### ISSUE TITLE
ng build --prod 10-20 times slower at 92% UglifyJSPlugin stage with the only difference being font awesome

### ISSUE THREAD

**Issue by sebastianbats** [FortAwesome/angular-fontawesome#102]
### Describe the problem

I had a project using material icons, in the end I didn't like the icons and how they aligned. Literally the only change to the project is using font awesome icons instead of material icons. 

Usually it would run about 10-20 seconds at the 92% UglifyJSPlugin stage when building with --prod which I'm assuming runs AOT and other stuff.

Now with fontawesome, I can just wait around for 5-10 minutes sometimes even 15 at a stage that used to last 20 seconds!!

I'm building stuff on an i7-7700k with 64GB ram and only SSD storage.

### What did you expect?

A much smaller impact

### Reproducible test case

Due to this having to be 'built for production' -- I can't share a stackblitz and my project does contain sensitive information that I cannot share. If you can't recreate this on any normal project out there, I can maybe do a screen recording for proof and offer some log?

**Comment by robmadole** [comment]
@sebastianbats check this for details on Tree Shaking. https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking

This is a bug with the uglifyjs project. The terser replacement fixes this.

**Comment by sebastianbats** [comment]
@robmadole  hmm -- I am importing each icon separately as described and relying on deep imports. 

I'll take a look at alternatives with Angular then, thanks!
