### ISSUE TITLE
Unable to use beyond 0.1.0-8

### ISSUE THREAD

**Issue by jfairley** [FortAwesome/angular-fontawesome#104]
### Describe the problem

Over the last few months, I have tried to upgrade to the latests periodically, but I always get the same error.

Currently I am trying:

```
"@fortawesome/angular-fontawesome": "0.2.1",
"@fortawesome/fontawesome-svg-core": "1.2.6",
"@fortawesome/free-brands-svg-icons": "5.4.1",
"@fortawesome/pro-light-svg-icons": "5.4.1",
"@fortawesome/pro-regular-svg-icons": "5.4.1",
"@fortawesome/pro-solid-svg-icons": "5.4.1"
```

The latest dependencies that I have found to work in my app are:

```
"@fortawesome/angular-fontawesome": "0.1.0-8",
"@fortawesome/fontawesome-free-brands": "5.0.13",
"@fortawesome/fontawesome-pro-light": "5.0.13",
"@fortawesome/fontawesome-pro-regular": "5.0.13",
"@fortawesome/fontawesome-pro-solid": "5.0.13",
"@fortawesome/fontawesome-svg-core": "1.2.0-14",
```

Please see https://github.com/jfairley/font-awesome-build-failure for a full sample project to reproduce what I am seeing.

Upgrading any piece yields the same error on init (see below).

### What did you expect?

I expect to be able to upgrade my dependencies and get the app to work.

### Reproducible test case

I've pushed code to a repository for testing:
﻿https://github.com/jfairley/font-awesome-build-failure

This is a much slimmed down version of my app code.

When I run `npm start`, I get the following browser console error.

```
angular-fontawesome.js?1dff:110
Uncaught TypeError: Cannot read property 'replacementClass' of undefined
    at eval (angular-fontawesome.js?1dff:110)
    at Module../node_modules/@fortawesome/angular-fontawesome/fesm5/angular-fontawesome.js (main.js:305)
    at __webpack_require__ (main.js:64)
    at eval (asset-icons-module.ts?091b:3)
    at Object../src/modules/asset-icons/asset-icons-module.ts (main.js:3358)
    at __webpack_require__ (main.js:64)
    at eval (index.ts?7175:1)
    at Object../src/modules/asset-icons/index.ts (main.js:3546)
    at __webpack_require__ (main.js:64)
    at eval (index.ts?9f62:1)
```

It seems that `config` from `import { config, icon, parse, text, counter } from '@fortawesome/fontawesome-svg-core';` is undefined.

---

Any help is appreciated.

I'm not using Angular CLI, but I hope that's not _the_ issue. I'm interested in staying with webpack.

**Comment by robmadole** [comment]
@jfairley it looks like you are using some pre-releases. Can you upgrade all your `@fortawesome` scoped dependencies and try again?

**Comment by jfairley** [comment]
@robmadole That's the point of this issue.

See my linked github repository.
https://github.com/jfairley/font-awesome-build-failure

I want to upgrade. When I do, I get errors. I've been punting this upgrade for months. :(

**Comment by jfairley** [comment]
In my linked repo, I'm pretty sure the `library.add(faXYZ)` is unnecessary. We do not use that style currently, but as I said, I've tried all the configuration options described in the repo readme.

**Comment by jfairley** [comment]
I've reworded the main description, hopefully for more clarity.

**Comment by devoto13** [comment]
Hi @jfairley! I've looked into your reproduction and the issue in your case is incorrectly configured `file-loader`. 

```
            {
                test: /\.gif|png|jpg|svg|woff|woff2|ttf|eot|ico(\?v=\d\.\d\.\d)?$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]'
                        }
                    }
                ]
            },
```

If you run `./node_modules/.bin/webpack --config playground/webpack.playground.js` you'll notice that some FA files end up in the `dist` folder in the completely unprocessed state (e.g. with original `import/export` keywords) instead of being included in the `main.js` bundle. This is because path to these modules includes `svg`, they will match the regex from above and be processed through `file-loader` instead of being processed as JS modules.

If you correct it by adding parentheses (`/(\.gif|png|jpg|svg|woff|woff2|ttf|eot|ico)(\?v=\d\.\d\.\d)?$/`) the bundling works correctly. The repro fails with the new error, but it does not seem to be related to FA.

**Comment by jfairley** [comment]
@devoto13 Thanks for the tip! I will go check out the new error!

**Comment by devoto13** [comment]
@jfairley Actually never mind about the new error. It was because I only started `webpack-dev-server`.    No errors now :)
