### ISSUE TITLE
Feature request:  fas-icon far-icon fab-icon

### ISSUE THREAD

**Issue by hhfrancois** [FortAwesome/angular-fontawesome#108]
### Describe the problem you'd like to see solved or task you'd like to see made easier

For simplify using fontawsesome with angular

```
<fas-icon icon="coffee"></fas-icon>   

<far-icon icon="coffee"></far-icon>   

<fab-icon icon="coffee"></fab-icon>

```
instead

```
<fa-icon [icon]="['fas', 'coffee']"></fa-icon>   

<fa-icon [icon]="['far', 'coffee']"></fa-icon>   

<fa-icon [icon]="['fab', 'coffee']"></fa-icon>

```

### Is this in relation to an existing part of angular-fontawesome or something new?

Just angular-fontawesome implementation

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?

make the API super-convenient 

### Why would other angular-fontawesome users care about this?

because it is easily to use

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

5 - "while we're young"

### Feature request checklist

- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [X] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment]
Thanks for the suggestion, but it is not something we want to implement.

See discussion in https://github.com/FortAwesome/angular-fontawesome/pull/110 for the reasoning.
