### ISSUE TITLE
unable to find rocketChat icon

### ISSUE THREAD

**Issue by RezaRahmati** [FortAwesome/angular-fontawesome#112]
### Describe the problem

I tried to use rocketchat as [https://fontawesome.com/icons/rocketchat?style=brands](https://fontawesome.com/icons/rocketchat?style=brands), but I couldn't make it work

### What did you expect?

Display rocketchat

### Reproducible test case

`<fa-icon [icon]="['fab', 'rocketchat' ]"></fa-icon>`

```
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.8",
    "@fortawesome/free-regular-svg-icons": "^5.5.0",
    "@fortawesome/free-solid-svg-icons": "^5.5.0",
```

**Comment by devoto13** [comment]
Did you add the icon to the `library`? See 1, 2, 3, 4, 5 in the [documentation](https://github.com/FortAwesome/angular-fontawesome#using-the-icon-library).

**Comment by RezaRahmati** [comment]
Yes I tried even I am not able to add it to library, also I checked the d.ts file, that icon is not there

I am able to use other icons such as comment, times, coffee

**Comment by devoto13** [comment]
Just noticed that you don't have `@fortawesome/free-brands-svg-icons` in your dependencies. The icon you're trying to use is from the Brands style as mentioned on the icon page you have linked. I checked the package and it contains the icon.

**Comment by RezaRahmati** [comment]
Oh Ok, thanks for help, I will check it out
