### ISSUE TITLE
Issue with FortAwesome Pro CDN

### ISSUE THREAD

**Issue by AvogadroSG1** [FortAwesome/angular-fontawesome#113]
Hi all!

I followed the instructions provided to add a .npmrc file for my packages and local npm to use.  Grabbed my token from my Pro account and pushed it into the .npmrc.

In visual studio 2017 version 15.8.5, when inside the packages.json file, input the "@forstawesome/pro-solid-svg-icons" : "XXXX"

Once I start trying to type into the XXXX area for the version number, VS freezes and will not go further.  In fact, need to terminate it and make sure to remove the prior line from my packages.json if it was saved.

I know this could be (most likely is) as VS problem, but wanted to make sure the CDN is performing correctly.

Thanks!
Peter

**Comment by devoto13** [comment]
Hi @AvogadroSG1!
Does `npm view @fortawesome/pro-light-svg-icons versions` return list of version, when you run it from terminal? If so, I would say it's either VS bug or misconfiguration.

**Comment by mlwilkerson** [comment]
Coincidentally, we _are_ having some CDN anomalies right now. Engineers are investigating a spike in traffic. Not sure if that's what would cause this freezing behavior in VS (seems like VS shouldn't freeze just because a network request like this might be slow).

See https://status.fortawesome.com/

> Our CDN provider is investigating reports of downtime for fontawesome.com and pro.fontawesome.com.

**Comment by devoto13** [comment]
https://status.fortawesome.com/ claims that all services are operational now, so closing the issue.

**Comment by robmadole** [comment]
Yep, this issue (when originally posted) would not have been related to the Pro CDN service.
