### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by piwko28** [FortAwesome/angular-fontawesome#114]
There is an information in package.json about MIT license, but there is no license file within repository nor github info.
I'd like to use this package in my project, but my organisation requires to law analysis.
I noted that there are license file in other FortAwesome repositories.
Could you please add the license?

I would be grateful for help.
Best wishes,
Szymon

**Comment by robmadole** [comment]
Thanks for helping us clean up our omission @piwko28 ! All fixed up.
