### ISSUE TITLE
Issue with FontAwesome in an Ionic application

### ISSUE THREAD

**Issue by JesperBalslev** [FortAwesome/angular-fontawesome#115]
I previously used FontAwesome 5 without using this package, with no problems, but it seems it is not updated anymore (last version 5.1).

After doing the installation as written by you fine guys, i tried starting up my app, and was met by this error:

`TypeError: Object(__WEBPACK_IMPORTED_MODULE_1__angular_core__["defineInjectable"]) is not a function. (In 'Object(__WEBPACK_IMPORTED_MODULE_1__angular_core__["defineInjectable"])({ factory: function FaIconService_Factory() { return new FaIconService(); }, token: FaIconService, providedIn: "root" })', 'Object(__WEBPACK_IMPORTED_MODULE_1__angular_core__["defineInjectable"])' is an instance of Object)
`

I am currently running Ionic 3 and Angular 5, so it might be an issue with compatibility, but i am having a hard time finding any information about the issue.

Any ideas?

As far as i can see, defineInjectable is an Angular 6 function only. Is there any way to use this library without upgrading to Angular 6?

**Comment by devoto13** [comment]
Hi @JesperBalslev! Yes, it is a compatibility issue. You can find information regarding supported Angular versions in the [CHANGELOG](https://github.com/FortAwesome/angular-fontawesome/blob/master/CHANGELOG.md) (maybe not super clear, but it's there 😄). The support for Angular 5 was dropped in 0.2.0, so I would recommend to stick with 0.1.1 until you upgrade your Angular version. 

Although we don't test it I that version should be compatible with all latest icon packages.

**Comment by JesperBalslev** [comment]
Thanks for the reply. I actually decided to go ahead and upgrade to Angular 6.1.10... It did not seem to break anything, so why not! :)

Thanks again, and while it took me some time to rewrite all my icons, it is well worth it, and i prefer this angular / web component approach. :)

**Comment by devoto13** [comment]
Great, @JesperBalslev! Happy you solved it.
