### ISSUE TITLE
fa-layers fixedWidth not supported attribute with Angular 5.x and Angular-FontAwesome 0.1.1

### ISSUE THREAD

**Issue by theCrius** [FortAwesome/angular-fontawesome#119]
### Describe the problem

I'm trying to implement stacked icons using the layers tag. While it definitely works with Angular 6+ and the latest version of this library, it seems to fail with the project I'm working on that is written in Angular 5.x and thus need a previous version of this library.

### What did you expect?

The fa-layers to work as in the example here: https://github.com/FortAwesome/angular-fontawesome#advanced-usage

### Reproducible test case

I used the template suggested (https://stackblitz.com/edit/angular-z8v4ux) and the feature works fine. I couldn't figure out how to have stackbliz install Angular 5.x and all dependencies and after some fiddling I realised it coudn't be anything else as if I literally copied and pasted the code from my project into stackbliz, it was working.

### Suggestion

I don't think retrofitting versions is a viable solution as especially angular follow a very quick release cycle. **It would be quite useful however to have a clear indication of "since which version" features are gonna be supported, in the example of usage or wherever necessary**.

I'll just use the straight html version for my case as shown here: https://fontawesome.com/how-to-use/on-the-web/styling/layering

**Comment by devoto13** [comment]
I'm going to close this issue. While it is a valid feature request, it didn't get any traction since it was reported and I still stand by my original opinion that maintaining since version everywhere is not worth the effort for the given size of the library. We can totally reconsider it in the future though.
