### ISSUE TITLE
Compatibility issue with IE 11: SCRIPT1003.

### ISSUE THREAD

**Issue by Fieel** [FortAwesome/angular-fontawesome#120]
### Describe the problem

When adding icons to my icons library in my app.module.ts file this library triggers a bug on IE which expects an object to be created using key:value pairs, this isn't happening for some reason, FA declares the object without this so IE crashes.

Error in question: https://docs.microsoft.com/it-it/previous-versions/bzt48fs6(v=vs.94)
My part of compiled vendor.js file that triggers the bug:
```
var _iconsCache = {
  faAd,
  faAddressBook,
  faAddressCard,
  faAdjust,
  faAirFreshener,
  faAlignCenter,
  faAlignJustify,
_..SHORTENED FOR CLARITY..._
}; 
```

The part of my app.module.ts file that triggers this bug: (removing this will resolve the bug, but i need the icons)
`library.add(faMapMarkerAlt, faExclamationTriangle, faCalendarAlt);`

Screenshots of the console:
![image](https://user-images.githubusercontent.com/11167635/50042453-47ed3100-0063-11e9-912d-95cdb0ee87a7.png)
![image](https://user-images.githubusercontent.com/11167635/50042461-5f2c1e80-0063-11e9-8637-fda536ff4cdb.png)

EDIT:

Tried using the icons explicitly without using the library and the same error happens.

### What did you expect?

It works on all major browsers except IE 11. I was expecting this to work on IE11 too given how avoidable this error is.

### Reproducible test case

This is a very simple and minimal issue, i believe there is no need of a test case. If it's needed i can provide one as soon as i have some time.

**Comment by fchiumeo** [comment]
update version font-awesome

[font-awesome #14382](https://github.com/FortAwesome/Font-Awesome/issues/14382)

**Comment by devoto13** [comment]
As @fchiumeo said. Update to 5.6.1, this was a regression in 5.6.0.
