### ISSUE TITLE
How to import the same icon from solid and regular library ?

### ISSUE THREAD

**Issue by WizardPC** [FortAwesome/angular-fontawesome#121]
### Describe the problem

I want to import "faStar" from the regular AND solid library. There is no example in the documentation to do this.

If i try to do :

```
import { faStar } from '@fortawesome/free-regular-svg-icons';
import { faStar } from '@fortawesome/free-solid-svg-icons';
```

I got an error because it's duplicate. 

I end up using this solution but i don't know if it's the rigth way...

```
import { faStar as farStar } from '@fortawesome/free-regular-svg-icons';
import { faStar as fasStar } from '@fortawesome/free-solid-svg-icons';
...
library.add(fasStar);
library.add(farStar);
...
<fa-icon [icon]="['fas', 'star']"></fa-icon>
<fa-icon [icon]="['far', 'star']"></fa-icon>
```

### What did you expect?

A tip to import an icon from both free library without importing all "far" and "fas" like this :

```
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/free-solid-svg-icons';
import { far } from '@fortawesome/free-regular-svg-icons';

library.add(fas, far);
```

**Comment by devoto13** [comment]
@WizardPC Your solution using import aliases is the correct way. 

Would you be willing to send a PR adding an example on how to use same icon from different styles under [Using other styles](https://github.com/FortAwesome/angular-fontawesome#using-other-styles) section?

**Comment by WizardPC** [comment]
I just see that aliases are used in the stackblitz example... It's just a missing doc issue so :+1: 

I haven't the time now cause of Christmas but here is my example :

Adding an icon from both Regular and Solid style:

```
import { faStar as farStar } from '@fortawesome/free-regular-svg-icons';
import { faStar as fasStar } from '@fortawesome/free-solid-svg-icons';

library.add(fasStar);
library.add(farStar);

```

```
<fa-icon [icon]="['fas', 'star']"></fa-icon>
<fa-icon [icon]="['far', 'star']"></fa-icon>
```

**Comment by MaklaCof** [comment]
Is this also a legitimate way?
```
import * as fas from "@fortawesome/pro-solid-svg-icons";
import * as fal from "@fortawesome/pro-light-svg-icons";
import * as far from "@fortawesome/pro-regular-svg-icons";

//Solid
library.add(fas.faHome);

//Light
library.add(fal.faHome);

//Regular
library.add(far.faHome);
```
I have TreeShaking in mind?

**Comment by devoto13** [comment]
@MaklaCof I'm not sure. My guess is that it may depend on the bundler/minifier used. If it works and unused icons are removed, then it is fine as well.

**Comment by WizardPC** [comment]
@MaklaCof can you compare the bundle size ?

**Comment by bjoernboeckle** [comment]
> import { faStar as farStar } from '@fortawesome/free-regular-svg-icons';
> import { faStar as fasStar } from '@fortawesome/free-solid-svg-icons';
> ...
> library.add(fasStar);
> library.add(farStar);
> ...
> <fa-icon [icon]="['fas', 'star']"></fa-icon>
> <fa-icon [icon]="['far', 'star']"></fa-icon>
> ```

Thanks for the posts, thats exactly what I did and it works fine in development.
The reason why I ended here ist that if I do a production build I'm getting errors that the icons are not defined as soon as I use a "as xxx" import.

No idea whats wrong, as mentioned I'm using exactly the syntax above.
Maybe anyone has an idea?

Thanks

**Comment by devoto13** [comment]
Hard to say, @bjoernboeckle. It seems to work for other people. Try to update to latest Angular CLI/Webpack and check if it is still broken. Otherwise you'll probably have to debug it yourself.

**Comment by bjoernboeckle** [comment]
Thanks a lot for your response, I'm using C# for many years now, but I'm new to angular and web development, so no idea why it doesnt' work; I'm already using the latest versions.

But in the mean time I solved it by using the code by MaklaCof below, as mentioned my first soution which was the same as the original post only works in development mode.

> `import * as fas from "@fortawesome/pro-solid-svg-icons";`
`import * as fal from "@fortawesome/pro-light-svg-icons";`
`import * as far from "@fortawesome/pro-regular-svg-icons";`
`library.add(fas.faHome, fal.faHome, far.faHome);`

**Comment by stephaniepurvis** [comment]
I just submitted a PR for something else in the documentation. Since I've already got this forked, would you like me to add this to the documentation in another PR? I'd be happy to help!

**Comment by devoto13** [comment]
Would be great if you add it, @stephaniepurvis. Thanks!
