### ISSUE TITLE
Lack of documentation on how to use fa-icon with svg sprite and symbols

### ISSUE THREAD

**Issue by jpzwarte** [FortAwesome/angular-fontawesome#122]
I'm creating this issue which basically is the same as #33 because there doesn't seem to be any activity on that issue.

I've found out that doing `<fa-icon [icon]="..." symbol="sprite"></fa-icon>` will create an svg element with a `<symbol>`. What i've failed to accomplish to actually use `<fa-icon>` to reference that symbol!

So how does one use `<fa-icon>` to output `<svg><use xlink:href="#fas-foo"></use><></svg>`.

I've tried reading the source but haven't found the answer that way.

Related: is there a best practice on how to create an svg sprite? So 1 `<svg>` element with > 1 `<symbol>`s?

**Comment by robmadole** [comment]
@jpzwarte the `<fa-icon>` component is intentionally not designed to output the `<svg><use ...` elements. Part of the reason that you would use a symbol over just a normal `<fa-icon>` is that you want to optimize performance. The use case for this is [outlined here](https://fontawesome.com/how-to-use/on-the-web/advanced/svg-symbols).

It's preferable that you go ahead and type directly in the `.html` file the `<svg><use xlink:href="#edit"></use></svg>`. This way you don't have any additional processing time in your app.

As far as performance this is really something that you need to measure. Use both approaches and see which works for your scenario.
