### ISSUE TITLE
Argument of type 'IconPack' is not assignable to parameter of type 'IconDefinitionOrPack'

### ISSUE THREAD

**Issue by ehujdur** [FortAwesome/angular-fontawesome#125]
### Describe the problem

Trying to import fab icons to angular project, but cli says there's the following error:

`error TS2345: Argument of type 'IconPack' is not assignable to parameter of type 'IconDefinitionOrPack'. Type 'IconPack' is missing the following properties from type 'IconDefinition': icon, prefix, iconName
`

**Comment by devoto13** [comment]
@ehujdur Can you also add your code, which leads to this error?

**Comment by AvogadroSG1** [comment]
I have this issue loading Regular Icons.

`
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { library } from '@fortawesome/fontawesome-svg-core';
import { fas } from '@fortawesome/pro-solid-svg-icons';
import { far } from '@fortawesome/pro-regular-svg-icons';
import { CreateProjectComponent } from './create-project/create-project.component';
import { CreateProjectWebprojectComponent } from './create-project-webproject/create-project-webproject.component';
import { CreateProjectChangeworkorderComponent } from './create-project-changeworkorder/create-project-changeworkorder.component';
import { ProjectDashboardComponent } from './project-dashboard/project-dashboard.component';
import { ProjectsRoutingModule } from './projects-routing.module';
import { CreateProjectCreateTaskComponent } from './create-project-create-task/create-project-create-task.component';

library.add(fas);
library.add(far);
`

**Comment by devoto13** [comment]
Can you mention versions of `@fortawesome/fontawesome-svg-core` and `@fortawesome/pro-regular-svg-icons` packages you use?

**Comment by AvogadroSG1** [comment]
Hi!  I'm very sorry for the delay.

![image](https://user-images.githubusercontent.com/3843680/53175973-1fca0300-35bb-11e9-8b42-75b506e52f4e.png)

**Comment by devoto13** [comment]
Do you use both `@fortawesome/fontawesome-pro` and `@fortawesome/angular-fontawesome` in the same project? This may be the source of the issue. Try removing `@fortawesome/fontawesome-pro` if you don't use it.

**Comment by AvogadroSG1** [comment]
Did try this with and without because I wasn't sure.  I removed it, still have the problem.  Here's my module's FA imports and statements.
![image](https://user-images.githubusercontent.com/3843680/53177270-b7c8ec00-35bd-11e9-811c-dc290e343594.png)

**Comment by devoto13** [comment]
Managed to reproduce it, investigating.

**Comment by devoto13** [comment]
So the issue seems to be that you ended up having two instances of `@fortawesome/fontawesome-common-types` of different versions installed.

Can you first try to open your `package-lock.json` and search for `"@fortawesome/fontawesome-common-types": {`? Does it find more than one result? If so try changing `@fortawesome/fontawesome-svg-core` to `^1.2.12` and running `npm install` to force it to update and de-duplicate?

**Comment by AvogadroSG1** [comment]
I couldn't get it to force the install, so I removed it from packages.json and then readded it.  Now all point to ^0.2.15. (While before one was pointing to 0.2.12)

So the better question, is this an NPM issue or a deployment problem from the package?

**Comment by devoto13** [comment]
It's is a consequence of how FontAwesome packages are structured. Let's keep this issue open, I'lll think how we can prevent this from happening in the future.

**Comment by AvogadroSG1** [comment]
Thanks for your help!

**Comment by AndreKoepke** [comment]
I had the problem too, the solution was to add a missing import-statement.

```css
@import "~@fortawesome/fontawesome-free/css/regular.css";
@import "~@fortawesome/fontawesome-free/css/solid.css";
@import "~@fortawesome/fontawesome-free/css/fontawesome.css";
@import "~@fortawesome/fontawesome-free/css/brands.css"; // <- this one was missing
```

**Comment by caleuanhopkins** [comment]
Hey so running into this issue also. Been using Pro on an angular 7 project for months, no issues what so ever. Tried to load the `faGoogle` icon and get these errors:

![Screenshot 2019-06-28 at 13 05 46](https://user-images.githubusercontent.com/1164525/60341238-c37e5200-99a5-11e9-967a-098d6c953646.png)
![Screenshot 2019-06-28 at 13 05 36](https://user-images.githubusercontent.com/1164525/60341239-c416e880-99a5-11e9-9f2b-c80f3821f089.png)

package.json:

```
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-brands-svg-icons": "^5.9.0",
    "@fortawesome/free-regular-svg-icons": "^5.9.0",
    "@fortawesome/pro-light-svg-icons": "^5.6.3",
    "@fortawesome/pro-regular-svg-icons": "^5.6.3",
    "@fortawesome/pro-solid-svg-icons": "^5.6.3",
```

**Comment by devoto13** [comment]
@caleuanhopkins Can you try to perform steps described in https://github.com/FortAwesome/angular-fontawesome/issues/125#issuecomment-466036515 to see if you have two instances of the `@fortawesome/fontawesome-common-types` package?

**Comment by caleuanhopkins** [comment]
Can only find the 1 instance in the lock file and looks like all the libraries are loading the correct version in their dependency:

![Screenshot 2019-06-28 at 13 11 44](https://user-images.githubusercontent.com/1164525/60341452-7babfa80-99a6-11e9-8eb3-74c51ace3dba.png)

**Comment by devoto13** [comment]
@caleuanhopkins Something looks odd, e.g.: `@fortawesome/pro-light-svg-icons` is of version `^5.6.3` in the `package.json` and `5.8.2` in your `package-lock.json` screenshot. Can you ensure that these are from the same project and same version of the project and you have run `npm install`?

**Comment by caleuanhopkins** [comment]
Ok apologies! 🤦‍♂ 

Using Yarn to install packages and noticed after I remove the `package-lock.json` that yarn has it's own `lock.json` file and yes I can see more than 1 `@fortawesome/fontawesome-common-types` package.

have removed the incorrect package now from the `yarn.lock`, reinstalled `node_modules` and is working now 👍

**Comment by devoto13** [comment]
Please check https://github.com/FortAwesome/angular-fontawesome/issues/125#issuecomment-466036515 for instructions how to diagnose and workaround this issue.

**Comment by epstarr** [comment]
Running into the issue mentioned above, my `package.json` and `package-lock.json` look like this:

![image](https://user-images.githubusercontent.com/4422380/66211182-20626600-e681-11e9-83fb-d36fe5451d2a.png)

![image](https://user-images.githubusercontent.com/4422380/66211134-06288800-e681-11e9-99a5-0ce68a06b1b3.png)

What I've done to get it to work is clear out lines 2549-2555 in my `package-lock.json` file, and change line 2548 to 
`"@fortawesome/fontawesome-common-types": "^0.2.22"`
to match with the other packages.

However, I can't keep having to do this after each npm install, especially when builds are built and deployed through CI. Since all my packs are the same version, why does the brands one have this extra dependency and it requires a different version of the `@fortawesome/fontawesome-common-types`?

**Comment by devoto13** [comment]
@epstarr Explicitly specifying `@fortawesome/fontawesome-common-types` is one possible solution.

Your approach didn't work, because `@fortawesome/free-brands-svg-icons` 5.11.1 does require `@fortawesome/fontawesome-common-types` 0.2.24 or newer (so 0.2.22 does not satisfy the requirement). That's why hoisting didn't happen. What you may do instead is to either remove all records related to `@fortawesome/*` packages from the `package-lock.json` and run `npm install` to get all the latest versions or alternatively remove all records for `@fortawesome/fontawesome-common-types` and it should *probably* hoist as well.

**Comment by PatricNox** [comment]
Removing the `yarn.lock` file and running install again solved it, thanks!
Maybe a `package-lock.json` & `yarn.lock` interference? 

I of course don't use both, but I know that a new team mate may or may not have been fiddling around this.

**Comment by arno-developer** [comment]
I had the same issue, but the cause of my issue was that my @fortawesome/free-brands-svg-icons package was one (1) version newer than the rest of the fontawesome packages

**Comment by launchdex** [comment]
Fixed issue by using IconDefinition

`import { library, IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faTwitter,
  faGithub,
  faDiscord,
  faTelegram,
  faMedium
} from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';

library.add(
  faTwitter as IconDefinition,
  faGithub as IconDefinition,
  faDiscord as IconDefinition,
  faTelegram as IconDefinition,
  faMedium as IconDefinition
);`

**Comment by mightykip** [comment]
I've tried everything.

Here's what is in my package.json:

    "@fortawesome/angular-fontawesome": "^0.8.2",
    "@fortawesome/fontawesome-svg-core": "^1.3.0",
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-regular-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",

Every time I run an 'npm install' I get multiple versions of "@fortawesome/fontawesome-common-types" so I get the error:

Types of property 'iconName' are incompatible.

If I hand edit the package.json file and remove the duplicates everything works... but every time I run 'npm install' I have duplicates again.

Can anyone please help?

Our build script automatically runs 'npm install' so the build always fails.

If it helps my node version is v16.14.0 and for npm I've tried versions 6, 7, and 8 with the same problem.

**Comment by mightykip** [comment]
> 

I'd love a better fix... but this is the only thing that has worked for me.

**Comment by PatricNox** [comment]
> Can anyone please help?


if you remove  the .lock file and run npm install, does it still cause duplicates?

**Comment by mightykip** [comment]
Yes.

**Comment by mightykip** [comment]
> if you remove the .lock file and run npm install, does it still cause duplicates?

Yes, I still can duplicates if I delete the .lock file.

**Comment by mightykip** [comment]
> faTwitter as IconDefinition

It's not ideal but this solution did work for now.

Thanks @launchdex !

**Comment by devoto13** [comment]
Hey @mightykip, Sorry for the late response!

I've rasied this problem upstream in https://github.com/FortAwesome/Font-Awesome/issues/16592#issuecomment-1053578571. To resolve it on your side (for now), please change `"@fortawesome/fontawesome-svg-core": "^1.3.0"` to `"@fortawesome/fontawesome-svg-core": "~1.2.36" and `npm install`.

I hope that my proposal will get accepted and we can finally resolve this type compatibility mess.

I've also created https://github.com/FortAwesome/angular-fontawesome/issues/346, which I'm going to look into once I have a response to my proposal.

**Comment by robmadole** [comment]
We are implementing @devoto13's proposal (it's a good one!) and it will be available in 6.1.0.

**Comment by devoto13** [comment]
@robmadole Will this part of the proposal be implemented as well? It is crucial as otherwise, people will keep facing the same problem because `^1.2.x` will automatically install 1.3.0 and cause the error. E.g. https://github.com/FortAwesome/angular-fontawesome/issues/350

> I think we should publish @fortawesome/fontawesome-svg-core 6.0.0 and @fortawesome/fontawesome-common-types 6.0.0, then mark @fortawesome/fontawesome-svg-core 1.3.0 and @fortawesome/fontawesome-common-types 0.3.0 as deprecated, so that package managers will avoid these versions when resolving ^1.2.14 range, but will keep these version published to avoid breaking people who have already installed them.

**Comment by robmadole** [comment]
@devoto13 yes. I'll be deprecating those. I will also be pinning each of the icon packages (like `@fortawesome/free-solid-svg-icons`) to use `@fortawesome/fontawesome-svg-core` at `6.1.0` instead of `^6.1.0`. It just doesn't make sense to let that dependency be out of sync with the exact version of the icon packages.

I think at one point we thought it might be useful to release these things with patch releases outside the normal Font Awesome release process. But that idea hasn't panned out (we've never done that to my knowledge.) So it makes sense to just keep all these version grouped together and all dependencies will match.

**Comment by robmadole** [comment]
Ok @devoto13 both of those packages are now deprecated. Hopefully that will clean up the mess! Thanks again for helping us with this one.

**Comment by Husdady** [comment]
Hi developer, I haver another other solution for this problem:

`
import { fas } from '@fortawesome/free-solid-svg-icons'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { far } from '@fortawesome/free-regular-svg-icons'
import { library, IconPack } from '@fortawesome/fontawesome-svg-core'

library.add(
  far as IconPack,
  fas as IconPack,
  fab as IconPack
)
`

**Comment by rubenheymans** [comment]
I had to set the versions fixed to make it work. deleted package-lock and ran npm i again
```
    "@fortawesome/angular-fontawesome": "0.11.1",
    "@fortawesome/fontawesome-svg-core": "6.2.1",
    "@fortawesome/free-brands-svg-icons": "6.2.1",
    "@fortawesome/free-solid-svg-icons": "6.2.1",
```

**Comment by fontanon** [comment]
> Hey @mightykip, Sorry for the late response!
> 
> I've rasied this problem upstream in [FortAwesome/Font-Awesome#16592 (comment)](https://github.com/FortAwesome/Font-Awesome/issues/16592#issuecomment-1053578571). To resolve it on your side (for now), please change `"@fortawesome/fontawesome-svg-core": "^1.3.0"` to `"@fortawesome/fontawesome-svg-core": "~1.2.36"` and `npm install`.
> 
> I hope that my proposal will get accepted and we can finally resolve this type compatibility mess.
> 
> I've also created #346, which I'm going to look into once I have a response to my proposal.

Worked like a charm. Thanks.
