### ISSUE TITLE
@fortawesome/Angular-FontAwesome npm package with ng-packagr

### ISSUE THREAD

**Issue by alc86** [FortAwesome/angular-fontawesome#129]
We create for our angular projects a private npm UI package which contains our UI components. Now I tried to add all our needed Icons from FontAwesome to the Library. We use the ng-packagr to generate the npm package this works without any issue. If I our package then I get a build issue:

Error during template compile of 'WebUiModule'
  Could not resolve @fortawesome/angular-fontawesome relative to [object Object].

Our idea is that we define all our needed Icons at the UI npm package an use only the ones we defined there.

**Comment by devoto13** [comment]
It's hard to understand what you're trying to do and what may be the issue just from the short description. But if you manage to create a small reproduction on GitHub I can take a look.

**Comment by devoto13** [comment]
Closing as it is not actionable without more information or reproduction.
