### ISSUE TITLE
Angular 7, problem with sizing

### ISSUE THREAD

**Issue by aster-orthrinos** [FortAwesome/angular-fontawesome#130]
Hi!

"@angular/core": "7.0.2"
angular-fontawesome": "0.3.0"
free-solid-svg-icons": "5.7.2"

 So I put icon in my project like this:
```
<fa-icon
                [icon]="['fas', 'spinner']"
                [spin]="!groups"
                [size]='3x'></fa-icon>
```

and I have following error:

compiler.js:2547 Uncaught Error: Template parse errors:
Parser Error: Unexpected token 'x' at column 2 in [3x] in ng:///AppModule/ItemsWithGroupsComponent.html@20:16 ("
                [icon]="['fas', 'spinner']"
                [spin]="!groups"
                [ERROR ->][size]='3x'></fa-icon>

if i write '3' instead of '3x' I got no desired size and this html is generated:

`<fa-icon _ngcontent-c3="" class="ng-fa-icon" ng-reflect-icon-prop="fas,spinner" ng-reflect-spin="false" ng-reflect-size="3"><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="spinner" class="svg-inline--fa fa-spinner fa-w-16 fa-3" ...........</fa-icon>`

and if I change 'fa-3' in this html right in my browser to 'fa-3x' then I have desired size.
So what could be wrong?

**Comment by devoto13** [comment]
```
[size]='3x' -> size="3x"
// or 
[size]='3x' -> [size]="'3x'"
```

You want `3x` to be treated as a string literal, not as a variable name or number. See [this answer](https://stackoverflow.com/a/36220057/1377864) for more details.

**Comment by aster-orthrinos** [comment]
Sorry for so simple question, somehow I missed out that square brackets were not present in tutorial...

Thank you!
