### ISSUE TITLE
Installation-Guide via NPM missing

### ISSUE THREAD

**Issue by de-mim-1974** [FortAwesome/angular-fontawesome#132]
I was try to Install this with "yarn", but I got that warning:

> package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> [1/4] Resolving packages...
> warning @angular-devkit/build-angular
> ...

My Angular 6 Application is not a fresh created with Angular-CLI, it was crated with Angular-CLI some month ago. So I don't want to mix the package mangers. I like to stay at npm because in the past I've installed many packages via npm.

I was try to install package with npm:
```
npm install @fortawesome/fontawesome-svg-core
npm install @fortawesome/free-solid-svg-icons
npm install @fortawesome/angular-fontawesome
```

In app.module.ts I've add the FontAwesomeModule:
```
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faCoffee, faRoad } from '@fortawesome/free-solid-svg-icons';

library.add(faRoad);

@NgModule({
  imports: [
    BrowserModule,
    FontAwesomeModule,
...
```
When I run the Application I get the follow error:
```core.js:1598 ERROR Error: Uncaught (in promise): Error: Template parse errors:
'fa-icon' is not a known element:
1. If 'fa-icon' is an Angular component, then verify that it is part of this module.
2. If 'fa-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

  <div style="text-align:center">
    Test: [ERROR ->]<fa-icon icon="road"></fa-icon>
  </div>
...
```

I could not get answers to my problems or questions about this project through Google.

Why does the Import of the FontAwesomeModule not register the 'fa-icon' element-type?
Why have the project only a Install-Guide for Yarn and no Guide for NPM?

**Comment by stephaniepurvis** [comment]
You need to put the library.add(faRoad); in the exports

![screen shot 2019-02-26 at 10 13 57 am](https://user-images.githubusercontent.com/3844427/53427910-65b60b00-39af-11e9-925a-b722c071fcb5.png)

**Comment by de-mim-1974** [comment]
Thank you Stephanie! Good point! 
I've change it in app.module.ts.

The Error 

`'fa-icon' is not a known element:`

is still there :(

**Comment by devoto13** [comment]
@de-mim-1974 Most likely you try to use `fa-icon` in the component, which is declared not in `AppModule`, but in some other module. Make sure to import `FontAwesomeModule` into the module, where component you plan to to add icon to is present in `declarations` array.

**Comment by de-mim-1974** [comment]
@devoto13 Thank you, that was the cause. I had to implement it in my `home.module.ts`. I am ashamed a little.
