### ISSUE TITLE
main readme.md includes incorrect command "fort" not "font"

### ISSUE THREAD

**Issue by jordan112** [FortAwesome/angular-fontawesome#133]
### Describe the problem

yarn add @fortawesome/fontawesome-svg-core \
  yarn add @fortawesome/free-solid-svg-icons \
  yarn add @fortawesome/angular-fontawesome

**Comment by robmadole** [comment]
Hey @jordan112 the “fort” is actually correct. Are you having trouble installing them?

**Comment by jordan112** [comment]
Oh, my apologies.  It was just unexpected.  thanks.
