### ISSUE TITLE
Add docs for unit testing

### ISSUE THREAD

**Issue by danieldanielecki** [FortAwesome/angular-fontawesome#135]
The [react-fontawesome](https://github.com/FortAwesome/react-fontawesome) dependency includes [documentation for unit testing](https://github.com/FortAwesome/react-fontawesome#unit-testing). It would be good to have it here as well.

**Comment by devoto13** [comment]
Related to #134.

**Comment by danieldanielecki** [comment]
It's overcomplicated there, that's why decided to open a new issue based on solution which already exists for React.

**Comment by damienwebdev** [comment]
@devoto13 I'm not certain on this one, but potentially we should have a docs site? Having all the content in the README has maybe run its course, as it's starting to become tediously large. We could simply utilize Github Pages as a starter and grow from there.

**Comment by damienwebdev** [comment]
Additionally, I don't have any idea how https://fontawesome.com/how-to-use/on-the-web/using-with/angular gets updated, so we may want to figure out how to manually build to that point and keep that updated.

**Comment by mlwilkerson** [comment]
@damienwebdev That doc on `fontawesome.com` is updated only from within our private/internal web app that deploys to `fontawesome.com`. So yes, keeping things in sync can be a challenge. We've fallen out of sync before with the Ember component, for example.

In general, I think we're trying to strike the right balance between: on the one hand, having an initial eyeful of quick start info there on our website where new users/customers may be discovering how to integrate Font Awesome in their project, and on the other hand, delegating most of the details to where the project is actively maintained here in GitHub. Admittedly, having too much detail on our site runs the risk of falling out of date with what's on GitHub, especially when there are breaking changes; but having too little might also feel a little user-unfriendly to those who find their way to the component through `fontawesome.com`.

As for where precisely to draw to that line, we're flexible. My general leaning would be to delegate _more_ to the GitHub docs, so it's less likely to fall out of sync. But also, we can push changes to those docs on `fontawesome.com` for the occasional breaking change--no problem.

By comparison with an analogous project, here's where we're at with the [Ember component](https://fontawesome.com/how-to-use/on-the-web/using-with/ember).

Thanks for your contributions to this repo!

**Comment by devoto13** [comment]
For reference: https://github.com/FortAwesome/angular-fontawesome/issues/186#issuecomment-535845363

**Comment by christiancueto** [comment]
Has there been any updates on this? `FontAwesomeTestingModule` seems like the thing I need right now as I replace the icons at work to use this package and need to update tests

**Comment by devoto13** [comment]
@christiancueto `FontAwesomeTestingModule` has been implemented, but not yet released. If you want it right now, I can suggest [copying](https://github.com/FortAwesome/angular-fontawesome/blob/master/testing/src/testing.module.ts) [implementation](https://github.com/FortAwesome/angular-fontawesome/blob/master/testing/src/icon/mock-icon-library.service.ts) into your project and switch to the official version once it is released.

What `FontAwesomeTestingModule` does is that it replaces icon library with a mock, which always returns a dummy icon, so you don't need to add icons to the library in every test. Alternative approach is to use regular `FontAwesomeModule` in tests and actually configure `FaIconLibrary` with the icons necessary in the test.

[Explicit reference](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/explicit-reference.md) approach does not require any special configurations for unit tests.

**Comment by christiancueto** [comment]
@devoto13 Using the suggestion above, I still see the following error:
`Could not find icon with iconName=ellipsis-h and prefix=fas. This warning will become a hard error in 0.6.0`
as well as a new error:
`Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "undefined". `

**Comment by damienwebdev** [comment]
@christiancueto I wrote a test scenario that covers this. Try and use this for inspiration in your test and let me know if it works.

https://github.com/FortAwesome/angular-fontawesome/blob/master/testing/test/integration/module-test.spec.ts

**Comment by christiancueto** [comment]
@damienwebdev Thanks for your prompt responses! I think the path error is valid, I pulled repo and ran the test suite locally:
![Screen Shot 2019-11-01 at 11 27 05 AM](https://user-images.githubusercontent.com/8916062/68035852-e2199000-fc9a-11e9-8384-d357fa8e2e6f.png)

**Comment by devoto13** [comment]
Good catch @christiancueto. I have now fixed this in https://github.com/FortAwesome/angular-fontawesome/pull/194.

As for `Could not find icon with iconName=ellipsis-h and prefix=fas. This warning will become a hard error in 0.6.0`, it may be coming from another test case, which does not import `FontAwesomeTestingModule`.
