### ISSUE TITLE
[animation] fa-spin is being applied for class fa-pulse

### ISSUE THREAD

**Issue by nartc** [FortAwesome/angular-fontawesome#136]
### Describe the problem

![image](https://user-images.githubusercontent.com/25516557/56874471-b07bef80-69ff-11e9-856e-aeda8dc7bb54.png)

### What did you expect?

setting `[pulse]` should have `pulse` animation instead of `spin`

**Comment by devoto13** [comment]
It does not sound very logical, but according to [documentation](https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons) this is intended behavior:

> use fa-pulse to have it rotate with 8 steps

`angular-fontawesome` is a thin wrapper around the [core Font Awesome](https://github.com/FortAwesome/Font-Awesome) library, so we can't really do anything about it here. I would recommend to open an issue in the core library to discuss this problem and if it is fixed there it will automatically propagate to the `angular-fontawesome`.

**Comment by nartc** [comment]
Sounds good. Thanks

**Comment by nartc** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/14694 

So it's actually intended to rotate with 8 steps. That's a weird naming.

Everything's clear now.
