### ISSUE TITLE
Want pass icon name as a variable

### ISSUE THREAD

**Issue by chiraggmodi** [FortAwesome/angular-fontawesome#140]
I am getting Icon name from http request and want to pass that name as a icon name
but when i do that i am getting this error
`FontAwesome: Could not find icon with iconName=facebook and prefix=fas`

here is my code in html
```
<li class="list-inline-item" *ngFor="let social_icon of SociaIconsLink">
   <a [href]="social_icon.social_link" target="_blank">
       <fa-icon [icon]="social_icon.social_name" ></fa-icon>
    </a>
 </li>
```

**Comment by devoto13** [comment]
Most likely your forgot to add this icon to the library using `library.add(...)`. See [documentation](https://github.com/FortAwesome/angular-fontawesome#using-the-icon-library) for more information.

**Comment by bartdebever** [comment]
Note that it's also stating `facebook and prefix=fas`. The Facebook icon is within the Brands library so should be with the 'fab' prefix.
