### ISSUE TITLE
The installation instructions will not work if your project isn't already Angular 8.  

### ISSUE THREAD

**Issue by jamisonroberts** [FortAwesome/angular-fontawesome#145]
### Describe the problem

The installation instructions will not work if your project isn't already Angular 8.  

### Reproducible test case

If you have an Angular 6 or 7 project and follow the instructions, you will end up with angular-fontawesome version 0.4.0 (as of now).  This appears to require angular 8, and you will end up with build error "export 'defineinjectable' was not found in '@angular/core'

Not so much as a defect but rather documentation clarification.

**Comment by fchiumeo** [comment]
see [changelog](https://github.com/FortAwesome/angular-fontawesome/blob/master/CHANGELOG.md#040---2019-03-28)

**Comment by devoto13** [comment]
Thanks @fchiumeo!

It would be good to have a compatibility table close to the Installation section of the README (like [here](https://github.com/ng-bootstrap/ng-bootstrap#dependencies)). PRs welcome!

**Comment by martinkasa** [comment]
Author states he is using semantic versioning. Breaking something means increase of major version. Removing Angular v6 and v7 support is breaking change.

**Comment by devoto13** [comment]
See point 4 in the specification: https://semver.org/
Currently we avoid breaking changes in patch releases only.

**Comment by martinkasa** [comment]
ok, thanks for poiting out.
