### ISSUE TITLE
Layers Counter / Text not working in Angular 8 with Ivy enabled

### ISSUE THREAD

**Issue by andan604** [FortAwesome/angular-fontawesome#154]
### Describe the problem

Everything in a component after `<fa-layers>` with `<fa-layers-counter>` or `<fa-layers-text>` stop rendering if Ivy has been enabled. The console prints the following error:

> ERROR Error: inject() must be called from an injection context
>     at injectInjectorOnly (core.js:651)
>     at Module.ɵɵinject (core.js:667)
>     at FaLayersTextBaseComponent_Factory (angular-fontawesome.js:462)
>     at NodeInjectorFactory.FaLayersCounterComponent_Factory [as factory] (angular-fontawesome.js:627)
>     at getNodeInjectable (core.js:8939)
>     at instantiateAllDirectives (core.js:15215)
>     at createDirectivesAndLocals (core.js:14611)
>     at ɵɵelementStart (core.js:19505)
>     at Module.ɵɵelement (core.js:19604)
>     at AppComponent_Template (app.component.html:3)

### What did you expect?

I would expect it to work, even if Ivy is enabled :)

### Reproducible test case

I've been unable to get StackBlitz to run an Ivy-enabled project. So here's some instructions on how to set something up locally:

`ng new fa-issue --enableIvy=true --minimal=true`

`npm install @fortawesome/fontawesome-svg-core @fortawesome/free-solid-svg-icons @fortawesome/angular-fontawesome`

In app.module.ts:

```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faShoppingCart } from '@fortawesome/free-solid-svg-icons';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [ AppComponent ],
  imports: [ BrowserModule, FontAwesomeModule ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor() { library.add(faShoppingCart); }
}
```

In app.component.html:

```html
<fa-layers [fixedWidth]="true">
  <fa-icon icon="shopping-cart"></fa-icon>
  <fa-layers-counter content="99+"></fa-layers-counter>
</fa-layers>
Hello!
```

Running ng --version:
```
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.0
Node: 10.16.0
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
```

By changing "enableIvy" to false in tsconfig.app.json the application starts to work as expected.

**Comment by devoto13** [comment]
Seems to be an issue in Angular itself. Let's see if https://github.com/angular/angular/pull/31379 solves this and if not, I'll refactor our code.
