### ISSUE TITLE
Feature request: Add support for the new duotone icons

### ISSUE THREAD

**Issue by JaxonWright** [FortAwesome/angular-fontawesome#156]
### Describe the problem you'd like to see solved or task you'd like to see made easier

Add support for the newly-announced FontAwesome Duotone icons which are a part of the Pro version.

### Is this in relation to an existing part of angular-fontawesome or something new?

Something new.

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?

Add directives that make manipulating their unique nature feel like it is done in an "Angular way".

### Why would other angular-fontawesome users care about this?

It is a hot new icon set that FontAwesome undoubtedly wants all of its users to try out.

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

10

**Comment by jnurse13** [comment]
Yes please

**Comment by LewisBrowne** [comment]
I support this.

**Comment by devoto13** [comment]
It's coming. In the meantime you can use all the features of duotone icons with existing `fa-icon` by passing desired classes or styles using `classes` and `styles` properties. E.g. 

```
<fa-icon [icon]="faCamera" [classes]="['fa-swap-opacity']"></fa-icon>
<fa-icon [icon]="faCamera" [styles]="{'--fa-secondary-opacity': '0.20'}"></fa-icon>
```
