### ISSUE TITLE
Need a proper documentation for implementation.

### ISSUE THREAD

**Issue by sheikalthaf** [FortAwesome/angular-fontawesome#16]
Need a proper guide to implement the component.
1. how to import module
2. how to use component

**Comment by mlwilkerson** [comment]
Hi @sheikalthaf in preparation for our next release, we've put out pre-release `0.1.0-6`, which includes some more documentation.

I'll close this issue against PR #20. But do have a look and let us know if you think something important is missing from the docs.

Here are some links into relevant docs:

- [README.md](https://github.com/FortAwesome/angular-fontawesome/blob/master/README.md)

- [UPGRADING.md](https://github.com/FortAwesome/angular-fontawesome/blob/master/UPGRADING.md)
- [Examples](https://github.com/FortAwesome/angular-fontawesome/tree/master/examples)

**Comment by mlwilkerson** [comment]
UPDATE: I previously had referenced a different pre-release version in my last comment. That pre-release npm package was broken. Updated that to refer to a new, fixed pre-release version.
