### ISSUE TITLE
Migration document 0.4.0 -> 0.5.0 misleading

### ISSUE THREAD

**Issue by bjornharvold** [FortAwesome/angular-fontawesome#169]
### Describe the problem

The doc refers to an "add" method that does not exist on the new library object. 

### What did you expect?

Should say "addIcons"

**Comment by devoto13** [comment]
@bjornharvold Do you mean this one?

<img width="382" alt="image" src="https://user-images.githubusercontent.com/823594/62851244-c3cc7580-bce5-11e9-80e4-03ca038a2cb8.png">

**Comment by danieldiazastudillo** [comment]
Stackblitz example is misleading. Not using the same approach from the one used in Using Icon Library.

**Comment by rooby** [comment]
I would say it is misleading in that it says 

> Icon library from @fortawesome/fontawesome-svg-core (referred as global icon library) is deprecated in favour of FaIconLibrary provided by @fortawesome/angular-fontawesome and managed by Angular (referred as icon library).

however if I remove the @fortawesome/fontawesome-svg-core package from my package.json I get a bunch of errors that come from @fortawesome/angular-fontawesome importing type definitions from @fortawesome/fontawesome-svg-core.

So you currently still need to have the @fortawesome/fontawesome-svg-core package installed becuase it is not listed as a dependency of @fortawesome/angular-fontawesome

**Comment by devoto13** [comment]
@danieldiazastudillo There is one Stackblitz to be updated in the [README](https://github.com/FortAwesome/angular-fontawesome#stackblitz) and another one in the issue template. Did you have anything else in mind?

@rooby The migration guide doesn't mention that you should remove `@fortawesome/fontawesome-svg-core` from your dependencies. It is still a [peer dependency](https://github.com/FortAwesome/angular-fontawesome/blob/master/package.json#L88) and is used internally by components. New icon library is the first step of our effort to hide `fontawesome-svg-core` dependency from the `angular-fontawesome` consumers and make it an implementation detail. 

I'll update the migration guide to mention that you should not remove a dependency explicitly. Thanks for the feedback!

**Comment by devoto13** [comment]
Updated both Stackblitz examples and added note to the upgrade guide that `@fortawesome/fontawesome-svg-core` dependency should not be removed.

**Comment by devoto13** [comment]
Problems reported in this issue were resolved. Feel free to open a new issue if you still experience troubles with the upgrade.
