### ISSUE TITLE
How to specify icon color

### ISSUE THREAD

**Issue by devakone** [FortAwesome/angular-fontawesome#17]
How would you specify a specific color for an icon?

Thank you

**Comment by robmadole** [comment]
Hi @devakone . The icons will inherit, through CSS, the color from its parent. So just use CSS :)

**Comment by danieldanielecki** [comment]
Code snippet for people looking for it, will change color on hover (**.scss** code):

```
a:hover svg.fa-behance path {
  transition: 1s;
  fill: #1769ff;
}
```

**Comment by blogcraft** [comment]
Duotone works the same?
