### ISSUE TITLE
Font weight css property not working

### ISSUE THREAD

**Issue by jgomesmv** [FortAwesome/angular-fontawesome#174]
### Describe the problem

When I set a css class with a specfic font-weight value the icon weight don't change
The icon font-weight remains the same

### What did you expect?

The icon appearance to change when I set the font-weight  value

### Reproducible test case

Icon tag:
<fa-icon [icon]="['fal', 'angle-down']" class="angleIcon"></fa-icon>

Css class:
  &__accordionOpenAnchorIcon {
    position: relative;
    right: 8px;
    bottom: 20px;
    float: right;
    font-weight: 900 !important;
    font-size: 15px;
  }

**Comment by devoto13** [comment]
`angular-fontawesome` renders icons using SVG images, not fonts, so `font-weight` is expected to have no effect. 

If you want to render an icon to the icon from another style you'll need to modify the `icon` input property. Please, check https://github.com/FortAwesome/angular-fontawesome/issues/159#issuecomment-519527147 and let me know if it helps. It seems to be similar to what you're trying to do.

**Comment by jgomesmv** [comment]
OK understood. So there it less flexibility, you can only use the available properties.
To set the icon weight:
Solid
Regular
Light

To set the size:
fa-xs
fa-sm
fa-lg
fa-2x
fa-3x
fa-5x
fa-7x
fa-10x

Or there is another way to style size and weight?

**Comment by devoto13** [comment]
For the weight, yes. Note that different styles do not only change icon thickness, but also the shape of the icon (e.g. filled or not, etc).

As for the size, besides the property, an icon will also inherit the font-size of the place where it is rendered, so it aligns with the surrounding text: https://stackblitz.com/edit/angular-z8v4ux-drdc85?file=src%2Fapp%2Fapp.component.html.

**Comment by jgomesmv** [comment]
OK! Clear answer! Thanks for your help!

**Comment by forgantini** [comment]
Just in case, i made a directive that adds the _stroke-width_ and _stroke_ properties to the _path_ svg tag, having the same effect as the bold.
Here the interesting section: 
`const pathElement: SVGPathElement = this.elementRef.nativeElement.querySelector('path');
  this.renderer.setStyle(pathElement, 'stroke-width', '20');
  this.renderer.setStyle(pathElement, 'stroke', this.color);
`
