### ISSUE TITLE
fa-stack renders blank, but removing wrapper renders icons

### ISSUE THREAD

**Issue by MrSuttonmann** [FortAwesome/angular-fontawesome#177]
I want to display an icon stack on my page, so this is what I have:

```
<fa-stack>
  <fa-icon [icon]="['fal', 'lock']"></fa-icon>
  <fa-icon [icon]="['fal', 'ban']"></fa-icon>
</fa-stack>
```

However, this renders completely empty: 
![image](https://user-images.githubusercontent.com/7480500/64615471-8c2f1700-d3d2-11e9-8c13-0d032dfe99ec.png)
![image](https://user-images.githubusercontent.com/7480500/64615490-951fe880-d3d2-11e9-95b0-8a52f3cf539a.png)

If I remove the `<fa-stack>` wrapper, the icons render:
![image](https://user-images.githubusercontent.com/7480500/64615568-b4b71100-d3d2-11e9-826f-6c22f79b95e2.png)
![image](https://user-images.githubusercontent.com/7480500/64615590-c1d40000-d3d2-11e9-944d-df1d61f9b375.png)

My implementation as I understand it is completely in-line with [the documentation provided](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/features.md#stacked-icons), so is this a bug or am I doing something wrong?

I'm running on Angular 8.2.3.
Font Awesome versions:
![image](https://user-images.githubusercontent.com/7480500/64615751-0fe90380-d3d3-11e9-868b-ac9792853d42.png)

**Comment by devoto13** [comment]
Please check [docs](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/features.md#stacked-icons) for the correct usage. `stackItemSize` property is required.

Somehow I've [expected](https://github.com/FortAwesome/angular-fontawesome/blob/master/src/lib/stack/stack.component.ts#L6) this issue to come up... Let's keep this issue open to implement a check for missing `stackItemSize` directive.

**Comment by plinkpaste** [comment]
@devoto13 Ah. That's not so obvious from the documentation, I would have assumed default to have been '1x'. 

Either an error if it's missing or a default of '1x' would be useful, rather than rendering nothing.

**Comment by devoto13** [comment]
@plinkpaste Sorry about that. Can you submit a PR to mention in the documentation that the `stackItemSize` property is required? This will be useful until we implement the actual error checking.

PS Unfortunately we can't make this a default, because it is a separate [directive](https://github.com/FortAwesome/angular-fontawesome/blob/master/src/lib/stack/stack-item-size.directive.ts), which adds extra logic for the icon component and therefore needs to be added explicitly.

**Comment by plinkpaste** [comment]
@devoto13 Sure, I can do that.
