### ISSUE TITLE
fa-icon prefix doesn't seem to work

### ISSUE THREAD

**Issue by plinkpaste** [FortAwesome/angular-fontawesome#178]
### Describe the problem

Defining an icon with a prefix doesn't change the prefix.
```
<fa-icon prefix="far" icon="ban"></fa-icon>
```
![image](https://user-images.githubusercontent.com/7480500/64616444-7fabbe00-d3d4-11e9-8402-9b1ec84775ca.png)

### What did you expect?

I expect changing the prefix value to actually change the prefix. As you can see, with a prefix value of 'far', the icon is been looked for in 'fas'.

### Reproducible test case

[StackBlitz example](https://stackblitz.com/edit/angular-z8v4ux-k1ygli)

**Comment by devoto13** [comment]
There is no `prefix` input on the `fa-icon` component. Use `<fa-icon [icon]="['far', 'ban']"></fa-icon>` to pass a custom prefix. This proposal was discussed in https://github.com/FortAwesome/angular-fontawesome/issues/10 and rejected.

**Comment by plinkpaste** [comment]
Thanks, I wasn't aware that `prefix` wasn't a font-awesome input!
