### ISSUE TITLE
'fa-stack' is not a known element - Angular 7

### ISSUE THREAD

**Issue by kirstenfrager** [FortAwesome/angular-fontawesome#183]
### Describe the problem

When using any of font-awesomes additional features, error is thrown.

In this example, using <fa-stack> selector in html throws error:
```
Uncaught Error: Template parse errors:
'fa-stack' is not a known element:
1. If 'fa-stack' is an Angular component, then verify that it is part of this module.
```

### What did you expect?

To be able to use all the additional features with their component selectors.

### Setup 

**ADDITIONAL INFO:**
 I am using font awesome pro
Using regular <fa-icon> selector tag works fine

Setup:
Angular CLI: 7.3.8
Node: 11.2.0
OS: darwin x64
Angular: 7.2.15

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/material                 7.3.7
@angular/pwa                      0.13.9
@ngtools/webpack                  7.3.9
@schematics/angular               8.0.1
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.29.0

app.module.ts:
```
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    FontAwesomeModule
  ],
  providers: [],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule { }

```

package.json includes these packages:
```
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.22",
    "@fortawesome/free-brands-svg-icons": "^5.10.2",
    "@fortawesome/free-solid-svg-icons": "^5.10.2",
    "@fortawesome/pro-light-svg-icons": "^5.10.2",
    "@fortawesome/pro-regular-svg-icons": "^5.10.2",
    "@fortawesome/pro-solid-svg-icons": "^5.10.2",
```

page.html:
```
    <fa-stack>
      <fa-icon [icon]="faEye" stackItemSize="2x"></fa-icon>
      <fa-icon [icon]="faEye" [inverse]="true" stackItemSize="1x"></fa-icon>
    </fa-stack>
```

page.ts:

```
import { faListAlt } from '@fortawesome/pro-regular-svg-icons'
import { faEye } from '@fortawesome/pro-solid-svg-icons'

export class DisclaimersPage implements OnInit {

  faEye = faEye;
  faListAlt = faListAlt;

  constructor(
  ) { }
}
```

**Comment by devoto13** [comment]
@kirstenfrager `fa-stack` component was introduced in version [0.5.0](https://github.com/FortAwesome/angular-fontawesome/releases/tag/0.5.0), while you use the older version - 0.3.0. Bad news is that you'll have to upgrade Angular to be able to use the newer features... See [Compatibility table](https://github.com/FortAwesome/angular-fontawesome#compatiblity-table).

This is also related to https://github.com/FortAwesome/angular-fontawesome/issues/119.

**Comment by kirstenfrager** [comment]
@devoto13 damn, that is bad news. Thanks for your quick response.
