### ISSUE TITLE
Outdated documentation on how to add icons to the library

### ISSUE THREAD

**Issue by devoto13** [FortAwesome/angular-fontawesome#186]
### Describe the problem

Outdated documentation using `library.add()` (e.g. [here](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/using-other-styles.md#brand-icons)).

### What did you expect?

Up to date documentation using `FaIconLibrary.addIcons()` and `FaIconLibrary.addPacks()`.

Need to search documentation for usages of `library.add()` and update samples to show usage of `FaIconLibrary`.

**Comment by YuriMB** [comment]
Please also add some explanation on how to use this in karma unit tests. Previously the library was global and could be used to register the icons in karma tests, but that no longer works.

**Comment by devoto13** [comment]
@YuriMB Can you please shortly describe your use case? `FaIconLibrary` is a regular Angular service, so you can inject it in the tests using [`TestBed.get(FaIconLibrary)`](https://angular.io/api/core/testing/TestBed#get) or [`inject`](https://angular.io/api/core/testing/inject):

```
beforeEach(inject([FaIconLibrary], (library) => {
  library.addIcons(...);
}));
```

If you're after configuring `FaIconLibrary` once per test run, then we don't have a recommended solution at the moment. Please, fill in a new feature request to track it.

**Comment by YuriMB** [comment]
> @YuriMB Can you please shortly describe your use case? `FaIconLibrary` is a regular Angular service, so you can inject it in the tests using [`TestBed.get(FaIconLibrary)`](https://angular.io/api/core/testing/TestBed#get) or [`inject`](https://angular.io/api/core/testing/inject):
> 
> ```
> beforeEach(inject([FaIconLibrary], (library) => {
>   library.addIcons(...);
> }));
> ```
> 
> If you're after configuring `FaIconLibrary` once per test run, then we don't have a recommended solution at the moment. Please, fill in a new feature request to track it.

if you want to use the `inject` method, then you need a separate beforeEach block, because you can't inject before calling `configureModule`. The `TestBed.get(FaIconLibrary)` option however works like a charm!

I've had some additional issues that were actually caused by other problems after migrating from Angular 7 to Angular 8. Thanks for the quick reply!
