### ISSUE TITLE
Icon can be formatted as Link

### ISSUE THREAD

**Issue by apijay** [FortAwesome/angular-fontawesome#187]
There is use case when an action is performed on clicking on icon e.g: close icon, it would nice to hover effect on icon for this case.

https://semantic-ui.com/elements/icon.html#link

**Comment by devoto13** [comment]
It's rather straight-forward to implement it and consumers may want behavior to look different depending on their design, so not sure how valuable is it to have a built-in support. Let's gather more feedback on this feature request.

https://stackblitz.com/edit/angular-z8v4ux-gbzehx?file=src%2Fapp%2Fapp.component.css

**Comment by devoto13** [comment]
I'm going to close this feature request as rejected as it hasn't received any traction in almost 2 years. It's relatively easy to implement the icon hover effect in the application, so it's probably better to do it that way.
