### ISSUE TITLE
Licence is not included on package download.

### ISSUE THREAD

**Issue by sergio8016** [FortAwesome/angular-fontawesome#188]
### Describe the problem

Currently the MIT licence is not comming on the downloaded files before run the command npm i @fortawesome/angular-fontawesome

### What did you expect?

This licence file should be added for audit reasons.

**Comment by devoto13** [comment]
The license is specified in the `license` field of the [`package.json`](https://github.com/FortAwesome/angular-fontawesome/blob/master/package.json#L41). But if you need the actual file to be present in the downloaded package, please, send a PR.
