### ISSUE TITLE
How to handle no icon at all?

### ISSUE THREAD

**Issue by Guy--L** [FortAwesome/angular-fontawesome#189]
### Describe the problem

I see errors "FontAwesome: Could not find icon. It looks like you've provided a null or undefined icon object to this component."

From this markup:
`            <fa-icon [icon]="element.icon()" [ngClass]="element.style()"></fa-icon>
`
Where this component provides this function:
`    icon = (where: place) => {
        switch (this.Status[where]) {
            case "Town":              return faCheckSquare;
            case "County":           return faCopyright;
            case "State":              return faExclamationTriangle;
            case "Country":        return faExclamationCircle;
            default:                   return null;
        }
    }
`
How do I return something other than null to prevent error in debug?

**Comment by devoto13** [comment]
@Guy--L See this comment for two possible solutions: https://github.com/FortAwesome/angular-fontawesome/issues/50#issuecomment-519890025.

**Comment by devoto13** [comment]
Closing as answered. 

Please comment if it is still a problem.
