### ISSUE TITLE
how to know what name icon import?

### ISSUE THREAD

**Issue by leonardopaiva** [FortAwesome/angular-fontawesome#193]
hello, i am trying to use https://fontawesome.com/icons/cc-visa?style=brands how can i know what name import on my component to use it?

example, for coffe icon:
import { faCoffee } from '@fortawesome/free-solid-svg-icons';

for visa credit card icon, how can i know the name?
something like that?
import { faCCVisa } from '@fortawesome/free-solid-svg-icons';

**Comment by devoto13** [comment]
This icon is from the ‘brands’ style, so you can find it in another package: https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/using-other-styles.md#brand-icons

I usually rely on the auto completion in the editor to get the list of all icons in the package. But yes, it should be something similar to what you guessed, only imported from another package.

**Comment by devoto13** [comment]
@leonardopaiva Thanks for a detailed description of the approach! I'll use it as a reference it if similar question arises again in the future.

In the meantime I'll close this issue as the original problem seems to be resolved now.
