### ISSUE TITLE
Storybook Integration

### ISSUE THREAD

**Issue by christiancueto** [FortAwesome/angular-fontawesome#195]
**Question**
Now that the global icon library has been [deprecated](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/upgrading/0.4.0-0.5.0.md#migrate-from-global-icon-library-to-faiconlibrary) in 0.5.0, is there a recommended way as to how to set up an icon library in storybook?

Storybook stories have no module/Angular constructor.

I was previously doing something like this in my `.storybook/config.js` file:
```js
import { library } from '@fortawesome/fontawesome-svg-core';
import { IMPORTED_ICONS } from '@app/icons';

library.add(...IMPORTED_ICONS);
```

**Related Issue**
https://github.com/storybookjs/storybook/issues/8349

**Comment by devoto13** [comment]
I'm not very familiar with the storybook, so can't say about the *recommended* way, but I've described one working approach in [this SO answer](https://stackoverflow.com/a/58672268/1377864). Let me know if solves your problem.

**Comment by devoto13** [comment]
Contributions are welcome to add [a guide](https://github.com/FortAwesome/angular-fontawesome/tree/master/docs/guide) in the documentation, which will explain how to use `angular-fontawesome` with Storybook.
