### ISSUE TITLE
Error: inject() must be called from an injection context (v9-rc0)

### ISSUE THREAD

**Issue by frct1** [FortAwesome/angular-fontawesome#199]
### Describe the problem
In angular 9 rc0 fa-layers-counter calling error
`ERROR Error: inject() must be called from an injection context`

After migration from v8

### What did you expect?
Usual rendering layers-counter with classes

### Reproducible test case
As i know stakcblitz not supported angular 9 
Simply use code below
```html
<fa-layers>
    <fa-icon size="lg" [icon]="['fas', 'server']"></fa-icon>
    <fa-layers-counter content="{{(counters$ | async).option}}" [classes]="['fa-custom-counter']"> 
    </fa-layers-counter>
 </fa-layers>
```

**Comment by devoto13** [comment]
Looks like a duplicate of https://github.com/FortAwesome/angular-fontawesome/issues/154, which has been fixed already. I'll try to cut a pre-release with Angular 9 support this weekend.

**Comment by frct1** [comment]
Yes, i've saw that
Also update from 0.4 to 0.5 didn't help

**Comment by devoto13** [comment]
This is expected. There is no release, which contains the fix yet. I'll post back once it is released.

**Comment by frct1** [comment]
Thank you
Will disable it temporarily

**Comment by devoto13** [comment]
https://github.com/FortAwesome/angular-fontawesome/releases/tag/0.6.0-alpha.0 is now available, which has Angular 9 support. Please give it a try and report back if you experience any issues.

**Comment by frct1** [comment]
Hi @devoto13 
Tested it, now errors doesn't throwing. Works like a charm 👍 
Thank you for fix and have a good day :)
