### ISSUE TITLE
Feature Request: Upgrading 0.5.0 to 0.6.0 Guide

### ISSUE THREAD

**Issue by sagunpandey** [FortAwesome/angular-fontawesome#207]
### Describe the problem you'd like to see solved or task you'd like to see made easier

Upgrading 0.5.0 to 0.6.0 guide incomplete.

`this.icon$ = this.loadIcon().pipe(startsWith(defaultIcon));`

What is `this.loadIcon()` ?

### Is this in relation to an existing part of angular-fontawesome or something new?

Existing Part

### Why would other angular-fontawesome users care about this?

Everybody needs to the point documentation.

### Feature request checklist

- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment]
It is a function, which loads the icon asynchronously. It is specific for each application, that is why it is not specified in the upgrade guide.

PRs are welcome to clarify this and/or expand the example code.
