### ISSUE TITLE
Cannot bind 'icon' since it isn't a known property of 'fa-icon'

### ISSUE THREAD

**Issue by kuehlc** [FortAwesome/angular-fontawesome#211]
I am explicitly using angular fontawesome 0.6.0, and it seems to not be working for a component that I have. It works in another one that is declared in the app module, but not a component that is in a module that was imported to app module. I may just be crazy and missing something simple, but it looks almost the same, and I don't see why it isn't working.
![viewercomponent](https://user-images.githubusercontent.com/22896763/70270895-eab62800-176a-11ea-89ff-e7e264d69265.PNG)
![appmodule](https://user-images.githubusercontent.com/22896763/70270906-f0ac0900-176a-11ea-84ef-f9de2b4b1714.PNG)
![viewermodule](https://user-images.githubusercontent.com/22896763/70270937-ff92bb80-176a-11ea-972a-35d9f7864182.PNG)
![headercomponent](https://user-images.githubusercontent.com/22896763/70270951-09b4ba00-176b-11ea-90c2-741ef7810148.PNG)
![sharedmodule](https://user-images.githubusercontent.com/22896763/70270964-0faa9b00-176b-11ea-9a14-2c60c62d3659.PNG)
![viewerhtml](https://user-images.githubusercontent.com/22896763/70270973-176a3f80-176b-11ea-9284-6ed00d1c0b59.PNG)
![headerhtml](https://user-images.githubusercontent.com/22896763/70270988-1d602080-176b-11ea-8c15-ab9b7e3debc5.PNG)

**Comment by kuehlc** [comment]
I works in the header, but not in viewer if that wasn't clear from the initial post.

**Comment by devoto13** [comment]
You need to add FontAwesomeModule to imports array of the module where your component is present in the declarations array for Angular to know about fa-icon component.

**Comment by kuehlc** [comment]
I have Fontawesome in shared module which is in viewer as well though

**Comment by kuehlc** [comment]
Viewer component is in viewer module which has SharedModule imported

**Comment by kuehlc** [comment]
Exporting it from sharedmodule made it work.
