### ISSUE TITLE
Feature request: fixed-width by default

### ISSUE THREAD

**Issue by mrvonwyl** [FortAwesome/angular-fontawesome#216]
### Describe the problem you'd like to see solved or task you'd like to see made easier

It would be nice to have all icons being fixed-width by default to achieve better layouts in certain scenarios. As far as I know this is currently not possible.

### Is this in relation to an existing part of angular-fontawesome or something new?

FontAwesomeModule

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?

Provide configuration options for the FontAwesomeModule. Maybe by implementing a .forRoot() method, which receives a configuration. This could also include default icon style, so that it could be omitted in <fa-icon>.

### Why would other angular-fontawesome users care about this?

I believe this would make the work of other layout designers/programmers easier.

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

6

**Comment by devoto13** [comment]
In fact we already allow to configure default prefix using [`FaConfig`](https://github.com/FortAwesome/angular-fontawesome/blob/134d82e4c27e7ab2f0f852eb5e0fd2dab92a5875/src/lib/config.ts). See [documentation](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/icon-library.md#changing-the-default-prefix).

PRs are welcome to add a `FaConfig.fixedWidth` property to specify default value for [`fa-icon`](https://github.com/FortAwesome/angular-fontawesome/blob/134d82e4c27e7ab2f0f852eb5e0fd2dab92a5875/src/lib/icon/icon.component.ts#L147) and [`fa-layers`](https://github.com/FortAwesome/angular-fontawesome/blob/134d82e4c27e7ab2f0f852eb5e0fd2dab92a5875/src/lib/layers/layers.component.ts#L24) components.

**Comment by mrvonwyl** [comment]
Thank you for the hint for the default prefix!

I would be glad to implement that. However I am facing a problem with the imports of `@fortawesome/angular-fontawesome` within the demo project:

```
ERROR in projects/demo/src/app/alternate-prefix.component.ts:2:41 - error TS2307: Cannot find module '@fortawesome/angular-fontawesome'.

2 import { FaConfig, FaIconLibrary } from '@fortawesome/angular-fontawesome';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
projects/demo/src/app/app.component.ts:2:41 - error TS2307: Cannot find module '@fortawesome/angular-fontawesome'.

2 import { FaConfig, FaIconLibrary } from '@fortawesome/angular-fontawesome';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
projects/demo/src/app/app.module.ts:3:35 - error TS2307: Cannot find module '@fortawesome/angular-fontawesome'.

3 import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
```

Could you provide me a solution on how to resolve these failing imports. I am new to working with angular workspaces/sub-projects. Thank you!

**Comment by devoto13** [comment]
`demo` app is configured to use distribution of the library, so you need to run `yarn build` to produce the library build first.

However with the recent Angular changes this is not very convenient as you have to manually re-run `yarn start` after every change to the library code... To get better experience you can replace `paths` section in the root `tsconfig.json` with:

```
    "paths": {
      "@fortawesome/angular-fontawesome": ["src/lib/public_api.ts"],
      "@fortawesome/angular-fontawesome/testing": ["testing/src/public_api.ts"]
    }
```

during development. Then you only need `yarn start` and changes will be picked up as expected.

Let me know if you need any further help with this.
