### ISSUE TITLE
addIconPacks not work with fab

### ISSUE THREAD

**Issue by calidion** [FortAwesome/angular-fontawesome#217]
### Describe the problem

```
import {
  fab
} from "@fortawesome/free-brands-svg-icons";

import {
  fas
} from "@fortawesome/free-solid-svg-icons";

```

```
  constructor(
    library: FaIconLibrary
  ) {
    library.addIconPacks(fas, fab);
  }
```
it works for fas, but not fab.

**Comment by devoto13** [comment]
It is not clear what do you mean by "does not work". Please provide an error message you get and version of all `@fortawesome/*` packages you use.

May be related to https://github.com/FortAwesome/angular-fontawesome/issues/125.

**Comment by calidion** [comment]
There is no error message, just not showing the icons.

package versions are:
```
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.17",
    "@fortawesome/free-brands-svg-icons": "^5.8.1",
    "@fortawesome/free-solid-svg-icons": "^5.8.1",
```

**Comment by devoto13** [comment]
It's hard to say what problem is without an error message. Please provide a minimal reproduction on StackBlitz. You can use https://stackblitz.com/edit/angular-z8v4ux as a started template.

**Comment by calidion** [comment]
@devoto13 

Thanks.

solved:  https://stackblitz.com/edit/angular-z8v4ux-y4vxrb
