### ISSUE TITLE
font awesome icon in pseudo element

### ISSUE THREAD

**Issue by vivongithub** [FortAwesome/angular-fontawesome#221]
Is it possible to show a fontawesome icon within css pseudo elements in angular apps that imports fontawesome through @angular-fontawesome?
Example:
<div class="header">My title</div>

in css file: 
.header:before {
  font-family: "Font Awesome 5 Free";
  font-weight: 900;
  content: "\f04e";
  margin-right: 0.2rem;
}
Only shows an empty square.

I can get it working with the following code:
<fa-icon  icon="forward"></fa-icon>My title

Any help would be greatly appreciated. Thanks

**Comment by devoto13** [comment]
No, this way of rendering icons with CSS is not possible with `angular-fontawesome`. Please check https://github.com/FortAwesome/angular-fontawesome/issues/159, maybe your actual problem may be solved without using this approach. Also you may be interested in [programmatic API](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/features.md#programmatic-api) to render icons dynamically.

**Comment by vivongithub** [comment]
It makes sense. Thanks
