### ISSUE TITLE
Question: Is there any way to change the spin or pulse speed?

### ISSUE THREAD

**Issue by TaiyouFTW** [FortAwesome/angular-fontawesome#222]
Hello. Is there any way to change the spin or pulse speed?

In my code i use this basic example only with 1 class to change the color.
<fa-icon [icon]="['fas', 'spinner']" [spin]="true"></fa-icon>

**Comment by devoto13** [comment]
No, there is no official support for this. But it is possible to assign arbitrary CSS animation to the icon by using `classes` or `styles` inputs.

It should even be possible to re-use FA CSS animation and only change its time using this approach. See [an example](https://stackblitz.com/edit/angular-z8v4ux-dtnpga). Note that re-using FA animation is not officially supported and may break without notice in the future release of Font Awesome library.

**Comment by TaiyouFTW** [comment]
Thank you for the help.
