### ISSUE TITLE
using the PRO icons 

### ISSUE THREAD

**Issue by saffabook** [FortAwesome/angular-fontawesome#234]
### Describe the problem

I have done the installation and everything works as expected, however, I cannot get the Pro to work as well. 

I followed this guide https://github.com/FortAwesome/angular-fontawesome

My pro folder looks like this though. 

![image](https://user-images.githubusercontent.com/6928921/76523293-d8860d00-6470-11ea-8125-fb7e525e34c3.png)

As you can see, I have the pro-solid folder, but no ref to the acorn icon. 

I have also tried a new ng add @fortawesome/angular-fontawesome@0.6.x

And end up with this screen. 
![image](https://user-images.githubusercontent.com/6928921/76523588-53e7be80-6471-11ea-9f3a-6ebc5a80a833.png)

Why would this be?

**Comment by devoto13** [comment]
You have installed the [old and deprecated icon package](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/upgrading/0.1.0-0.1.0-6.md#renamed-packages). Please check [this documentation](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/using-other-styles.md) to learn how to install and use correct packages.

Note that you'll need to [configure your `.npmrc`](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro) to be able to install Pro packages.

Also you should use specific `angular-fontawesome` version, which is compatible with your Angular version. See [Compatibility table](https://github.com/FortAwesome/angular-fontawesome#compatiblity-table). This may be the reason why `ng add` fails. If you use the correct version and still experience the problem with `ng add`, please provide a minimal reproduction and I'll investigate it further.

**Comment by saffabook** [comment]
Hi there, I have installed the pro now and works as you explained. Thanks for pointing that out. 

I do have angular 9 so compatibility should work with ng add @fortawesome/angular-fontawesome@0.6.x ?

Anyways, thank you for everything.

**Comment by devoto13** [comment]
Yes, `ng add` should work with Angular 9. Please provide a reproduction steps, so I can debug and fix this bug.

**Comment by nephi5** [comment]
Hi, how would you go about using the pro icons when you are behind a corporate proxy?

**Comment by devoto13** [comment]
@nephi5 It's impossible to answer your question without more details. Please open a new issue and describe step by step what you're doing and what is the error message you receive. Normally everything should just work as long as `npm.fontawesome.com` domain is not blacklisted by your proxy.

**Comment by nephi5** [comment]
Hi @devoto13 - thanks for the quick answer. Our company does not use blacklists, they white-list only a handful of domains. They won't allow a domain like `npm.fontawesome.com` to be white-listed. Currently we are manually downloading and hosting the fontawesome pro assets. Is there a way I could point to those resources?

**Comment by devoto13** [comment]
@nephi5 Well, Pro packages are only available from `npm.fontawesome.com`. If you can't access it, this means you can not install these NPM packages.

But I still don't completely understand what you're trying to do. What exactly do you mean by "point to those resources"?
