### ISSUE TITLE
Some Covid-19 Awareness Icons not working

### ISSUE THREAD

**Issue by eruecco87** [FortAwesome/angular-fontawesome#235]
### Describe the problem

There are some icons in the [set](https://fontawesome.com/changelog/latest?utm_source=ea&utm_medium=email&utm_campaign=5.13) that are throwing console errors

`ERROR Error: Could not find icon with iconName=bacteria and prefix=fas in the icon library.`

### What did you expect?

The icon should be rendered correctly & without console errors

### Reproducible test case

https://stackblitz.com/edit/angular-z8v4ux-nukrw4

I'm initializing the library in the **app.module.ts** file instead of importing each stand alone icon

**Comment by robmadole** [comment]
Hi @eruecco87 . The `bacterium` and `bacteria` are only available in Font Awesome Pro. Try `virus` instead.
