### ISSUE TITLE
Type '"bacteria"' is not assignable to type 'IconName'

### ISSUE THREAD

**Issue by Joshanity17** [FortAwesome/angular-fontawesome#236]
### Describe the problem

I am trying to add [brands](https://www.npmjs.com/package/@fortawesome/free-brands-svg-icons), but whenever I include it to `FaIconLibrary.addIcons()`, I get `Type '"bacteria"' is not assignable to type 'IconName'`

Full Error:
```
Argument of type 'import("/path/node_modules/@fortawesome/free-brands-svg-icons/node_modules/@fortawesome/fontawesome-common-types/index").IconDefinition' is not assignable to parameter of type 'import("/path/node_modules/@fortawesome/fontawesome-common-types/index").IconDefinition'.
  Types of property 'iconName' are incompatible.
    Type 'import("/path/node_modules/@fortawesome/free-brands-svg-icons/node_modules/@fortawesome/fontawesome-common-types/index").IconName' is not assignable to type 'import("/path/node_modules/@fortawesome/fontawesome-common-types/index").IconName'.
      Type '"bacteria"' is not assignable to type 'IconName'.
```

### What did you expect?

I should be fine since the brands export is `IconDefinition` type

**Comment by devoto13** [comment]
@Joshanity17 This sounds very similar to https://github.com/FortAwesome/angular-fontawesome/issues/125. Can you check whether you have duplicated `@fortawesome/fontawesome-common-types` in your lock files (https://github.com/FortAwesome/angular-fontawesome/issues/125#issuecomment-466036515)?

**Comment by Joshanity17** [comment]
> @Joshanity17 This sounds very similar to #125. Can you check whether you have duplicated `@fortawesome/fontawesome-common-types` in your lock files ([#125 (comment)](https://github.com/FortAwesome/angular-fontawesome/issues/125#issuecomment-466036515))?

This does not solve the problem, I tried to check the `package-lock.json` and there's only one `@fortawesome/fontawesome-common-types` there with version `0.2.27`

I tried to check the versions of the aforementioned package and there are no versions `1.2.27` < `1.3.0`

**Comment by Joshanity17** [comment]
> @Joshanity17 This sounds very similar to #125. Can you check whether you have duplicated `@fortawesome/fontawesome-common-types` in your lock files ([#125 (comment)](https://github.com/FortAwesome/angular-fontawesome/issues/125#issuecomment-466036515))?

This does not solve the problem, I tried to check the `package-lock.json` and there's only one `@fortawesome/fontawesome-common-types` there with version `0.2.27`

I tried to check the versions of `@fortawesome/fontawesome-svg-core` package and I am already running with `1.2.27`

**Comment by devoto13** [comment]
@Joshanity17 Then please provide the minimal code to reproduce the problem. I can't reproduce this problem unless your setup includes multiple versions of `@fortawesome/fontawesome-common-types` package. From the error message I would assume that you have both `0.2.27` and `0.2.28` installed.

**Comment by Joshanity17** [comment]
It looks like this is a bug from these versions.
```
"@fortawesome/fontawesome-svg-core": "^1.2.27"
"@fortawesome/free-solid-svg-icons": "^5.12.1"
```

When I changed the version to these
```
"@fortawesome/fontawesome-svg-core": "^1.2.28",
"@fortawesome/free-solid-svg-icons": "^5.13.0",
```

The error was gone.
