### ISSUE TITLE
Cannot read property 'kind' of undefined during ng add @fortawesome/angular-fontawesome

### ISSUE THREAD

**Issue by weitlos** [FortAwesome/angular-fontawesome#237]
Dear fontawesome team,

first of all thank you so much for this great offering! I am new to web development and really suprised about all that great content available for web developers! :)

![image](https://user-images.githubusercontent.com/19833878/77693570-da8bb800-6fa8-11ea-81a4-7fc327c0bd2a.png)

I just tried to setup fontawsome for my angular project but while running
ng add @fortawesome/angular-fontawesome for my project I run into the following issue after choosing the icon package I want to use:

"Cannot read property 'kind' of undefined".

![image](https://user-images.githubusercontent.com/19833878/77693676-04dd7580-6fa9-11ea-8b0f-04320087adeb.png)

As a result it seems that the installation is not finished properly.
This happens for all free icon packages (tried single and also multiselect).

As there is only very limited output I am not 100% sure if this is an issue caused by fontawesome or the CLI or what ever else. s:

I develop in Visual Studio Code.
I also attach here the angular version. hope that helps!

![image](https://user-images.githubusercontent.com/19833878/77693211-44579200-6fa8-11ea-9a4f-3035bec61f96.png)

Any ideas or comments would be great :)

kind regards from Berlin,
Simon

**Comment by devoto13** [comment]
Thanks for a detailed report Simon. I've seen a similar report in https://github.com/FortAwesome/angular-fontawesome/issues/234. But I'm not able to reproduce this issue on my side. And I can not fix it if I can't reproduce it.

```
$ ng new test-app
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE test-app/README.md (1024 bytes)
CREATE test-app/.editorconfig (274 bytes)
CREATE test-app/.gitignore (631 bytes)
CREATE test-app/angular.json (3582 bytes)
CREATE test-app/package.json (1284 bytes)
CREATE test-app/tsconfig.json (489 bytes)
CREATE test-app/tslint.json (3125 bytes)
CREATE test-app/browserslist (429 bytes)
CREATE test-app/karma.conf.js (1020 bytes)
CREATE test-app/tsconfig.app.json (210 bytes)
CREATE test-app/tsconfig.spec.json (270 bytes)
CREATE test-app/src/favicon.ico (948 bytes)
CREATE test-app/src/index.html (293 bytes)
CREATE test-app/src/main.ts (372 bytes)
CREATE test-app/src/polyfills.ts (2835 bytes)
CREATE test-app/src/styles.css (80 bytes)
CREATE test-app/src/test.ts (753 bytes)
CREATE test-app/src/assets/.gitkeep (0 bytes)
CREATE test-app/src/environments/environment.prod.ts (51 bytes)
CREATE test-app/src/environments/environment.ts (662 bytes)
CREATE test-app/src/app/app.module.ts (314 bytes)
CREATE test-app/src/app/app.component.css (0 bytes)
CREATE test-app/src/app/app.component.html (25723 bytes)
CREATE test-app/src/app/app.component.spec.ts (948 bytes)
CREATE test-app/src/app/app.component.ts (212 bytes)
CREATE test-app/e2e/protractor.conf.js (808 bytes)
CREATE test-app/e2e/tsconfig.json (214 bytes)
CREATE test-app/e2e/src/app.e2e-spec.ts (641 bytes)
CREATE test-app/e2e/src/app.po.ts (301 bytes)
✔ Packages installed successfully.
$ cd test-app
$ ng add @fortawesome/angular-fontawesome
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Choose Font Awesome icon packages you would like to use: Free Solid Icons
UPDATE package.json (1438 bytes)
UPDATE src/app/app.module.ts (407 bytes)
✔ Packages installed successfully.
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.1.0
Node: 13.8.0
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
```

Can you try to run the same commands (lines starting with `$`) in your Terminal and confirm that it fails on your side?

If it does not, try to identify the minimal set of commands to produce the error you have described in your initial report.

**Comment by grosem** [comment]
I can reproduce it with typescript 3.7.5 - no issues with 3.8.3

**Comment by weitlos** [comment]
Hi,

thank you for the super fast reply! It worked fine with your example. I then removed any fontawesome dependency and module manually as well as reinstalling typescript with the mentioned version 3.8.3. This fixed the issue!

Thank you all for the great help!

All the best and a great weekend for you!
Simon
