### ISSUE TITLE
Cannot find module '@fortawesome/angular-fontawesome/testing' in v0.5.0

### ISSUE THREAD

**Issue by YoanDieu** [FortAwesome/angular-fontawesome#241]
Hello there!

### Describe the problem

The version 0.5.0 seems to not export FontAwesomeTestingModule anymore. It was a few days ago, but reinstalling it now break my test since the module is missing.

### What did you expect?

To still have a FontAwesomeTestingModule exported when installing 0.5.0.

### Reproducible test case

[stackblitz](https://stackblitz.com/edit/angular-espzad)

### Step to reproduce on your machine
Create a new angular 8 project.
Follow the guideline to install angular-fontawesome 0.5.0.
Try to `import { FontAwesomeTestingModule } from '@fortawesome/angular-fontawesome/testing';
` anywhere in your default tests.
Module can not be found.

Looking a the node_module doesn't seems to be exported indeed, and i see no reference to it anywhere.
Am i missing something or is it really gone?

**Comment by devoto13** [comment]
@YoanDieu The `FontAwesomeTestingModule` has been added in [`0.6.0-alpha.0`](https://github.com/FortAwesome/angular-fontawesome/releases/tag/0.6.0-alpha.0), so it was never available in the 0.5.0. Maybe you had newer version installed earlier?

Also there is no way to change contents of the published release. It is only possible to remove it completely.

**Comment by YoanDieu** [comment]
Ok thanks. I'm a bit confuse about my setup now, but at least i learned something ! Thanks for the quick reply.
