### ISSUE TITLE
Social Icons like Facebook, Twitter, LinkedIn, Instagram

### ISSUE THREAD

**Issue by sujaywork** [FortAwesome/angular-fontawesome#242]
I don't see the social icons such as Facebook, Twitter, LinkedIn, or Instagram in the current library? What's the process to use them?

https://fontawesome.com/icons?d=gallery&q=facebook&m=free
https://fontawesome.com/icons?d=gallery&q=twitter&m=free
https://fontawesome.com/icons?d=gallery&q=linkedin&m=free
https://fontawesome.com/icons?d=gallery&q=instagram&m=free

**Comment by devoto13** [comment]
I think what you're looking for is [this documentation](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/using-other-styles.md#brand-icons) on how to install brands icon package.

**Comment by sujaywork** [comment]
Yes that was it, thanks for the tip!

import { faFacebook, faTwitter, faInstagram, faYoutube } from '@fortawesome/free-brands-svg-icons';
