### ISSUE TITLE
Angular-Fontawesome & Unicode

### ISSUE THREAD

**Issue by bhalicki** [FortAwesome/angular-fontawesome#250]
Hoping someone can tell me the procedure to use angular-fontawesome and unicode.  

Fontawesome works using traditional approach (<fa-icon class="button-icon" [icon]="['fas', 'file-upload']"></fa-icon>), but I ultimately need to use icons in a select input control, so understand I need to use unicode for this.

For example:
```
.test
{
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
}

<span class="test">&#xf2b9;</span>
```

Cannot find this referenced in the documentation at all and the above solution results in unrecognized fonts.

**Comment by devoto13** [comment]
@bhalicki `angular-fontawesome` is based on SVG with JavaScript approach, therefore it does not include fonts and does not support fonts usage.

If you want to use font icons on the Web, the best approach is probably to install [generic FontAwesome package](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers) and load a font from there. Consider opening an issue in [generic FontAwesome repo](https://github.com/FortAwesome/Font-Awesome) if you need future support with it.

**Comment by devoto13** [comment]
Closing as answered and this is not the feature we're planning to support in `angular-fontawesome`.
