### ISSUE TITLE
'@fortawesome/pro-light-svg-icons@^5.13.0' is not in the npm registry

### ISSUE THREAD

**Issue by AlexanderSesslerPorabo** [FortAwesome/angular-fontawesome#254]
### Describe the problem

I tried installing FA from npm and selected Pro Light Icons. The installation failed.

### Reproducible test case

ng add @fortawesome/angular-fontawesome@0.6.1
? Choose Font Awesome icon packages you would like to use: Pro Light Icons    [ Requires: https://fontawesome.com/pro ]
⠸ Installing packages...npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-light-svg-icons - Not found
npm ERR! 404 
npm ERR! 404  '@fortawesome/pro-light-svg-icons@^5.13.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'my-project'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by AlexanderSesslerPorabo** [comment]
For everyone who gets here, i needed to set the npm registry like this:
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

**Comment by gbrunow** [comment]
Thanks, I don't why it is so difficult to find that documentation.
