### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by ericfowler303** [FortAwesome/angular-fontawesome#256]
### Describe the problem
On the [README.md](https://github.com/FortAwesome/angular-fontawesome/blob/master/README.md#installation) file there are typos in the Installation section.

In each section they start with @fortawesome instead of @fontawesome. Notice @FORT vs @FONT.

**Comment by devoto13** [comment]
Thanks for the issue, but this is not a typo: https://www.npmjs.com/package/@fortawesome/angular-fontawesome
