### ISSUE TITLE
Release for next version? (0.6.2 ?)

### ISSUE THREAD

**Issue by Pittan** [FortAwesome/angular-fontawesome#262]
Hello!  

I'm working with a project that is using Angular 9.  
When I try to update to Angular 10, error message will shown like the issue below.  
https://github.com/FortAwesome/angular-fontawesome/issues/257  

Can we get a new release to fix the problem?  
Maybe throwing new beta release will be a good test with Angular 10.

**Comment by devoto13** [comment]
[0.7.0](https://github.com/FortAwesome/angular-fontawesome/releases/tag/0.7.0) has been published.

**Comment by Pittan** [comment]
@devoto13 Thank you!
