### ISSUE TITLE
How to use this library with a downloaded copy of FA (pro subscription)?

### ISSUE THREAD

**Issue by battika** [FortAwesome/angular-fontawesome#264]
My client's build internal system will not allow us to access the npm.fontawesome.com site for downloading FA assets. We have purchased the PRO subscription which comes with two option for downloading Font Awesome for Web or Desktop. When I download the Web version which I suppose I would need, it contains lots of JS, CSS, LESS and SVG files and it would be easy to use it the classic HTML way (fa classes) but not sure how to get them work with angular-fontawesome. I looked on the web site but could not find any relevant info there. The ["Hosting Font Awesome Yourself"](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself) document only touches on the obvious things like including FA in the index.html file and use the fa classes.

Could someone please give me a pointer how to get the downloaded assets work with this library?

Thank you in advance

**Comment by devoto13** [comment]
I don't think the downloadable assets from the website will work with the library. But you should be able to download/install the icon packages from `npm.fontawesome.com` and commit them to the repository instead of installing them if you're willing to accept this compromise.

**Comment by battika** [comment]
Thanks, it seems I managed to find a solution. Downloaded the necessary pro icon packs using the `npm pack <packagename>` command which resulted in a number of tgz files. Then, removed the .npmrc file from my repo so that it will not reach out to the npm.fontawesome.com site any longer. Finally, installed the icon packs using the `npm install <filename.tgz>` command. Once finished, also installed this library with the usual npm install command. As all free components of FA are available at registry.npmjs.org that will not cause any problem during the build process.
