### ISSUE TITLE
The latest version fails in dependency Injection only in prod mode.

### ISSUE THREAD

**Issue by shyam1992** [FortAwesome/angular-fontawesome#266]
### Describe the problem

The screen doesn't launch because of the NullInjector Error, in production mode when the modules are loaded lazily.

### What did you expect?

To work properly like older version, We downgraded it to 0.5.0 and it works.

**Comment by devoto13** [comment]
1. Please check the [compatibility matrix](https://github.com/FortAwesome/angular-fontawesome#compatiblity-table) first.
2. If you're using the supported version of Angular and 0.6.1 still fails, please create a minimal reproduction. I.e. create a new Angular CLI project, add minimal code to reproduce the problem, push it on GitHub and post a link here. Without this reproduction there is nothing we can do to resolve this issue.

**Comment by shyam1992** [comment]
@devoto13 Thanks, The compatibility table solved the confusion.
https://github.com/FortAwesome/angular-fontawesome#compatiblity-table
