### ISSUE TITLE
whether anyone knows error TS2339: can you suggest  how can solve?

### ISSUE THREAD

**Issue by Ravindrakumara** [FortAwesome/angular-fontawesome#268]
ERROR in src/app/main/movie-details/movie-details.component.html:5:24 - error TS2339: Property 'faCoffee' does not exist on type 'MovieDetailsComponent'. 
    
    5       <fa-icon [icon]="faCoffee"></fa-icon>
                             ~~~~~~~~
    
      src/app/main/movie-details/movie-details.component.ts:5:16
        5   templateUrl: './movie-details.component.html',
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component MovieDetailsComponent.

**Comment by devoto13** [comment]
Make sure you have assigned the icon to the property of the component as described in the step 2 of the [Usage](https://github.com/FortAwesome/angular-fontawesome#usage) instructions.

**Comment by devoto13** [comment]
Closing as answered.
