### ISSUE TITLE
ng-add fails if it can't find tslint

### ISSUE THREAD

**Issue by madebyjeffrey** [FortAwesome/angular-fontawesome#269]
### Describe the problem

When performaing ```ng add @fortawesome/angular-fontawesome@0.6.0``` it asked for what font icons I would like:

```
Installing packages for tooling via npm.
Installed packages for tooling via npm.
? Choose Font Awesome icon packages you would like to use: Free Solid Icons, Free Regular Icons, Free Brands Icons
UPDATE package.json (3013 bytes)
UPDATE src/app/app.module.ts (11139 bytes)
```

But afterwards failed with: ```Cannot find module 'tslint'```

### What did you expect?

It to succeed without any errors. I do not use tslint.

### Reproducible test case

Unable to produce a test case on stackblitz, requires command line.

**Comment by devoto13** [comment]
Sounds reasonable to me. Feel like submitting a PR?

The fix is to wrap [this line](https://github.com/FortAwesome/angular-fontawesome/blob/master/projects/schematics/src/ng-add/index.ts#L69) into "tslint is installed" check.

**Comment by madebyjeffrey** [comment]
I am certainly willing to do this. Is there an official method of checking for tslint is installed? Most direct way I can think of is just seeing if node_modules\.bin\tslint(.exe)? exists or checking the package_lock or the yarn equivalent.

**Comment by devoto13** [comment]
It may be a bit tricky to perform the direct check for all platforms and different package managers. I would suggest to attempt loading the module and see if it fails. Something like below:

```
try {
  require('tslint');
  return true;
} catch (err) {
  return false;
}
```

**Comment by madebyjeffrey** [comment]
That would be beautiful if it works!

**Comment by madebyjeffrey** [comment]
There might be a testing opportunity as well, but not sure if it is worth it to research it.

**Comment by devoto13** [comment]
I don't think there is an easy way to test it, so it is fine without test.
