### ISSUE TITLE
size not work in lazy load modules

### ISSUE THREAD

**Issue by nhaancs** [FortAwesome/angular-fontawesome#274]
The size property of <fa-icon> work when I tried in app component, but when I try it in a component belong to a lazy load module, it doesn't work.

Notes:
- I imported font awesome module in both app and the lazy module
- I add linkedin-in icon in both modules as well
- What I use in the template: <fa-icon [icon]="['fab', 'linkedin-in']" size="xs"></fa-icon>

**Comment by devoto13** [comment]
Seems to work fine: https://stackblitz.com/edit/angular-z8v4ux-vv3m9g?file=src%2Fapp%2Flazy.ts

Most likely the issue is in your code, but if you still believe that this is a bug, please provide a minimal reproduction, so we can reproduce and investigate it.

**Comment by nhaancs** [comment]
@devoto13 thanks for your hint. I checked my code, the reason is I set `encapsulation: ViewEncapsulation.ShadowDom` in the component. Is that intended?

Demo: https://stackblitz.com/edit/angular-z8v4ux-xb6tn5?file=src/app/lazy.ts

**Comment by devoto13** [comment]
Yeah, `angular-fontawesome` injects its styles with arbitrary JS and therefore it is on compatible with `ShadowDom`. Please subscribe to https://github.com/FortAwesome/angular-fontawesome/issues/96 to track updates in this area.
