### ISSUE TITLE
icon not shown!

### ISSUE THREAD

**Issue by calidion** [FortAwesome/angular-fontawesome#275]
### Describe the problem

icon not shown!

error info: 

```
'fa-icon' is not a known element:
1. If 'fa-icon' is an Angular component, then verify that it is part of this module.
2. If 'fa-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```
### What did you expect?
icon shown.

**Comment by devoto13** [comment]
It's a standard Angular error. As a starting point please make sure that you have added `FontAwesomeModule` to `imports` of the module where the component you want to add fa-icon to is declared.

See [here](https://indepth.dev/avoiding-common-confusions-with-modules-in-angular/#module-encapsulation) for more details.

**Comment by calidion** [comment]
@devoto13 

It is added.

You can check it [here](https://github.com/calidion/trojan-desktop)

**Comment by calidion** [comment]
added in (app.module.ts)[https://github.com/calidion/trojan-desktop/blob/master/src/app/app.module.ts]

**Comment by devoto13** [comment]
You seem to have a weird structure. You declare `HomeComponent` as part of the `AppModule`, but you render it as part of a lazy-loaded `HomeModule`. This is most likely what is causing this issue. I think `HomeComponent` should be declared in the `HomeModule` and `FontAwesomeModule` should be imported there as well.

**Comment by devoto13** [comment]
> `imports` of the module where the component you want to add fa-icon to is declared.

`HomeComponent` is declared in the `HomeModule`, not `AppModule`: https://github.com/calidion/trojan-desktop/blob/master/src/app/home/home.module.ts#L10
