### ISSUE TITLE
Feature request:  Angular Fontawesome for Angular 11

### ISSUE THREAD

**Issue by NBprojekt** [FortAwesome/angular-fontawesome#280]
### Describe the problem you'd like to see solved or task you'd like to see made easier
When looking on the [compatibility table](https://github.com/FortAwesome/angular-fontawesome#compatibility-table) im missing angular 11.

Will there be a new version for Angular 11 or should I use `@fortawesome/angular-fontawesome@0.7.x` ?

### Feature request checklist

- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment]
Support is already merged - https://github.com/FortAwesome/angular-fontawesome/pull/277. I'll cut a new release later today/tomorrow. You can keep using 0.7.x until then if it works with Angular 11.

**Comment by devoto13** [comment]
[0.8.0](https://github.com/FortAwesome/angular-fontawesome/releases/tag/0.8.0) with Angular 11 support has been published.
