### ISSUE TITLE
Unable to add version 0.8.1 to Angular 11.x.x project or stackblitz

### ISSUE THREAD

**Issue by ovesyan19** [FortAwesome/angular-fontawesome#287]
Hi! Tried to update Angular 10 to 11 version, but it's failed cause of angular-fortawesome 0.8.1. Also I can't add the same version of fort awesome to Stackblitz blank project if there is installed Angular 11
Please help

**Comment by devoto13** [comment]
Unfortunately with the provided information we can't help you to solve the problem. 

If you believe there is a bug in angular-fontawesome, please provided a minimal project, clear steps to reproduce the error and the error itself. Good starting point is to generate a fresh Angular project, add minimal code to reproduce the problem you experience, push this project to GitHub and add a link here.

**Comment by devoto13** [comment]
Closing as not reproducible, but happy to re-open if requested details are provided.
