### ISSUE TITLE
feature request: import @font-face{eot+woff2+ woff + ttf +svg} only specified types not all for smaller package.

### ISSUE THREAD

**Issue by specchiasoft** [FortAwesome/angular-fontawesome#288]
Please I would like to make a request for a selective import of fonts types in the css.

I have font-awesome-pro in a multi-project angular app, font awesome is imported in angular.json under "styles": ["node_modules/@fortawesome/fontawesome-pro/css/all.min.css,] .

The application angular is composed from 6 sub-projects all in one .

**The problem**: When I build the application, angular copies  **all fonts of all types**  from node_modules\@fortawesome \ fontawesome-pro \ webfonts to project site root one for each project.  The webfont folder is 15 MB multiplied by 6 projects **90 MB** of fonts! is too  much!

Is an enterprise application and everyone uses chrome not other browsers. I use the Lato font in ttf format I would like to be able to import from font-awesome only ttf (or little else woff for cover all browsers ) not all types especially not the svg that each make 2.5 mb.

This is possible by copying and customizing the @fortawesome/fontawesome-pro/css/all.css and remove the @font-face not used,  
but if in fortawesome package npm you can add some **css import selectively** types ttf  or ttf + some examples:
@fortawesome/fontawesome-pro/css/all.ttf.css 
@fortawesome/fontawesome-pro/css/all.woff.css 
or 
@fortawesome/fontawesome-pro/css/all.woff.ttf.css 
etc.. 

Thanks for reading Regards. 

ps. this is screenshot of my application : total size 163 mb ,  90 mb the size of font awesome.
![image](https://user-images.githubusercontent.com/25741411/104489220-aa60e480-55cf-11eb-9c83-985f80b1e88e.png)

**Comment by robmadole** [comment]
Hi @specchiasoft. As a Pro subscriber you might take a look at our Desktop Subsetter. It would allow you to select just the icons that you are using and reduce the bundle size.

You can find this on https://fontawesome.com/download (if you have beta features enabled)

**Comment by robmadole** [comment]
Closing as this is not specific to the angular-fontawesome project. @specchiasoft feel free to send us an email to hello@fontawesome.com as well.
