### ISSUE TITLE
0.8.1 Circular dependencies

### ISSUE THREAD

**Issue by pauldaustin** [FortAwesome/angular-fontawesome#289]
### Describe the problem

On update to 0.8.1 the following circular dependencies show up:

Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/config.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/config.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/config.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/icon-library.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/icon-library.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/icon-library.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/stack/stack-item-size.directive.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/stack/stack-item-size.directive.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/stack/stack-item-size.directive.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/stack/stack.component.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/stack/stack.component.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/stack/stack.component.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/icon/icon.component.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/icon/icon.component.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/icon/icon.component.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/icon/duotone-icon.component.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/icon/duotone-icon.component.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/icon/duotone-icon.component.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/layers/layers.component.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/layers/layers.component.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/layers/layers.component.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/layers/layers-counter.component.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/layers/layers-counter.component.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/layers/layers-counter.component.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/layers/layers-text.component.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/layers/layers-text.component.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/layers/layers-text.component.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/fontawesome.module.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/fontawesome.module.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/fontawesome.module.d.ts.map
Warning: Unable to fully load /app/node_modules/@fortawesome/angular-fontawesome/angular-fontawesome.d.ts for source-map flattening: Circular source file mapping dependency: /app/node_modules/@fortawesome/angular-fontawesome/angular-fontawesome.d.ts.map -> /app/node_modules/@fortawesome/angular-fontawesome/angular-fontawesome.d.ts.map

Node: 15.6.0
Angular: 11.1.0

**Comment by devoto13** [comment]
AFAIR there is an issue in Angular, which leads to this error if you have leftover cache in the `node_modules` after the upgrade: https://github.com/angular/angular/issues/38001#issuecomment-656761729. I would suggest to remove `node_modules` and try again.

Consider also archiving your project with `node_modules` folder before that and sharing it with Angular team in case they wish to debug and maybe fix this problem.

**Comment by devoto13** [comment]
I hope you have been able to solve your problem by now.

Closing as it is not a bug in `angular-fontawesome`.
