### ISSUE TITLE
Some basic Icons are missing in the library

### ISSUE THREAD

**Issue by ambujkhanna** [FortAwesome/angular-fontawesome#298]
Hi,

I am using this library but unable to find following icons
- Windows OS (https://fontawesome.com/icons/windows?style=brands)
- Android OS (https://fontawesome.com/icons/android?style=brands)
- Apple OS (https://fontawesome.com/icons/apple?style=brands)

I wanted to use these icon in my project. Is there any way to get these icons?

**Comment by devoto13** [comment]
Please make sure that you have the latest version of the corresponding icons package installed (https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/using-other-styles.md#brand-icons) and that you have imported and added the icons to the library (https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/icon-library.md#using-the-icon-library).

If it still does not work, please provide a minimal reproduction using [StackBlitz](https://stackblitz.com/edit/angular-z8v4ux).

**Comment by ambujkhanna** [comment]
@devoto13 Is there any Demo page where we can check graphical representation for exact idea before to import in the project. How icon will be visible on screen?

**Comment by devoto13** [comment]
@ambujkhanna Sorry, I don't follow. You can check how does the icon look on the pages you have mentioned before (e.g. https://fontawesome.com/icons/windows?style=brands). If you want to use the icon, you install the corresponding icon package (https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/using-other-styles.md#brand-icons) and use it in you project (https://github.com/FortAwesome/angular-fontawesome#usage).

**Comment by ambujkhanna** [comment]
@devoto13  Thankyou for your quick help!!! 🥇
