### ISSUE TITLE
Type Definition Error

### ISSUE THREAD

**Issue by thatcort** [FortAwesome/angular-fontawesome#30]
When using the pro light icons I get the following error on the line where I add the light icon to the library:

```
angular_1  | ERROR in src/app/abcd/abcd.module.ts(14,13): error TS2345: Argument of type 'IconDefinition' is not assignable to parameter of type 'IconDefinitionOrPack'.
angular_1  |   Type 'IconDefinition' is not assignable to type 'IconPack'.
angular_1  |     Index signature is missing in type 'IconDefinition'.
```

I don't get this error using the solid icons or the free icons.

My module code has the following:

```
import {library} from '@fortawesome/fontawesome-svg-core';
// import {faArrowToBottom} from '@fortawesome/pro-solid-svg-icons'; <--- Works fine
import {faArrowToBottom} from '@fortawesome/fontawesome-pro-light';

library.add(faArrowToBottom); <--- Error is on this line
```

My template uses the icon as follows:
```
<fa-icon [icon]="['fal', 'arrow-to-bottom']"></fa-icon>
```

**Comment by devoto13** [comment]
It may be because you use '@fortawesome/fontawesome-pro-light‘ package instead of '@fortawesome/pro-light-svg-icons‘. Former is not intended to be used with the latest pre-release.

**Comment by thatcort** [comment]
Thank you, that did the trick. It would be great to update the docs. I had to dig around a lot to figure out how/where to install the pro fonts from npm. I clearly found out of date versions.

**Comment by devoto13** [comment]
@thatcort Please, point out where you have seen outdated docs, so we can fix them.

In the meantime README in this repo should contain an up to date documentation on how to install [more icons](https://github.com/FortAwesome/angular-fontawesome#add-more-styles-or-pro-icons).

**Comment by mlwilkerson** [comment]
Hi @thatcort if you were looking at docs on our main site, fontawesome.com, those haven't yet been updated for the pre-releases. This Angular component is being developed on the bleeding edge, and has often, in fact, defined that edge. So for the moment, the documentation on the main web site haven't caught up with the documents that you'll find on the latest version of the README in this repo for the Angular component.

**Comment by thatcort** [comment]
If I can find them again, I will. I can open another ticket for that if you'd like to close this one.

**Comment by mlwilkerson** [comment]
OK, thanks.
