### ISSUE TITLE
Angular 11 with IconLibrary - Icons are not showing

### ISSUE THREAD

**Issue by asamkamalesan** [FortAwesome/angular-fontawesome#303]
I followed the same steps mentioned in https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/icon-library.md#using-the-icon-library - addICons.

But the icons are not shown/rendered in the browser.

I can able to see <fa-icon> generated in DOM, but nothing after that. Its an empty <fa-icon> tag. Am I missing something ?

**Comment by devoto13** [comment]
Are there any warnings in the console? 

I just tried it and it works in the fresh Angular CLI project. If you believe that it's a bug, please add a minimal code to reproduce it to the https://stackblitz.com/edit/angular-z8v4ux / GitHub repo and share a link. Otherwise either you did something wrong or there is something off with your project setup.

```
$ ng new test-proj
$ cd test-proj
$ ng add @fortawesome/angular-fontawesome@0.8.x
? Would you like to share anonymous usage data about this project with the Angular Team at
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For more
details and how to change this setting, see https://angular.io/analytics. No
ℹ Using package manager: npm
✔ Package information loaded.
✔ Package successfully installed.
? Choose Font Awesome icon packages you would like to use: Free Solid Icons
UPDATE package.json (1364 bytes)
UPDATE src/app/app.module.ts (407 bytes)
✔ Packages installed successfully.
$ cat src/app/app.component.html
<fa-icon icon="coffee"></fa-icon>
$ cat src/app/app.module.ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';
import {
  FaIconLibrary,
  FontAwesomeModule,
} from '@fortawesome/angular-fontawesome';
import { faCoffee } from '@fortawesome/free-solid-svg-icons';

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, FontAwesomeModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {
  constructor(library: FaIconLibrary) {
    // Add an icon to the library for convenient access in other components
    library.addIcons(faCoffee);
  }
}
```

**Comment by asamkamalesan** [comment]
It worked in the below stackblitz

https://stackblitz.com/edit/angular-z8v4ux-cqyn5e?file=src%2Fapp%2Fapp.module.ts

I will check out from my app - I used Angular 11 though.

**Comment by devoto13** [comment]
Hope you were able to resolve your problem by now.
If you still experience the problem and believe that there is a bug in `angular-fontawesome`, please provide a minimal reproduction we can look at.
