### ISSUE TITLE
Error during compilation when FaIconLibrary is used in Angular App; Is FaIconLibrary compatible with Angular Ivy?

### ISSUE THREAD

**Issue by larachandra** [FortAwesome/angular-fontawesome#308]
### Describe the problem

Angular 12.0.3
"@fortawesome/angular-fontawesome": "^0.9.0",
"@fortawesome/fontawesome-svg-core": "^1.2.35",
"@fortawesome/free-solid-svg-icons": "^5.15.3"

Seeing below error during compilation when FaIconLibrary is used.

![image](https://user-images.githubusercontent.com/85049690/121003196-e24d0c00-c7aa-11eb-8829-e14d008702f7.png)

### What did you expect?

Expected this to be compatible with Angular 12 as described in the documentation.

**Comment by devoto13** [comment]
It is. We have tests, which verify it. 

Most like something is wrong with your setup. I would suggest beginning with removing `node_modules` and re-installing everything. If it does not help, make sure that `angular-fontawesome` is processed by `ngcc` (there should be `Compiling @fortawesome/angular-fontawesome : es2015 as esm2015` in the `ng build` output). If you still can't resolve it, please create a minimal reproduction and share it, so we can point out an error: generated new project with `ng new`, add minimal code to demonstrate the problem, push it to GitHub repository and share a link here.

**Comment by devoto13** [comment]
Hope you were able to resolve your problem by now.
If you still experience the problem and believe that there is a bug in `angular-fontawesome`, please provide a minimal reproduction we can look at.
