### ISSUE TITLE
Feature request: Add input to set position of fa-layers-counter (fa-layers-bottom-left, etc)

### ISSUE THREAD

**Issue by nelson6e65** [FortAwesome/angular-fontawesome#309]
### Describe the problem you'd like to see solved or task you'd like to see made easier

There is an option to set the position of counter by using `fa-layers-bottom-left`, `fa-layers-bottom-right`, `fa-layers-top-left` and `fa-layers-top-right` (https://fontawesome.com/v5.15/how-to-use/on-the-web/styling/layering) but I did not found it documented in this lib.

### Is this in relation to an existing part of angular-fontawesome or something new?

Missing prop of `fa-layers-counter`.

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?

Add an input for position

### Why would other angular-fontawesome users care about this?

Set position of counter.

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

9.6

### Feature request checklist

- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by nelson6e65** [comment]
I was able to use `[classes]="['fa-layers-bottom-left']"`, but should be nice to have an input.

**Comment by devoto13** [comment]
If you feel like it, please send a PR 😄

You can find some information on how to modify the library in our [developer documentation](https://github.com/FortAwesome/angular-fontawesome/blob/master/DEVELOPER.md).

**Comment by nelson6e65** [comment]
I'll try this weekend. 😃

**Comment by NayeBeckham** [comment]
Hello, I would like to contribute. Can I create a PR to solve the issue? Thank you!

**Comment by devoto13** [comment]
@NayeBeckham PR is more than welcome :)

You would need to do something similar to `size` input of [`FaLayersComponent`](https://github.com/FortAwesome/angular-fontawesome/blob/master/src/lib/layers/layers.component.ts ) and implement a corresponding test case similar to [this test](https://github.com/FortAwesome/angular-fontawesome/blob/824f040f951eee9dc65befd51113cca986f78b67/src/lib/layers/layers.component.spec.ts#L31). Please refer to the [developer documentation](https://github.com/FortAwesome/angular-fontawesome/blob/master/DEVELOPER.md) to get started.
