### ISSUE TITLE
peer rxjs@"^6.5.3" from @angular/core@12.1.3

### ISSUE THREAD

**Issue by chestongo** [FortAwesome/angular-fontawesome#313]
**Can't download angular-fontawesome with rxjs 7.2.0.**

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: 
npm ERR! Found: rxjs@7.2.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"^7.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.5.3" from @angular/core@12.1.3
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.1.3" from the root project
npm ERR!   peer @angular/core@"^12.0.0" from @fortawesome/angular-fontawesome@0.9.0
npm ERR!   node_modules/@fortawesome/angular-fontawesome
npm ERR!     @fortawesome/angular-fontawesome@"0.9.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by devoto13** [comment]
I don't think it is related to the `angular-fontawesome` in any way. It looks like you have installed `rxjs` 7.2.0, which is not supported by Angular 12 as indicated by the peer dependency error message. You should downgrade `rxjs` to the compatible version (`^6.5.3`) or (if you know what you're doing) suppress the error with flags as suggested by the error message.
