### ISSUE TITLE
Duplicated identifier

### ISSUE THREAD

**Issue by viniciosyals** [FortAwesome/angular-fontawesome#32]
I need to use two types of copyright icon, regular and solid

In documentation both have the same name
![Documentation](https://i.imgur.com/1Wu4lVU.png)

In code too... This is causing an error in typescript linter
![In code](https://i.imgur.com/yI3Z7Fe.png)

Both exists in respectives packages

**Comment by robmadole** [comment]
Try:

```
import { faCopyright as farCopyright } from '@fortawesome/free-regular-svg-icons'
```

**Comment by viniciosyals** [comment]
```js
import { faCopyright as farCopyright } ...
```
I know this is possible @robmadole, but this is the correct way? This is my question... Basicaly.

**Comment by robmadole** [comment]
@viniciosyals this is the ES6 way to handle situations just like this. So yes, it's the _right_ way ;)
