### ISSUE TITLE
There are 2 faStar's because of that I can not use them both in 1 component

### ISSUE THREAD

**Issue by Maxim-lejaeghere** [FortAwesome/angular-fontawesome#321]
### Describe the problem

I am getting an error message if I want to import both faStar's in 1 component

### What did you expect?

I was expecting to be able to use both this icons in on component (different name for different icon)

### Reproducible test case

https://stackblitz.com/edit/angular-z8v4ux-zdntlw?file=src%2Fapp%2Fapp.component.ts

![image](https://user-images.githubusercontent.com/61750005/128036928-eceae59a-a287-41bb-8ad0-3545fb587e3a.png)

**Comment by devoto13** [comment]
You can use [import aliases](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_an_export_with_a_more_convenient_alias) to resolve this issue. See [the documentation](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/using-other-styles.md#same-icon-from-multiple-styles) for an example.
