### ISSUE TITLE
Q: Is this package compatible with Font Awesome version 6?

### ISSUE THREAD

**Issue by nelson6e65** [FortAwesome/angular-fontawesome#328]
I see in description this package is for version 5, so I'm wondering if is incompatible with version 6.

Known issues:

- [x] Icon aliases are not supported.

**Comment by devoto13** [comment]
The package should be compatible with version 6. Please report issues if you experience any bugs.

**Comment by norbert-tasi** [comment]
Hello,

This worked til I upgrade to v6:
`<fa-icon icon="tasks"></fa-icon>`
with this
```
export class AppModule {
    constuctor(lib:FaIconLibrary){
        lib.addIcons(faTasks)
    }
}
```

but now I get this error:
Could not find icon with iconName=tasks and prefix=fas in the icon library.

Could you help me with this?

Thank you!

tano

**Comment by devoto13** [comment]
@norbert-tasi Looks like the icon got renamed to `list-check` and a `tasks` alias was added, so it should have worked as before. However, icon aliases is a new v6 feature and is not yet supported by `angular-fontawesome`'s icon library implementation. 

You can switch to the true icon name (`list-check`) or wait until we add support for aliases (then your current code will work as before).

Thanks for the report by the way!

**Comment by norbert-tasi** [comment]
Thank you for your quick response. It was the case. 

I could replace every icon with the new ones and it works as expected, but unfortunatelly I can import faTasks from @fortawesome/free-solid-svg-icons as I did before and I get runtime error instead of compile error. I can live with that till the aliases.

Thank you!

tano

**Comment by devoto13** [comment]
Fixed by https://github.com/FortAwesome/angular-fontawesome/pull/335 and released as [0.10.1](https://github.com/FortAwesome/angular-fontawesome/releases/tag/0.10.1).

I'm not back-porting the changes to older versions as Font Awesome 6 is still in beta and there are available workaround for the only known incompatibility - icon aliases.

**Comment by devoto13** [comment]
@robmadole Can you look into updating https://fontawesome.com/v6.0/docs/web/use-with/angular as both Font Awesome 6 and Duotone icons are supported by Angular component.

**Comment by nielsvanrijn** [comment]
I am using `"@fortawesome/angular-fontawesome": "^0.10.1",`
but how do I specify I want the v6 version of an icon?

for example:
When using the solid `exclamation-circle` icon the left most icon is the correct v6 version of the icon, the icon on the right is the v5 version
![image](https://user-images.githubusercontent.com/14902873/150705243-8b3becfe-5096-4f3e-8811-b1723fe2e94b.png)

Usage:
```html
<fa-icon size="lg" ngClass="text-red-400" icon="exclamation-circle"></fa-icon>
```

Import
```ts
import { faExclamationCircle } from '@fortawesome/pro-solid-svg-icons';
...
library.addIcons(faExclamationCircle);
```

Versions:
```json
"@fortawesome/angular-fontawesome": "^0.10.1",
"@fortawesome/fontawesome-svg-core": "~1.2.36",
"@fortawesome/pro-solid-svg-icons": "^5.15.4",
```

**Comment by nelson6e65** [comment]
fortawesome/pro-solid-svg-icons

Version 6 is still on beta. You may need to use [6.0.0-beta3](https://www.npmjs.com/package/@fortawesome/free-solid-svg-icons/v/6.0.0-beta3)

**Comment by nielsvanrijn** [comment]
@nelson6e65 Thanks! Don't know why i didn't think of this.
I just ran:
```
npm i @fortawesome/fontawesome-svg-core@next &&
npm i @fortawesome/free-solid-svg-icons@next &&
npm i @fortawesome/pro-solid-svg-icons@next
```
And it works!
