### ISSUE TITLE
Symbols using SVG Sprites

### ISSUE THREAD

**Issue by icecoldfire** [FortAwesome/angular-fontawesome#33]
What is the correct way to implement [symbols using SVG sprites](https://fontawesome.com/how-to-use/performance-and-security)?

**Comment by rapropos** [comment]
Can't speak to "correct", but the following seems to work for me:

```
<fa-icon [icon]="spriteIcon" symbol="sprite"></fa-icon>
<svg class="svg-inline--fa fa-w-16 fa-2x">
  <use xlink:href="#sprite"></use>
</svg>
```

**Comment by devoto13** [comment]
Closing as answered by @rapropos. Thanks!

The reasoning is outlined in https://github.com/FortAwesome/angular-fontawesome/issues/122#issuecomment-454595942.
