### ISSUE TITLE
Unable to set up font-awesome with angular module federation package.

### ISSUE THREAD

**Issue by SavvasZaidQuadri** [FortAwesome/angular-fontawesome#332]
I am seeing the error `Bootstrap call not found` and this is because the angular-architects/module-federation modifies the main.ts file and creates a different bootstrap.ts file. 

Steps to reproduce: 
1)ng add @angular-architects/module-federation 
2)ng add @fortawesome/angular-fontawesome
The install should fail here with the above error.

Any idea on how to make these two compatible?

**Comment by devoto13** [comment]
We use [a utility](https://github.com/angular/angular-cli/blob/37a06a7c37f5b4286d58b475e6e12c86f00fac5b/packages/schematics/angular/utility/ng-ast-utils.ts#L56) from `@schematics/angular` to add FontAwesome module to the imports.

IMO angular-fontawesome is not the right place to tackle the problem as many other libraries will fail in this setup as well (e.g. `ng add @ng-bootstrap/ng-bootstrap`). I would suggest working with `@angular-architects/module-federation` to stop moving exactly the bootstrap code to another file. Or maybe with Angular CLI to support a different layout (I doubt that they will be interested in that though).
