### ISSUE TITLE
free fonts installation fails

### ISSUE THREAD

**Issue by simonsobi** [FortAwesome/angular-fontawesome#333]
### Describe the problem
I select first 3 free ones abut it seems it tries to isntall the PRO and fails:

The package @fortawesome/angular-fontawesome@0.8.2 will be installed and executed.
Would you like to proceed? Yes
√ Package successfully installed.
"angular-fontawesome-ng-add" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
? Choose Font Awesome icon packages you would like to use: (Press <space> to select, <a> to toggle all, <i> to invert se
? Choose Font Awesome icon packages you would like to use: (Press <space> to select, <a> to toggle all, <i> to invert se
? Choose Font Awesome icon packages you would like to use: Free Solid Icons, Free Regular Icons, Free Brands Icons
    Formatting was skipped because tslint is not installed.
| Installing packages (npm)...npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-duotone-svg-icons - Not found
npm ERR! 404
npm ERR! 404  '@fortawesome/pro-duotone-svg-icons@^5.15.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-crash'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\simonkm1\AppData\Roaming\npm-cache\_logs\2021-10-16T16_55_53_974Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

### What did you expect?

install free ones

**Comment by devoto13** [comment]
@simonsobi Did you have a chance to try the above suggestion? I noticed in your report that you use version 0.8.2 and that's most likely the reason why you experiences problems ([the 0.8.x line is for Angular 11, not Angular 12](https://github.com/FortAwesome/angular-fontawesome#compatibility-table)). I'm going to close this issue as resolved, but let me know if you still experience the problem and we can look into it further.
