### ISSUE TITLE
Feature Request: Minimize fontawesome footprint in angular. 

### ISSUE THREAD

**Issue by Baso1st** [FortAwesome/angular-fontawesome#338]
### Describe the problem you'd like to see solved or task you'd like to see made easier

As of right now we have to do a lot to get fontawesome to work. 

**1- ng add**

![image](https://user-images.githubusercontent.com/29257536/146272976-eb02c10e-aeb9-46ed-a937-ad7b83460750.png)

### Here is how I would like it to work. 

1- ```npm install ``` or ``` ng add ``` 
2- Import in style.css or in index.html only what I will use or everything If I want it all. 
3- Add my icon in my component HTML and Live happily ever after. 

### Is this in relation to an existing part of angular-fontawesome or something new?

Related to the Installation 

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?

Make fontawesome footprint on the app much smaller. 

### Why would other angular-fontawesome users care about this?

because we don't want to clutter our apps, and simplicity is king. 

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

3 sounds good, because I really had to use bootstrap icon on a new project that needed just a few icons and I didn't want to add all the things fontawesome needs to work. 

### Feature request checklist

- [X] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [X] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

### After all thank you very much for making this available

**Comment by devoto13** [comment]
These steps are there for a reason. I don't think we can get rid of any of them without loosing something we don't want to lose.

1. With (2) and (3) you import `FontAwesomeModule` to gain access to the `fa-icon` component in your templates. That's the basic Angular thing, every Angular library works like that. Not having a dedicated component means no type-checking, completion for properties, etc. If you don't want that, you can consider [vanilla Font Awesome](https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers) with `<i>` tags and CSS classes. It's not the recommended way for Angular, but it's probably the closest to what you want.

2. Re (4) and (5): there are [two approaches](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage.md#approaches) for how to use `angular-fontawesome` library, each with its own pros and cons. The one you present in the issue (explicit reference) is more verbose, but is also more explicit. You may like the [icon library approach](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/icon-library.md) better as it's exactly about "import in **app.module.ts** only what I will use or everything If I want it all".

3. Isn't (6) exactly "Add my icon in my component HTML and Live happily ever after."?

**Comment by Baso1st** [comment]
Thanks for taking the time to read and comment on my request. 
I think the icon library approach you mentioned above should work fine for now since I don't want to go vanilla if it is not the recommended way. Although I still have to do that in every module, but we can cross that bridge when we get to it. 
Thanks again and I appreciate the detailed explanation.

**Comment by devoto13** [comment]
@Baso1st Also note that you only need to register icons in `AppModule` (even if you use them in other module) - [see https://stackoverflow.com/a/64842507/1377864]. You can also consider [`SharedModule` recipe](https://angular.io/guide/sharing-ngmodules) to avoid repeatedly importing `FontAwesomeModule` into every module where you want to display an icon.

**Comment by Baso1st** [comment]
Thanks again for all your help and pointing me in the right direction!!! I really appreciate it.
