### ISSUE TITLE
Installation steps are not working for angular 13

### ISSUE THREAD

**Issue by M-Usman10** [FortAwesome/angular-fontawesome#342]
When I run `ng add @fortawesome/angular-fontawesome` it gives an error:

`Node.js version v17.1.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
Skipping installation: Package already installed
? Choose Font Awesome icon packages you would like to use: Free Solid Icons
⠴ Installing packages (npm)...npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-duotone-svg-icons - Not found
npm ERR! 404 
npm ERR! 404  '@fortawesome/pro-duotone-svg-icons@^5.15.4' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/usman/.npm/_logs/2022-01-13T18_00_36_082Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.`

**Comment by devoto13** [comment]
Did you configure the FontAwesome Pro registry as outlined in the documentation?

https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers#installing-pro

**Comment by devoto13** [comment]
Hope you were able to resolve your problem by now.
If you still experience the problem and believe that there is a bug in `angular-fontawesome`, please provide a minimal reproduction we can look at.
