### ISSUE TITLE
Question: Is there a tentative release date for v6 support?

### ISSUE THREAD

**Issue by petterhoel** [FortAwesome/angular-fontawesome#344]
Hi, I am planning some work and would love to hear any non-committing ball park estimates of when v6 support is expected to land. 

Alternatively if some of v6 is already supported with 0.10.1, that would great info too, and if so which features even better. 

Great product, thanks!

**Comment by devoto13** [comment]
The v6 should be fully supported as of angular-fontawesome@0.10.0. Are you having some specific issues?

See https://github.com/FortAwesome/angular-fontawesome#compatibility-table.

**Comment by petterhoel** [comment]
Ah, great, thanks!

I came from the docs site and was misled by this: 
![image](https://user-images.githubusercontent.com/1263775/154261945-7730e8f4-8c0a-4bbf-968f-4e67dc6a10b2.png)

**Comment by devoto13** [comment]
Thanks for the info @petterhoel. I've asked the team to update the website.
