### ISSUE TITLE
TS2322: Type 'IconDefinition' is not assignable to type 'IconProp' with FA 6

### ISSUE THREAD

**Issue by androidseb25** [FortAwesome/angular-fontawesome#345]
### Describe the problem

After updating to FontAwesome 6 I get following error: 

```
Error: src/app/header-footer/toolbar/toolbar.component.html:7:33 - error TS2322: Type 'IconDefinition' is not assignable to type 'IconProp'.
  Type 'IconDefinition' is not assignable to type 'IconLookup'.
    Types of property 'prefix' are incompatible.
      Type 'import("$PATH/node_modules/@fortawesome/free-brands-svg-icons/node_modules/@fortawesome/fontawesome-common-types/index").IconPrefix' is not assignable to type 'import("$PATH/node_modules/@fortawesome/fontawesome-common-types/index").IconPrefix'.
        Type '"fat"' is not assignable to type 'IconPrefix'.
```

My HTML Tag:

`<fa-icon [@inOutAnimation] [icon]="menuIcon"></fa-icon>`

Under FA 5 everything works fine, is the package not compatible or did I make a mistake?

**Comment by devoto13** [comment]
It probably has the same root cause as https://github.com/FortAwesome/angular-fontawesome/issues/125. Can you update all `@fortawesome/*` packages to the latest versions and make sure that you only have one instance of the `@fortawesome/fontawesome-common-types` package in your dependency tree.

**Comment by androidseb25** [comment]
Thx for the quick response :) 

I had more then one `@fortawesome/fontawesome-common-types` in my package-lock.json

I've fixed it now with adding this to the package.json file under dependencies

```
    "@fortawesome/fontawesome-common-types": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.3.0",
```

**Comment by weirdyang** [comment]
I've got the same issue:

```
Error: src/app/genre-filter/genre-filter.component.html:13:26 - error TS2322: Type 'IconDefinition' is not assignable to type 'IconProp'.
  Type 'IconDefinition' is not assignable to type 'IconLookup'.
    Types of property 'iconName' are incompatible.
      Type 'import("D:/personal/angular/bulma-angular/node_modules/@fortawesome/free-solid-svg-icons/node_modules/@fortawesome/fontawesome-common-types/index").IconName' is not assignable to type 'import("D:/personal/angular/bulma-angular/node_modules/@fortawesome/fontawesome-common-types/index").IconName'.
        Type '"acquisitions-incorporated"' is not assignable to type 'IconName'.
```

tried adding `   "@fortawesome/fontawesome-common-types": "^0.3.0",` to dependencies and no luck.

package-lock.json does not have more than one `@fortawesome/fontawesome-common-types`

**Comment by devoto13** [comment]
@weirdyang That's odd. If you're sure that you have single instance of the `@fortawesome/fontawesome-common-types` in you dependency tree, can you perhaps setup a minimal reproduction repository and push it to GitHub, so I can take a look?

**Comment by weirdyang** [comment]
Hey sorry, I solved it after I uninstalled all the fortawesome packages then nuked my node modules folders and reinstalled.

**Comment by MichaelWheldon** [comment]
I fixed this by upgrading to the latest `@fortawesome/fontawesome-common-types`, assuming this goes unnoticed by most since its a dev dep.

**Comment by lironzaa** [comment]
upgrading all @fortawesome related packges fix it

**Comment by nalucode** [comment]
> I have these dependencies at package.json file: { "@fortawesome/fontawesome-svg-core": "^6.3.0", "@fortawesome/free-regular-svg-icons": "^6.3.0", "@fortawesome/free-solid-svg-icons": "^6.3.0", "@fortawesome/react-fontawesome": "^0.2.0",
> 
> it's work

It's works in ReactJS projects too! ;)
