### ISSUE TITLE
Dynamic imports are no longer working in v6

### ISSUE THREAD

**Issue by adam-marshall** [FortAwesome/angular-fontawesome#348]
### Describe the problem

Steps:
1. Clone simplified repo at https://github.com/devoto13/fa-dynamic-icon-load 
2. Run with `ng serve`, verify the free icons bundles are created, 1 per icon.
3. Enter an icon name e.g. 'faCog' into the box.
4. Click the 'Fetch' button to verify the dynamic import is working - the Network tab should show the bundle loading, the icon will appear.
5. Upgrade to v6, e.g. via https://fontawesome.com/docs/web/setup/upgrade/packages#using-npm-check-updates 

### Expected

it to still work

### Actual

now it won't even run, error: `Error: Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons'`

**Comment by devoto13** [comment]
Looks like this is actually a bug in webpack which does not support dynamic import for the packages using package exports feature - https://github.com/webpack/webpack/issues/13865.

**Comment by adam-marshall** [comment]
ah thank you again, great spot.
