### ISSUE TITLE
FontAwesome 6 `[spin]` and `[pulse]` no longer working

### ISSUE THREAD

**Issue by darrenhollick** [FortAwesome/angular-fontawesome#349]
### Describe the problem

When using FontAwesome 6 `[pulse]` and `[spin]` no longer work.

### What did you expect?

I expected to to keep working like it did or have documentation of the breaking change.

### Reproducible test case
https://stackblitz.com/edit/angular-ivy-yakahk

I'm using the following packages:

* @fortawesome/angular-fontawesome = "^0.10.1"
* @fortawesome/fontawesome-svg-core = "~1.3.0"
* @fortawesome/free-solid-svg-icons = "^6.0.0"

Am I missing something?

**Comment by devoto13** [comment]
What exactly do you mean by "not working"? This is what I see upon loading your reproduction.

https://user-images.githubusercontent.com/823594/156880346-c284cce2-6c41-4d26-b83d-2937b8ed5c51.mov

**Comment by darrenhollick** [comment]
What is going on here... when I load that they are not moving at all.  If I revert to FA5 they move just fine.  If it's something on my system what could possibly be?  Any ideas?

**Comment by darrenhollick** [comment]
I just tried on another computer and it does work so I guess this is not a bug but rather something really weird on my computer.  I have absolutely no idea what it could be.

**Comment by darrenhollick** [comment]
Just to add some follow-up here I discovered that it doesn't spin when viewed through Microsoft Remote Desktop.  If viewed in Chrome on my computer it works correctly.  However, when remoted into my work computer and viewed in Chrome it doesn't spin.  I was able to confirm with a few other people as well.

Is there a known reason why that would happen?

**Comment by robmadole** [comment]
A lot of Remote Desktop apps will enable “prefers-reduced-motion” to save on screen updates. FA 6 now respects this values and disable animations if this is enabled. Check the browser settings and see if this is the case.

**Comment by darrenhollick** [comment]
That was the clue I needed!  Sadly there doesn't seem to be a way to have Windows set to "prefer reduced motion" but not have Chrome set that way.  But, in any case I now know to enable/disable this for testing.  Thank you!

**Comment by jherman** [comment]
@robmadole Is there a way to override this? We do all of our work via remote, and we can't signal RDP to allow this animation.

**Comment by darrenhollick** [comment]
> @robmadole Is there a way to override this? We do all of our work via remote, and we can't signal RDP to allow this animation.

So do we, however as I said there is no way that I know to have Windows set to prefer reduced movement but not have Chrome set that way.

You certainly can change the setting in Windows which will affect Chrome so you can see your animations through RDP but you're overall RDP experience maybe a little slower because of all the Windows animations etc.

If you want to try Windows allowing animations in your RDP session here are instructions for Windows 11:
1. Open Settings (start menu search for  "settings")
2. In the Settings app search for "animation effects" which should take you to **Accessibility > Visual Effects**
3. Toggle "Animation effects" to "On"
