### ISSUE TITLE
In-place-replace fa-icon with svg directly

### ISSUE THREAD

**Issue by tomgruszowski** [FortAwesome/angular-fontawesome#35]
Is there a way to replace the generated markup so all you have is the svg tag?

Looking at using FA with Angular Material in as seamless & tree-shakable way as possible, and one approach is to embed fa-icon inside mat-icon tag, but much of materials styling is dependent on an svg tag being embedded as a direct ancestor of the mat-icon tag.

That is one option, the other is to use ng-fa to hook into Materials icon library but I'm not a fan of copying sprites into assets folder, would prefer to do it with this library.

I've filed an [issue](https://github.com/angular/material2/issues/10831) with Material team regarding supporting adding raw SVG directly, something like.

iconRegistry.addSvgIcon( 'user', faUser.icon[4] /* raw SVG property of imported icon */)

Thoughts on this approach? Note, this currently does not work as addSvg expects a url and does not accept a string.

**Comment by devoto13** [comment]
I don't think you need `angular-fontawesome` for this specific use-case. Looks like Material added support for setting icon as trusted SVG strings. I would recommend to use `icon` function from `@fortawesome/fontawesome-svg-core` package to render icon into a string and than pass this string to Material.

`angular-fontawesome` also uses `@fortawesome/fontawesome-svg-core` under the hood to render icon into an SVG string and than displays it. You can find the relevant code [here](https://github.com/FortAwesome/angular-fontawesome/blob/72f0cbfaac88e437a47def1938412a20a89d5b69/src/lib/icon/icon.component.ts#L125).

Does this work for you @tomgruszowski?

**Comment by tomgruszowski** [comment]
Thanks @devoto13, already following your suggestion ever since Material team added that support. Only difference is I was doing this a bit more manually in that I was creating the outerXML and tokenizing the icon vectors via fa icon import, will look into your suggestion to do this more cleanly.

Link to my solution:
https://github.com/angular/material2/issues/11630

Something like this:
 const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${iconDefinition.icon[0]} ${iconDefinition.icon[1]}"><path fill="currentColor" d="${iconDefinition.icon[4]}" /></svg>`;

this.iconRegistry.addSvgIconLiteralInNamespace(iconDefinition.prefix,
        iconDefinition.iconName,
        this.sanitizer.bypassSecurityTrustHtml(svg));

**Comment by devoto13** [comment]
@tomgruszowski Your approach also has its advantage: no extra library in the bundle :) 
And it totally works when you only need original icons.

The main advantage of `fontawesome-svg-core` approach is that you can use all features of the FontAwesome SVG framework, e.g. transformation, rotation, mask, etc.
