### ISSUE TITLE
Support @fortawesome/fontawesome-svg-core new major version 6.1.0

### ISSUE THREAD

**Issue by thijslimmen** [FortAwesome/angular-fontawesome#351]
https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core

Version made a major bump to 6.x.

**Comment by devoto13** [comment]
Thanks for the issue, I'll try to cut a new release this weekend.

**Comment by catapop84** [comment]
I also receive this error when I try to update it in an angular project

```
 Package "@fortawesome/angular-fontawesome" has an incompatible peer dependency to "@fortawesome/fontawesome-svg-core" (requires "~1.2.27 || ~1.3.0-beta2", would install "6.1.0").
```

Hope it helps
