### ISSUE TITLE
Icon size "xl" and others not included in SizeProp type

### ISSUE THREAD

**Issue by Dhug95** [FortAwesome/angular-fontawesome#355]
### Describe the problem

When setting "xl" or other new sizes as "size" property of a fa-icon element, an error message appears saying that the type is not assignable because not included in SizeProp.

![Screenshot 2022-03-21 at 16 49 45](https://user-images.githubusercontent.com/26246186/159302547-f70dfae2-5312-4955-a075-1e3bb9080bfa.png)

![Screenshot 2022-03-21 at 16 56 30](https://user-images.githubusercontent.com/26246186/159302622-c662ec85-7f13-4e69-924b-a5e87ab3832b.png)

### What did you expect?

"xl" size, as well as "2xs", "2xl", has been added as stated on official FontAwesome documentation

![Screenshot 2022-03-21 at 16 49 25](https://user-images.githubusercontent.com/26246186/159302497-5ed9b510-df83-47de-a387-a45c9398235f.png)

### Reproducible test case

Here a simple [reproduction](https://stackblitz.com/edit/angular-ivy-2uxl6a) of the problem.

**Comment by devoto13** [comment]
@robmadole @mlwilkerson It should probably be addresed in the `@fortawesome/fontawesome-svg-core` package [here](https://github.com/FortAwesome/Font-Awesome/blob/307f2c15e2d3bdf465b43df0d1486dcd249df2a1/js-packages/%40fortawesome/fontawesome-svg-core/index.d.ts#L22). What do you think?

**Comment by robmadole** [comment]
@devoto13 yep, agreed. We'll get it looked at.

**Comment by devoto13** [comment]
Fixed in `@fortawesome/fontawesome-svg-core@6.2.0`.
