### ISSUE TITLE
Type 'string' is not assignable to type 'IconProp'.

### ISSUE THREAD

**Issue by rajhim** [FortAwesome/angular-fontawesome#356]
### Describe the problem

Type 'string' is not assignable to type 'IconProp'.

interface:
```
export interface Icon{
 icon: string;
 children: Array<Icon>;
}
```
components in ts;
`item?: Icon;`

HTML:
```
 <ng-container *ngFor="let child of item?.children">
    <fa-icon [icon]="child.icon" ></fa-icon>
 </ng-container>
```
 
 packages: 
  ```
    "@angular/cli": "~13.3.0",
    "@angular/cdk": "^13.3.0",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@fortawesome/angular-fontawesome": "~0.10.1",
    "@fortawesome/fontawesome-svg-core": "~1.2.36",
    "@fortawesome/free-regular-svg-icons": "^6.1.0",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",

```
while decalring the random icon  `    <fa-icon [icon]="child.icon" ></fa-icon>`
this issue will arrise
`Type 'string' is not assignable to type 'IconProp'.`

Is there any solution for declaring without a fixed value?

**Comment by devoto13** [comment]
You should either fix you interface to specify a compatible type (depending on your needs):

```ts
export interface Icon{
 icon: `IconDefinition` / `IconName` / `IconLookup` / `IconProp`;
 children: Array<Icon>;
}
```

Or you can opt-out of type checking in the Angular template using [`$any()` cast](https://angular.io/guide/template-expression-operators#any-type-cast-function):

```html
 <ng-container *ngFor="let child of item?.children">
    <fa-icon [icon]="$any(child.icon)" ></fa-icon>
 </ng-container>
```
