### ISSUE TITLE
Angular 11 application stops compiling after adding font-awesome 

### ISSUE THREAD

**Issue by swarooprooney** [FortAwesome/angular-fontawesome#364]
### Describe the problem

Angular 11 application after adding font-awesome using  ng add @fortawesome/angular-fontawesome@<version> stops compiling 

the error I get is 
Error: node_modules/@fortawesome/angular-fontawesome/config.d.ts:25:21 - error TS2694: Namespace '"C:/Users/swaroop/Repos/non-strict-test/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

static ɵfac: i0.ɵɵFactoryDeclaration<FaConfig, never>;
### What did you expect?

The program should continue to work after adding the package

**Comment by devoto13** [comment]
Make sure you've used the correct version as suggested in the [README](https://github.com/FortAwesome/angular-fontawesome#compatibility-table) (for Angular 11 it is 0.8.x):

```
$ ng add @fortawesome/angular-fontawesome@0.8.x
```

If you still have a problem, please provide a repository containing the minimal reproduction of the problem, so I can troubleshoot it.

**Comment by swarooprooney** [comment]
Thanks you, this solved my issue. I had totally overlooked the compatibility table
