### ISSUE TITLE
peerDependencies property is wrong

### ISSUE THREAD

**Issue by eng-dibo** [FortAwesome/angular-fontawesome#368]
as mentioned in [docs](https://github.com/FortAwesome/angular-fontawesome), @FortAwesome/angular-fontawesome requires a specific version of Angular, but its package.json doesn't contain `@angular/core` in `peerDependencies`

![image](https://user-images.githubusercontent.com/57308531/172505996-c367f5dc-5a9c-4b9d-959e-157bb8d893c5.png)

**Comment by devoto13** [comment]
Looks like a regression from the https://github.com/FortAwesome/angular-fontawesome/commit/3ba3d57c52cfa5997b9824bb5b8e57ad8a45d95f. Would you be willing to send a PR to add it back?
