### ISSUE TITLE
RxJS peer dependency is failing with Angular 6 | Make it compatible with Angular 6

### ISSUE THREAD

**Issue by pradeeprajr93** [FortAwesome/angular-fontawesome#37]
As you all may know, **Angular 6 is out!**
When I try to update my angular 5 project to angular 6, getting following error on console. 
`Package "@fortawesome/angular-fontawesome" has an incompatible peer dependency to "rxjs" (requires "^5.5.2", would install "6.1.0").
Invalid range: ">=4.0.0"`

Please try updating your rx-js dependency to above 6. #

**Comment by robbaman** [comment]
The "Invalid range: ">=4.0.0"" error seems to be an error related to the upgrade process. I had the same thing but then with TypeScript:

https://github.com/angular/angular-cli/issues/10683

and other people have similar issues:

https://github.com/angular/angular-cli/issues/10621

**Comment by crhistianramirez** [comment]
#40

**Comment by k-schneider** [comment]
Is there an ETA on a release to support v6 at this point?

**Comment by devoto13** [comment]
Version `0.1.0-10` was recently released, which adds Angular 6 support. Please give it a try!

**Comment by scttcper** [comment]
This is working.

**Comment by MaklaCof** [comment]
Shouldn't be this issue closed?
