### ISSUE TITLE
Issue with self-hosted FontAwesome 6 pro

### ISSUE THREAD

**Issue by jaytonic** [FortAwesome/angular-fontawesome#374]
### Describe the problem
We have baught FontAwesome6 and are self-hosting it, like described here: https://fontawesome.com/v6/docs/web/setup/host-yourself/webfonts.
Once done, it works when using 
`<i class="fa-duotone fa-user"></i>`

We wanted to install angular-fontawesome in order to use the and bind more easily, and variate more easily.
When I ran ng add @fortawesome/angular-fontawesome@0.10.2(we have an angular 13), selected FontAwesome 6 and selected all the fonts, I got this error:

```
ng add @fortawesome/angular-fontawesome@0.10.2
ℹ Using package manager: npm
✔ Package information loaded.

The package @fortawesome/angular-fontawesome@0.10.2 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
? Choose Font Awesome version you would like to use: Font Awesome 6
? Choose Font Awesome icon packages you would like to use: Free Solid Icons, Free Regular Icons, Free Brands Icons, Pro Solid Icons    [ Requires Pro plan: https://fontawesome.com/plans ], Pro Regular Icons  [ Requires Pro plan: https://fontawes
ome.com/plans ], Pro Light Icons    [ Requires Pro plan: https://fontawesome.com/plans ], Pro Duotone Icons  [ Requires Pro plan: https://fontawesome.com/plans ], Pro Thin Icons     [ Requires Pro plan: https://fontawesome.com/plans ]
UPDATE package.json (4616 bytes)
UPDATE src/app/app.module.ts (2676 bytes)
⠦ Installing packages (npm)...npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-duotone-svg-icons - Not found
npm ERR! 404 
npm ERR! 404  '@fortawesome/pro-duotone-svg-icons@^6.1.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jaytonic\AppData\Local\npm-cache\_logs\2022-07-19T14_23_48_118Z-debug-0.log
✖ Package install failed, see above.
```
I'm probably missing something?

### What did you expect?

The npm package installation should succeed

### Reproducible test case

1) Setup an empty angular 13
2) Install fontawesome as described here: https://fontawesome.com/v6/docs/web/setup/host-yourself/webfonts
3) run `ng add @fortawesome/angular-fontawesome@0.10.2` and select all the packages

**Comment by jaytonic** [comment]
> Please refer to the first step from the [README](https://github.com/FortAwesome/angular-fontawesome#installation) which asks to configure credentials for the NPM registry:
> 
> > If you have [FontAwesome Pro](https://fontawesome.com/plans) subscription, make sure to [configure access](https://fontawesome.com/docs/web/setup/packages#_1-configure-access) before following the installation instructions.
> 
> Also, note that https://fontawesome.com/v6/docs/web/setup/host-yourself/webfonts and `@fortawesome/angular-fontawesome` are two alternative approaches that normally shouldn't be used together. Depending on your needs, you would go with one or the other. Please refer to [this documentation page](https://fontawesome.com/docs/web/dig-deeper/webfont-vs-svg) for more information.

Hi,
Thanks for the answer, yeah, I already read this, but I thought it was to include the svg/css. So you say it's impossible to use both?

**Comment by devoto13** [comment]
It is possible to use both, but you'll effectively include icons twice: once as a font file + corresponding CSS and once as SVG paths + JS bundle.

**Comment by devoto13** [comment]
Closing as answered.
