### ISSUE TITLE
No arrow right from bracket

### ISSUE THREAD

**Issue by GustavoCinque** [FortAwesome/angular-fontawesome#375]
Sorry for not using a template, it's more like a question before the bug, if there's one, actually (maybe it's intended).

There is no version of this arrow([right from bracket](https://fontawesome.com/icons/arrow-right-from-bracket?s=solid)) in the project?

I've been trying to use it. But even adding it in the library, it still displays incorrectly, the icon definition's width and height doesn't affect the icon displaying on the page.

For example, this is what I get using icon library:
![image](https://user-images.githubusercontent.com/13166137/181341479-bd88e48d-d875-43e5-a1ca-a8850bd44749.png)

Using this definition: 
```
    const icon: IconDefinition = {
      prefix: 'far',
      iconName: 'arrow-alt-from-left',
      icon: [
        24, 
        21, 
        [], 
        'f08b', 
        'M160 416H96c-17.67 0-32-14.33-32-32V128c0-17.67 14.33-32 32-32h64c17.67 0 32-14.33 32-32S177.7 32 160 32H96C42.98 32 0 74.98 0 128v256c0 53.02 42.98 96 96 96h64c17.67 0 32-14.33 32-32S177.7 416 160 416zM502.6 233.4l-128-128c-12.51-12.51-32.76-12.49-45.25 0c-12.5 12.5-12.5 32.75 0 45.25L402.8 224H192C174.3 224 160 238.3 160 256s14.31 32 32 32h210.8l-73.38 73.38c-12.5 12.5-12.5 32.75 0 45.25s32.75 12.5 45.25 0l128-128C515.1 266.1 515.1 245.9 502.6 233.4z'
      ]
    }
```
I'm using an icon name I won't be using anyway, because of the enumeration. everything else I got from FA site.

How can I solve this?

**Comment by devoto13** [comment]
> There is no version of this arrow([right from bracket](https://fontawesome.com/icons/arrow-right-from-bracket?s=solid)) in the project?

No, as you've said there is no left variant. One option is to use [rotate feature](https://fontawesome.com/docs/web/style/rotate) to rotate the right icon 180 degrees.

> I've been trying to use it. But even adding it in the library, it still displays incorrectly, the icon definition's width and height doesn't affect the icon displaying on the page.

And they should not, because those are dimensions of the SVG's [viewBox](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox). I'm not sure where did you get the path, but you should use the same width and height values as were there before. Then the icon will scale correctly when `size` input is used or based on the container's font size.

**Comment by GustavoCinque** [comment]
> No, as you've said there is no left variant. One option is to use [rotate feature](https://fontawesome.com/docs/web/style/rotate) to rotate the right icon 180 degrees.

Which icon should I use then? I did not find neither right nor left...

>I'm not sure where did you get the path, but you should use the same width and height values as were there before.

From FA itself, there's a feature to export the SVG, either file and code.

**Comment by devoto13** [comment]
> Which icon should I use then? I did not find neither right nor left...

Not sure what do you mean by this, since you've linked to the icon from your original post - https://fontawesome.com/icons/arrow-right-from-bracket?s=solid.

> From FA itself, there's a feature to export the SVG, either file and code.

Ok, then you should use the same `viewBox` width and height as was used in the original exported SVG file.

**Comment by GustavoCinque** [comment]
> Not sure what do you mean by this, since you've linked to the icon from your original post - https://fontawesome.com/icons/arrow-right-from-bracket?s=solid.

I linked the FA one, yes, but I didn't find it inside the packages (free-solid-svg-icons, free-regular-svg-icons, etc). There's no faArrowRightFromBracket to import from, for example, @fortawesome/pro-regular-svg-icons. 

That was my question. Is there, inside the packages available here, any SVG that representes font awesome's arrow-right-from-bracket? 
Because I can't find it. I know it exists to be used as an icon and css. What I want is a solution inside your package's scope.

```json
    "@fortawesome/angular-fontawesome": "~0.9.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-brands-svg-icons": "^5.15.3",
    "@fortawesome/free-regular-svg-icons": "^5.15.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@fortawesome/pro-regular-svg-icons": "^5.15.3",
```

These are my dependencies, by the way. It may be a version problem.

**Comment by devoto13** [comment]
Note that the icon was renamed in FA v6, that's why you can't find it in the v5 packages. It was named [sign-out](https://fontawesome.com/v5/icons/sign-out?s=solid) in v5, so you should be able to import it as `faSignOut`.

Note that there is a version picker you can use when searching for icons on the website.

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/823594/181601412-1995850c-3620-4497-accf-1520dd389ac7.png">
