### ISSUE TITLE
Compatibility with theming in the html

### ISSUE THREAD

**Issue by Chudroy** [FortAwesome/angular-fontawesome#377]
Like with Angular Material Components, the ability to use the syntax **color="primary"**, for example. Like so:

`  <fa-icon [icon]="faGithub" size="2x" color="primary"></fa-icon>`

for example

**Comment by devoto13** [comment]
It should be pretty easy to "theme" icons using regular CSS, either with classes or CSS variables.

https://stackblitz.com/edit/angular-ivy-ajrhxl?file=src/styles.css

It feels like unnecessary complexity to have dedicated theming API given the narrow scope of the angular-fontawesome. Is there some specific use case you have in mind which can be improved by having a dedicated theming API vs the above suggestion?

**Comment by devoto13** [comment]
At this point it does not look like it is worth to introduce a dedicated theming API for the library.
