### ISSUE TITLE
Wrong width for some icons

### ISSUE THREAD

**Issue by Matrosskin** [FortAwesome/angular-fontawesome#378]
When I added `exclamation-triangle` svg icon to the Angular app I found that the width is not the same as height. Svg element of icon has attribute `viewBox="0 0 576 512"`.

I expected that the width is same as height like at icon preview https://fontawesome.com/icons/triangle-exclamation?s=solid. And also
svg file, downloaded from preview page, contain attribute `viewBox="0 0 512 512"`.

Here I prepared example with icon where applied wrong width: https://stackblitz.com/edit/angular-fontawesome-sample-t1tft4?file=src/app/app.component.html

**Comment by devoto13** [comment]
@Matrosskin Note that https://fontawesome.com/icons/triangle-exclamation?s=solid is a v6 icon, which indeed has size of 512x512. But in the Stackblitz you have Font Awesome 5.13 installed. In v5 this icon has size of 576x512 as you can see on [the v5 icon page](https://fontawesome.com/v5/icons/exclamation-triangle?s=duotone).

There is a version picker you can use when searching for icons to get the correct version:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/823594/185948540-acc6f4f5-ffb0-487f-96a8-7bb7766961d2.png">

**Comment by Mdkarimul** [comment]
hi how can i get all icons list used in angular like "faCircle"

**Comment by devoto13** [comment]
@Mdkarimul I don't think there is a way to do it on the website, but it should be pretty easy to get import name by converting from kebab-case to camelCase. E.g. `fa-user-alt` becomes `faUserAlt`, etc.

**Comment by devoto13** [comment]
Closing as answered.

**Comment by Matrosskin** [comment]
@devoto13 Thank you very much, the answer is so simple! And sorry for late comment from mi side.
