### ISSUE TITLE
How to put a FontAwesome icon on a DataTable button through TypeScript?

### ISSUE THREAD

**Issue by samirllorente** [FortAwesome/angular-fontawesome#38]
I'm using datatables and I want to create a button in the table, but instead of text I want to place an icon using fontawesome. I have the following code:

`this.dtOptions = { //... buttons: [ //... { extend: 'pdf', text: '<fa-icon [icon]="faDownload"></fa-icon>' } ] }`

**Comment by wartab** [comment]
Which datatables library are you using? Angular components are pre-compiled, you cannot just append components to HTML and expect those to be handled as components.

**Comment by samirllorente** [comment]
For the tables I use https://datatables.net/
But you tell me that angular is a pre-compiled language, how could you pre-compile the icons and use them through TypeScript?

**Comment by devoto13** [comment]
As pointed above that's not how Angular works. You can not insert Angular components as text in arbitrary place and expect it to work.

@samirllorente There is too much information missing to assist you efficiently. Depending on factors it may be better to either use `ComponentFactoryResolver` approach described above, render icon to SVG string (see https://github.com/FortAwesome/angular-fontawesome/issues/35) or use [simple approaches](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself). I would recommend to ask question on [StackOverflow](https://stackoverflow.com), tag it with `font-awesome` and provide as much detail about your project as possible, so people can help you choose the best approach.

Closing as this is neither bug report, nor feature request and therefore not actionable.
