### ISSUE TITLE
Sharp Icons?

### ISSUE THREAD

**Issue by Mobiusimmortal301** [FortAwesome/angular-fontawesome#380]
How can sharp icons be accessed without having to reference each icon individually?

**Comment by devoto13** [comment]
@Mobiusimmortal301 Not exactly sure what you mean (an example demonstrating your current code and pointing out what exactly you think is wrong with it should help)... But if you're using the [icon library approach](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/icon-library.md#changing-the-default-prefix) and asking how to avoid specifying a prefix for each icon, then you can use `faConfig.defaultPrefix = 'fass'` as shown at the bottom of that page.

**Comment by devoto13** [comment]
Closing as answered.
