### ISSUE TITLE
searching for house icon and can't found it

### ISSUE THREAD

**Issue by ShadowNightCoder** [FortAwesome/angular-fontawesome#389]
i was searching for house icon and i could not find it, i download the latest virsion of font awesome and search in solid icons
house and it wasnt there:
import { fahouse } from '@fortawesome/free-solid-svg-icons';
and as well searched in other icons option and there wasnt any house that is normal house
![image](https://user-images.githubusercontent.com/94745647/205481272-b421623b-b341-4223-82b1-f185e0135b36.png)

didnt find an icon.
to get the normal house icon: <i class="fa-solid fa-house"></i>

i would like to find all icons and not search in the setting of the icons files for house icon and than to see it doesnt excsist exsept broken-house or other unnormal houses option

*i use angular

**Comment by devoto13** [comment]
I suspect that you're using Font Awesome v5 and in v5 the house icon is only available as a Pro icon, see https://fontawesome.com/v5/icons/house?s=solid&f=classic. Make sure to select your version on the website when searching for icons to avoid confusion in the future.

**Comment by devoto13** [comment]
Hope you were able to resolve your problem by now.
If you still experience the problem and believe that there is a bug in `angular-fontawesome`, please provide a minimal reproduction we can look at.
