### ISSUE TITLE
Question: time-frame (first release date)

### ISSUE THREAD

**Issue by MaklaCof** [FortAwesome/angular-fontawesome#39]
Is there any time-frame for first official release?

I am checking this thread every day, but last month was really quite (no changes ...).

**Comment by robmadole** [comment]
No time frame yet. We are waiting to make sure some other changes in the base library are good-to-go before we take this project out of the pre release stage.

**Comment by MaklaCof** [comment]
Sad to hear that. Maybe you should re-think how you handle resources.

It is nice to read about all the new icons you added with release [5.0.9](https://github.com/FortAwesome/Font-Awesome-Pro/pull/1059/files), [5.0.11](https://github.com/FortAwesome/Font-Awesome-Pro/pull/1089/files), [5.0.13](https://github.com/FortAwesome/Font-Awesome-Pro/pull/1101/files), but I (and probably others too) can not use them. 

I support you kickstarter campaign just because you promise Angular support. I know you will deliver, but we are waiting for [several months](https://github.com/FortAwesome/Font-Awesome-Pro/issues/774) now ([another thread](https://github.com/FortAwesome/Font-Awesome-Pro/issues/691)). And you promised [soon](https://github.com/FortAwesome/Font-Awesome-Pro/issues/503).
Just saying you could dedicate more resources to get this done and then move on with new icons/packs.

For the end I would like to say, that there is no regrets about supporting you on kickstarter. And I loved everything you have done so far.

**Comment by devoto13** [comment]
@MaklaCof Well, you can pretty much use pre-release version for several months already. I (and probably [many others](https://npm-stat.com/charts.html?package=%40fortawesome%2Fangular-fontawesome)) do it in our projects. It is quite stable, it has documentation. It is just that guys need more time to polish everything before they can declare it stable.

Is there any specific issue, which blocks you from doing that?

**Comment by MaklaCof** [comment]
I know that I can use it for quite some time, I am tracking every change in this repository. 

I didn't try it because I read in some other issue that is not production ready. My application is quite big and when I will migrate from 4 to 5 I need to know it will work. If it will not work, I can not merge it to my release version and if I can not merge it I will constantly get merge conflicts.

So I am waiting to someone says it is production ready (probably will happened with version 1.0.0) and then I will try how lucky I am.

**Comment by robmadole** [comment]
Hey @MaklaCof our next release will be 0.1.0. Once this happens, in our minds, this is production ready. We're close to this.
