### ISSUE TITLE
Missing animations

### ISSUE THREAD

**Issue by va-it** [FortAwesome/angular-fontawesome#393]
### Describe the problem

The animations available are only a subset of what's shown on the website's spec.

### What did you expect?

I expect these animations to be available

- Beat
- Fade
- Beat-Fade
- Bounce
- Flip
- Shake
- _Spin_ 

But the only available ones are **spin** and **pulse** (the latter being marked as deprecated on the website spec).

Are these going to be added in a future release?

**Comment by devoto13** [comment]
Started to work on it in https://github.com/FortAwesome/angular-fontawesome/compare/master...devoto13:angular-fontawesome:animations. Will try to pick it up in the coming weeks.

**Comment by abierbaum** [comment]
@devoto13 This would be awesome to get in.  I didn't even know there was a way to do this with fontawesome.
