### ISSUE TITLE
FontAwesomeModule missing in '@fortawesome/fontawesome-svg-core'  - why?

### ISSUE THREAD

**Issue by Alex-1557** [FortAwesome/angular-fontawesome#394]
![BackendTst_12302022_233142](https://user-images.githubusercontent.com/104725261/210113130-437415a9-7796-4146-b475-d3c673045e68.png)

{
  "name": "angular-backend-tst",
  "version": "0.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "angular-backend-tst",
      "version": "0.0.0",
      "dependencies": {
        "@angular/animations": "^15.0.4",
        "@angular/cdk": "^15.0.3",
        "@angular/common": "^15.0.4",
        "@angular/compiler": "^15.0.4",
        "@angular/core": "^15.0.4",
        "@angular/forms": "^15.0.4",
        "@angular/material": "^15.0.3",
        "@angular/platform-browser": "^15.0.4",
        "@angular/platform-browser-dynamic": "^15.0.4",
        "@angular/router": "^15.0.4",
        "@fortawesome/fontawesome-svg-core": "^6.2.1",
        "@fortawesome/free-solid-svg-icons": "^6.2.1",
        "angular-fontawesome": "^1.0.0",
        "font-awesome": "^4.7.0",
        "generate-schema": "^2.6.0",
        "rxjs": "~7.5.0",
        "tslib": "^2.3.0",
        "zone.js": "~0.11.4"
      },

**Comment by devoto13** [comment]
Because `FontAwesomeModule` is in `@fortawesome/angular-fontawesome` 🤔 

Please follow the installation and usage instructions in the [README file](https://github.com/FortAwesome/angular-fontawesome).

**Comment by devoto13** [comment]
Hope you were able to resolve your problem by now.
If you still experience the problem and believe that there is a bug in `angular-fontawesome`, please provide a minimal reproduction we can look at.
