### ISSUE TITLE
There is a compatibility issue with "moduleResolution": "NodeNext" in TS

### ISSUE THREAD

**Issue by TomMettam** [FortAwesome/angular-fontawesome#396]
### Describe the problem

```
node_modules/@fortawesome/angular-fontawesome/config.d.ts:2:21 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@angular/core")' call instead.

2 import * as i0 from "@angular/core";
```
Same issue with `icon-library.d.ts`, `stack-item-size.directive.d.ts`, `stack.component.d.ts`, `icon.component.d.ts`, `duotone-icon.component.d.ts`, `layers.component.d.ts`, `layers-text.component.d.ts`, `layers-counter.component.d.ts`, `fontawesome.module.d.ts`

### What did you expect?

`angular-fontawesome` should import correctly with "moduleResolution" set to "NodeNext"

### Reproducible test case

Add angular-fontawesome to any Angular project which is using the new node/ESM interopability features.

Workaround would be to change my project to use CommonJS, but let's move in the progressive direction ;)

**Comment by devoto13** [comment]
Please specify versions of of `angular-fontawesome` and Angular you're using. Do you only have this issue with `angular-fontawesome` or any other libraries? Minimal reproduction would also help to resolve it faster.

`angular-fontawesome` is built using official Angular tooling for building libraries, so it should be either a common limitation of all Angular libraries or perhaps you're using old `angular-fontawesome` version or something?

**Comment by devoto13** [comment]
Hope you were able to resolve your problem by now.
If you still experience the problem and believe that there is a bug in `angular-fontawesome`, please provide a minimal reproduction we can look at.
