### ISSUE TITLE
Lost Icon - V5 to V6 upgrade

### ISSUE THREAD

**Issue by redevill** [FortAwesome/angular-fontawesome#397]
### Describe the problem
fahome icon in V5 has a chimney and a seethrough "eve"
While looking through the documented name changes
e.g. home -> house
The house icon IS NOT THE SAME ICON... looking through all the renames involving home, NONE of these icons is the same.

### What did you expect?
That we don't lose the use of icons through the upgrade process 
- this is NOT so awesome.

**Comment by devoto13** [comment]
Thanks for the issue @redevill, however this issue tracker is no the right place to raise this concern. `angular-fontawesome` just integrates FontAwesome with Angular and we can't do anything about icon shapes here.

Indeed, there are some design changes in the v6 and I'm sorry that the icon you used has changed. If none of the [available icons](https://fontawesome.com/search?q=house-chimney&o=r) works for you, please report the issue in the https://github.com/FortAwesome/Font-Awesome where icons are actually designed and your report can be seen by the icon designers.

**Comment by redevill** [comment]
Thank you - have re-submitted in the correct location.
