### ISSUE TITLE
Unable to target ".svg-inline--fa" using Css + Sass

### ISSUE THREAD

**Issue by JimmyWoooo** [FortAwesome/angular-fontawesome#408]
### Describe the problem

I'm trying to apply a round border around the svg but it's not working(sort of??). I'm targeting the `.svg-inline--fa` class to apply my css. It only works if the file is extension is Css and it's written like Sass nesting with a parent element.

Using Angular 14 and FontAwesome 5

### What did you expect?

I expected a round border around the icon but it seems that no stylings were applied. It works only for Chromium-based browsers.

### Reproducible test case
CSS file(no container):  **Doesn't work** [pic](https://prnt.sc/3TDyLMRH1Zoc)
```
.svg-inline--fa{
    border: 3px solid red;
    border-radius: 50%;
    width: 40px;
    height: 40px;
    padding: .25rem;
}
```

CSS file(with container SCSS style): **Works for Chrome + Edge** [pic](https://prnt.sc/C8509SY3BLEk)
```
.container{
    .svg-inline--fa{
        border: 3px solid red;
        border-radius: 50%;
        width: 40px;
        height: 40px;
        padding: .25rem;
    }
}
```

CSS file(with container): **Doesn't work** [pic](https://prnt.sc/5vf6pZkObj3v)
```
.container .svg-inline--fa{
      border: 3px solid red;
      border-radius: 50%;
      width: 40px;
      height: 40px;
      padding: .25rem;
}
```

SCSS file(no container): **Doesn't work** [pic](https://prnt.sc/WYqonjRGxaVx)

SCSS file(container): **Doesn't work** [pic](https://prnt.sc/Hf9_rfNhd3wd)

**Comment by devoto13** [comment]
Please refer to [this guide](https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/guide/styling-icon-internals.md) on how to style icon internals.

**Comment by JimmyWoooo** [comment]
Global styles did the trick. Thanks!
