### ISSUE TITLE
Icons not spinning in Windows

### ISSUE THREAD

**Issue by MumiaIrrequieta** [FortAwesome/angular-fontawesome#409]
The icons are not spinning in Window, but they do in Linux.
I'm using Chrome (v114.*) on both OS.
I was trying to spin "faSpinner" but it looks like it happens with all icons, just do:
`<fa-icon [icon]="faSpinner" [spin]="true"><fa-icon>`
Here's the example using latest versions (but I'm still using Angular 14 in my project and having the same issue):

[https://stackblitz.com/edit/stackblitz-starters-zthuny](https://stackblitz.com/edit/stackblitz-starters-zthuny)

Appreciate your help.

**Comment by devoto13** [comment]
Not sure what can cause this issue, the icons in the provided StackBlitz spin for me in both Windows and macOS (don't have a Linux desktop). Are you saying that the icons in StackBlitz don't spin for you on Windows? Could be the same issues as https://github.com/FortAwesome/angular-fontawesome/issues/349#issuecomment-1061221210?

**Comment by MumiaIrrequieta** [comment]
That's probably it, I'm using Windows on a remote VM.
Thank's a lot for the reply.
