### ISSUE TITLE
I got this error while installing : Bootstrap call not found

### ISSUE THREAD

**Issue by biondiBagasta** [FortAwesome/angular-fontawesome#410]
![error font awesome](https://github.com/FortAwesome/angular-fontawesome/assets/75413828/6af06c83-dac5-4d65-ad30-5e7c9f240967)

**Comment by devoto13** [comment]
Hey, Hard to tell without a minimal reproduction, but I can speculate that you're running standalone application and the existing ng-add schematic does not support it.

**Comment by alexandresebrao** [comment]
Hi @devoto13!  I'm updating project that I work on angular to v17, how do I update the package json to use master branch .

**Comment by devoto13** [comment]
@alexandresebrao You can use [0.14.0](https://github.com/FortAwesome/angular-fontawesome/releases/tag/0.14.0).
