### ISSUE TITLE
Feature request: Update FontAwesome to 6.4.2

### ISSUE THREAD

**Issue by Will-Smith-007** [FortAwesome/angular-fontawesome#411]
### Describe the problem you'd like to see solved or task you'd like to see made easier

The FontAwesome version is very old and doesn't provide the newest icons.

### Is this in relation to an existing part of angular-fontawesome or something new?

All Icons categories.

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?

Please provide all current icons from the page.

### Why would other angular-fontawesome users care about this?

Because everyone can use the latest icons e.g. "fa-x-twitter".

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

10

### Feature request checklist

- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment]
Hm, but you can update it in your project yourself. What exactly is the issue?

```
$ npm install @fortawesome/fontawesome-svg-core@6.4.2
$ npm install @fortawesome/free-brand-svg-icons@6.4.2
```

**Comment by Will-Smith-007** [comment]
Yes, you're right this is a solution. However it would be nice if the `ng add` command receives an update which can install the newest version of FontAwesome. I love this selection menu and there you can't get the newest version.

**Comment by devoto13** [comment]
With [0.14.0](https://github.com/FortAwesome/angular-fontawesome/releases/tag/0.14.0), the `ng add` command will install 6.4.2.
