### ISSUE TITLE
@fortawesome/angular-fontawesome imports symbols from @fortawesome/fontawesome-common-types, but doesn’t depend on it.

### ISSUE THREAD

**Issue by Nosfistis** [FortAwesome/angular-fontawesome#419]
### Describe the problem
Reopening #412 since the issue still exists. The issue causes problems when npm hoists packages in workspaces.

### What did you expect?
@fortawesome/angular-fontawesome should also mention @fortawesome/fontawesome-common-types as a dependency.

**Comment by devoto13** [comment]
Looks like a mistake. Feel free to send a PR to update the import to `@fortawesome/fontawesome-svg-core` and maybe add a lint rule to prohibit imports from packages which are not listed as dependencies.

**Comment by Nosfistis** [comment]
I am not sure if there is a specific eslint rule regarding this. I have tried `import/no-extraneous-dependencies` but it does not error in the current main branch.

Should I add just the package update?

**Comment by devoto13** [comment]
Okay, then just update the import to @fortawesome/fontawesome-svg-core (which is already a dependency), don't add a new dependency.

**Comment by Nosfistis** [comment]
I am not sure if this is the solution. `@fortawesome/fontawesome-svg-core` already lists the dependency. The issue is that `angular-fontawesome` imports common types without listing them as well in its dependency tree, depending on svg-core to provide that phantom dependency.

**Comment by devoto13** [comment]
Yes, but the point is that we should not import anything from the common types. So https://github.com/FortAwesome/angular-fontawesome/blob/7e3e5ed5c130ec67c4c18842873727a8b2f1ef8e/src/lib/config.ts#L2 should be updated to import these types from `@fortawesome/fontawesome-svg-core` instead.

**Comment by Nosfistis** [comment]
I have updated the PR with the change to the import.
