### ISSUE TITLE
Issue: Duplicate icons in kits

### ISSUE THREAD

**Issue by NabilNaou** [FortAwesome/angular-fontawesome#425]
### Describe the problem

When using kits and adding them to the library you have duplicate icons. 

### What did you expect?

When using kits you should only have one icon in each style (as noted by the prefix). However, some icons are duplicate. This is a hindrance when trying to print all icons through a for loop using the ''all'' object.

My kit & code uses Thin and Light icons which are split into two groups.

### Reproducible test case

Make a kit -> import through 'icon library' method -> print it through a for loop -> see console for duplicate icons.
Alternatively, print them through a for loop.

![image](https://github.com/FortAwesome/angular-fontawesome/assets/57749143/01443773-e81a-445f-8eb3-33949e84e3c2)

![image](https://github.com/FortAwesome/angular-fontawesome/assets/57749143/f5e6644e-e1e7-4bc7-bdf9-d2f6397e93ef)

**Comment by robmadole** [comment]
@NabilNaou can you send a support request to hello@fontawesome.com and ask for Rob? I'd like to look at your Kit so I need to grab your Kit token.

**Comment by NabilNaou** [comment]
> @NabilNaou can you send a support request to [hello@fontawesome.com](mailto:hello@fontawesome.com) and ask for Rob? I'd like to look at your Kit so I need to grab your Kit token.

Yeah sure. I sent an email
