### ISSUE TITLE
rotate input api does not work as documented

### ISSUE THREAD

**Issue by stefanofavero** [FortAwesome/angular-fontawesome#431]
setting `<fa-icon .... rotate="90"></fa-icon>` as documented @ https://github.com/FortAwesome/angular-fontawesome/blob/main/docs/usage/features.md is marked as an error because "90" is interpreted as a string
![image](https://github.com/FortAwesome/angular-fontawesome/assets/8805215/04029553-e178-4181-a87e-46365578a879)

I am currently using
"@fortawesome/angular-fontawesome": "^0.14.1",
"@fortawesome/fontawesome-svg-core": "^6.5.1",
"@fortawesome/free-regular-svg-icons": "^6.5.1",
 "@fortawesome/free-solid-svg-icons": "^6.5.1",

**Comment by devoto13** [comment]
Hey, The docs show incorrect usage, it should be `<fa-icon .... [rotate]="90"></fa-icon>`. The property is a number and the current example sets the value as string, hence the error. 

I'll update the docs.
