### ISSUE TITLE
Display: block required for Ionic 8+

### ISSUE THREAD

**Issue by novelapproaches** [FortAwesome/angular-fontawesome#437]
### Describe the problem

Up to Ionic 7.x <fa-icon> did not require "display: block" to be specified, after upgrading to Ionic 8.x, this is required. Although it is easy to fix by adding a style="display: block" to the <fa-icon>, it may not be preferable. The list of breaking changes with Ionic v8 is at: https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#version-8x, perhaps it of use to somebody else.

**Comment by devoto13** [comment]
Sorry, I don't understand what is it about and how it is related to the `angular-fontawesome`. If you believe there is a bug in the this library, please provide a minimal reproduction as was requested in the issue template and explain what exactly is not working as intended.
