### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by k-schneider** [FortAwesome/angular-fontawesome#44]
Any chance this project could adopt a CHANGELOG.md file so we can follow what updates are included in each new release?

**Comment by robmadole** [comment]
Yep, we'll get a CHANGELOG.md and a more official release process when the full version is released.

**Comment by devoto13** [comment]
@mlwilkerson was using [GitHub Releases](https://github.com/FortAwesome/angular-fontawesome/releases) to publish changelog in the past.

**Comment by mlwilkerson** [comment]
CHANGELOG.md is happening. Just released `0.1.1` with one.
