### ISSUE TITLE
Upgraded from v0.14 to v.0.15 and now I get an error: "Can't bind to 'spin' since it isn't a known property of 'fa-icon'."

### ISSUE THREAD

**Issue by toddhd** [FortAwesome/angular-fontawesome#447]
### Describe the problem

I recently upgraded from FA v.0.14.x to v.0.15.x and when I did, I started to see an error message stating that "Can't bind to 'spin' since it isn't a known property of 'fa-icon'." 

### What did you expect?

I expected not to see an error.

### Reproducible test case

[[](https://stackblitz.com/edit/angular-ivy-2flzzn?file=src%2Fapp%2Fapp.component.html)](https://stackblitz.com/edit/angular-ivy-2flzzn?file=src%2Fapp%2Fapp.component.html)

Angular 18.x, FA 0.15.x, Node 20.12.2, Material 3.x

**Comment by toddhd** [comment]
Please close this, I just saw the notice that spin has been deprecated. 

https://github.com/FortAwesome/angular-fontawesome/blob/main/docs/upgrading/0.14.0-0.15.0.md

**Comment by garethrpratt** [comment]
@toddhd hope you can help, did this work for you? If I change your example as per the upgrade instructions, it compiles, but the icon does not spin
