### ISSUE TITLE
I can't get the "spin" animation to work (v0.15 animation="spin")

### ISSUE THREAD

**Issue by garethrpratt** [FortAwesome/angular-fontawesome#448]
### Describe the problem

I'm struggling to get icons to spin after upgrading to 0.15. I've followed the upgrade instructions - perhaps I've missed something?

### What did you expect?

I'd like the icon to spin (infinitely)

### Reproducible test case

https://stackblitz.com/edit/angular-ivy-xpzam7

**Comment by devoto13** [comment]
Your StackBlitz works correctly for me 🤔 

https://github.com/FortAwesome/angular-fontawesome/assets/823594/a2fdae9c-59ab-4e36-87c1-6254deb8bbc8

I would suspect that upon upgrade, you have received the latest version of the `@fortawesome/fontawesome-svg-core` (as it is now bundled with library) and it now respects "prefers-reduced-motion" setting - https://github.com/FortAwesome/angular-fontawesome/issues/349#issuecomment-1061392657.

**Comment by garethrpratt** [comment]
@devoto13 thank you for your help, and you're absolutely right, "Show animations in Windows" was turned off for me. A setting I've not seen before!

![image](https://github.com/FortAwesome/angular-fontawesome/assets/25686738/045136a9-e261-4783-9cd0-386c754f2f6a)

**Comment by dhabierre** [comment]
@garethrpratt,

I am developing my application in a VM without Windows animations, and you were right!
I need to enable Windows animations to get this working with v0.15.0.

```html
<fa-icon [icon]="faSpinner" [animation]="'spin'"></fa-icon>
```

Windows 11:

![image](https://github.com/user-attachments/assets/598e7a05-f8d0-4b39-9887-2233331ce14f)

Without this option, animation is freezed.

Hope this help.
