### ISSUE TITLE
Feature request:  conditional animation

### ISSUE THREAD

**Issue by bregnvig** [FortAwesome/angular-fontawesome#449]
### Describe the problem you'd like to see solved or task you'd like to see made easier

In versions `^0.14.1` we had input property `spin` which could either be `true` or `false`. 

E.g the refresh icon is spinning while fetching data from the backend is progress. When data has been fetched, the animation stops.

This is not possible for me with the new `animation` icon. Maybe extends the `AnimationProp` with `none` or a property to enable disable animations

With `^0.15.0`

``` TypeScript
@if (taskList.loading) {
  <fa-icon [icon]="faIcons.refresh" animation="spin"/>
} @else {
  <fa-icon [icon]="faIcons.refresh"/>
}
```

With `^0.14.1`

``` TypeScript
<fa-icon [icon]="faIcons.refresh" [spin]="taskList.loading"/>
```

### Why would other angular-fontawesome users care about this?

Maybe others could use conditional animation? 

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

4 Plus it should be very simple.

### Feature request checklist

- [X] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [X] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [X] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment]
It is possible. See [upgrading instructions](https://github.com/FortAwesome/angular-fontawesome/blob/main/docs/upgrading/0.14.0-0.15.0.md#remove-usage-of-the-spin-and-pulse-inputs) for an example.
