### ISSUE TITLE
Sorry Question about pro

### ISSUE THREAD

**Issue by JohnFredMeyer** [FortAwesome/angular-fontawesome#457]
Hello just purchased pro and have setup and is working fine. Question in directions it shows the package for @fortawesome/pro-duotone-svg-icons. On website when searching I see there are duotone thin icons. How do you display those? The instructions show that as the only duotone package and it appears to be the regular duotone only. Thanks.

**Comment by devoto13** [comment]
@fortawesome/duotone-thin-svg-icons is the package name I believe. Will be added to ng add in the next release.

**Comment by JohnFredMeyer** [comment]
Ok so not capable right now? Will have to wait till updated release? Thanks.

**Comment by devoto13** [comment]
No-no, it's possible. `npm install @fortawesome/duotone-thin-svg-icons` for the time being. In the upcoming release it will also be an option in the `ng add` command.

**Comment by JohnFredMeyer** [comment]
ah thanks!
