### ISSUE TITLE
Default style prefix

### ISSUE THREAD

**Issue by piernik** [FortAwesome/angular-fontawesome#46]
If I use `<fa-icon icon="coffee"></fa-icon>` it is translated to `fas-coffee` and I have only `far`.
Is there a default font style option?

If not maybe adding in `forRoot` config?

**Comment by robmadole** [comment]
@piernik try `<fa-icon [icon]="['far', 'coffee']"></fa-icon>`. If you have any further trouble try posting here: https://stackoverflow.com/tags/angular-fontawesome

**Comment by devoto13** [comment]
@piernik I think this is good idea and it will be easy to implement in the `angular-fontawasome` library without affecting core.

**Comment by piernik** [comment]
Glad to hear it

**Comment by piernik** [comment]
any updates?

**Comment by alexjpwalker** [comment]
Is it still possible to set the default style prefix?

`FaIconService` (referenced in #84 , in both the code and the README changes) appears to be gone.
