### ISSUE TITLE
NPM artifacts without Github tags

### ISSUE THREAD

**Issue by jfairley** [FortAwesome/angular-fontawesome#47]
I'm currently using ver `0.1.0-8` of this library. So far `-9` and `-10` versions have been published to NPM, but there are no tags in Github to show what they represent and what has changed. Is this a bug in the publish process? I find the tags very handy to determine whether I should upgrade.

**Comment by robmadole** [comment]
Yep, we just missed these during the release process.

**Comment by lawchihon** [comment]
Will it be possible to add them back?

**Comment by mlwilkerson** [comment]
Just published `0.1.1` with GitHub tagging, using our latest documented release process.
