### ISSUE TITLE
Set default prefix/style

### ISSUE THREAD

**Issue by DaSchTour** [FortAwesome/angular-fontawesome#49]
Currently all icons are taken from fas by default. I would like to only use the light icons for my project and would like to configure this while loading the module. This would avoid a lot of boilerplatte by not adding the fal prefix to all icons.

I think this is caused by the fact, that instead of using ngOnInit the first ngOnChanges is used, that runs before ngOnInit.

**Comment by MaklaCof** [comment]
This is somehow duplicate to #46.
