### ISSUE TITLE
Use long form for boolean attributes

### ISSUE THREAD

**Issue by devoto13** [FortAwesome/angular-fontawesome#5]
Currently component expects a short form for boolean [attributes](https://github.com/FortAwesome/angular-fontawesome/blob/master/src/icon.component.ts#L107-L111), e.g. `<fa-icon spin></fa-icon>`. I don't think the short form of attributes is used in Angular world, so it will probably be confusing to users.

What's more important is that it blocks an important use case of binding variable to the boolean attribute. I was trying to disable animation by setting attribute to `false` and was surprised that it did not work.

Consider this example:

```ts
@Component({
  selector: 'my-comp',
  template: '<fa-icon [icon]="faSpinner" [spin]="isAnimated"></fa-icon><button type="button" (click)="isAnimated=!isAnimated">Toggle animation</button>'
})
class MyComp {
  isAnimated = true;
}
```

I would expect animation to stop after clicking a button first time.

**Comment by mlwilkerson** [comment]
Good catch.
