### ISSUE TITLE
Support Async Pipe for the icon attribute

### ISSUE THREAD

**Issue by DaSchTour** [FortAwesome/angular-fontawesome#50]
When using something like this `<fa-icon [icon]="icon | async"></fa-icon>` the component crashes on the first emit of null and doesn't go on if the icon changes in a later state. I would be nice if the component would not throw errors on null icons and just show the not available placeholder or something similar.

**Comment by robmadole** [comment]
@DaSchTour this is the first time I've seen `| async`. What is that exactly?

**Comment by robmadole** [comment]
Oh, nevermind. I found it. The `AsyncPipe`. :+1:

**Comment by devoto13** [comment]
Reproduced here: https://stackblitz.com/edit/angular-z8v4ux-memw8j

**Comment by osahner** [comment]
You could rewrite your code to:

`<h1 *ngIf="icon | async as nonAsyncIcon"><fa-icon [icon]="nonAsyncIcon"></fa-icon> angular-fontawesome template</h1>`

as documented here: https://angular.io/api/common/NgIf#storing-conditional-result-in-a-variable

**Comment by devoto13** [comment]
We actually want component to crash, when `icon` input is not provided.

Either use solution from @osahner to render nothing at all until icon is available:

```
<fa-icon *ngIf="icon | async as nonAsyncIcon" [icon]="nonAsyncIcon">
```

Or provide the default icon until the desired one is available:

```
this.icon = loadIcon().pipe(startsWith(defaultIcon));
```

**Comment by DaSchTour** [comment]
> We actually want component to crash, when `icon` input is not provided.

WTF? Seriously? You should never want something to crash. It should catch and report errors and continue working.

**Comment by devoto13** [comment]
Maybe I was not completely clear. Component will throw a clear error that `icon` input property is required. Missing `icon` input is not an expected usage and warning is easy to miss especially if it appears after the refactoring.

Solutions described in https://github.com/FortAwesome/angular-fontawesome/issues/50#issuecomment-519890025 allow to clearly express the intention: show either nothing or a placeholder icon. I've also created https://github.com/FortAwesome/angular-fontawesome/issues/170 to add support for the global placeholder icon.
