### ISSUE TITLE
Using directly in my Angular 6+ library?

### ISSUE THREAD

**Issue by kolkov** [FortAwesome/angular-fontawesome#52]
Hi! I create native wysiwyg editor for Angular 6+ https://github.com/kolkov/angular-editor.
Is a good idea to include this module directly in my Angular 6+ library?

**Comment by tomgruszowski** [comment]
@kolkov why not? this is tree shakable which is extremely compelling over the font based solution.

Take a look at [ngx-sharebuttons](https://github.com/MurhafSousli/ngx-sharebuttons) as he did this a month or so ago, allowing both font and svg based icons.

**Comment by robmadole** [comment]
@kolkov sure. If this is useful to you include it. That's why we made it :)

**Comment by kolkov** [comment]
I was wondering if there would be conflicts if the user also added a library to his project? or connect through the network?

**Comment by robmadole** [comment]
If someone is already using Font Awesome 4 there could be a conflict, @kolkov
