### ISSUE TITLE
Error when adding icons from PRO

### ISSUE THREAD

**Issue by MaklaCof** [FortAwesome/angular-fontawesome#56]
I found out strange behaviour when migrating from FA4 to FA5. I thought I had some strange code so I started new ASP.NET Core Angular template and repeat strange behaviour:
This code works:
```
import { library } from '@fortawesome/fontawesome-svg-core';
import { faCoffee } from '@fortawesome/free-solid-svg-icons';

library.add(faCoffee);
  <fa-icon icon="coffee"></fa-icon>
  <fa-icon icon="calendar"></fa-icon>   <!-- Not rendered (because it was not added to library which is expected -->
```
If I also add `faCalendar` to library, icon is displayed.

But adding icon from PRO shows errors (but Angular is compiled and page is displayed):

> Error	TS2345	(TS) Argument of type 'IconDefinition' is not assignable to parameter of type 'IconDefinitionOrPack'.
>   Type 'IconDefinition' is not assignable to type 'IconPack'.
>     Index signature is missing in type 'IconDefinition'.	D:\Temp\FontAwesome\FontAwesome\ClientApp (tsconfig or jsconfig project)	D:\Temp\FontAwesome\FontAwesome\ClientApp\src\app\share.module.ts	
> 
![2018-06-14_17-28-07](https://user-images.githubusercontent.com/1589573/41422034-5952a6c4-6ff8-11e8-8a42-0a5a433f947b.png)

Another strange behaviour is that when I include one icon from PRO, all icons works:
```
import { FontAwesomeModule } from "@fortawesome/angular-fontawesome";
import { library } from "@fortawesome/fontawesome-svg-core";
import { faHome } from "@fortawesome/fontawesome-pro-regular";
library.add(faHome);

  <fa-icon [icon]="['far', 'home']"></fa-icon>
  <fa-icon [icon]="['far', 'key']"></fa-icon>    <!-- Just works, but I think it shouldn't. -->

```
Everything from `packages.json` about `@fortawesome`:
```
        "@fortawesome/angular-fontawesome": "0.1.0-10",
        "@fortawesome/fontawesome-pro-light": "^5.0.13",
        "@fortawesome/fontawesome-pro-regular": "^5.0.13",
        "@fortawesome/fontawesome-svg-core": "^1.2.0-14",
```

**Comment by robmadole** [comment]
Try `@fortawesome/pro-regular-svg-icons`, `@fortawesome/pro-light-svg-icons`instead @MaklaCof . Those packages you are using are the old one (which will be deprecated soon).

**Comment by MaklaCof** [comment]
Hi @robmadole 
I follow [this](https://fontawesome.com/how-to-use/js-component-packages) and [this](https://fontawesome.com/how-to-use/use-with-node-js) documentation. Just hint for FortAwesome to fix. :)

It looks like strange behaviour when all icons are included is also gone.

**Comment by jmdmao** [comment]
@MaklaCof Same "problem" with @fortawesome/free-brands-svg-icons.

**Comment by jmdmao** [comment]
@robmadole same "problem"with @fortawesome/free-brands-svg-icons.

**Comment by robmadole** [comment]
@jmdmao what problem is that? You are seeing the same error as listed above?

**Comment by jmdmao** [comment]
@robmadole I was having the same problem, but after following some suggestions from another topic here from the forum, it worked almost perfectly. The only problem now is that the time to generate a production version of the app by angular-cli has gone up from a few seconds to up to 6-7 minutes sometime.
