### ISSUE TITLE
"export 'FontAwesomeModule' (imported as 'i97') was not found in '@fortawesome/angular-fontawesome'

### ISSUE THREAD

**Issue by choopage** [FortAwesome/angular-fontawesome#57]
Did anyone get this issue when using angular-fontawesome with Angular 6?

![screen shot 2018-06-21 at 12 05 05 pm](https://user-images.githubusercontent.com/6467136/41697471-8aa533d8-754b-11e8-973b-cef60f736b70.png)

![screen shot 2018-06-21 at 12 06 24 pm](https://user-images.githubusercontent.com/6467136/41697472-8cb80204-754b-11e8-87a5-b6ed351ff589.png)

![screen shot 2018-06-21 at 12 08 41 pm](https://user-images.githubusercontent.com/6467136/41697551-df0babfa-754b-11e8-90aa-5975982a4de9.png)

Adding this line of code `import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';` causes that error.

**Comment by travis1234** [comment]
yep i'm getting the same problem.

**Comment by choopage** [comment]
@travis1234  you are totally right. Reverted as seen here. Problem fixed. 

![screen shot 2018-06-21 at 12 11 41 pm](https://user-images.githubusercontent.com/6467136/41697656-5381c366-754c-11e8-9373-469af16d763e.png)

**Comment by bjornharvold** [comment]
Same issue.

**Comment by dottodot** [comment]
I'm having the same issue too, had to revert back.

**Comment by PyArchitect** [comment]
Same problem.

**Comment by devoto13** [comment]
The root cause seems to be that it is not using correct `tsconfig.json` for build. Relevant issues is https://github.com/dherges/ng-packagr/issues/915. Probably needs to be added [here](      .forProject(join(process.cwd(), 'src/package.json'))), but it looks like `tsconfig.json` itself need to be adjusted as well. If anybody want to give it a shot - you're welcome. Otherwise I'll try to create a PR later today.

**Comment by mlwilkerson** [comment]
Thanks @devoto13. I'll add a note to the current README for the moment to direct any newcomers to use `0.1.0-10` until we get it resolved.

**Comment by mastermike501** [comment]
Hi all, has this issue been fixed as of 0.3.0? I am still seeing this issue when using 0.3.0 with Angular 6.0.1.

**Comment by pethaniakshay** [comment]
I am facing the same issue with Angular 8 and fontawesome svg core version 1.2.22
