### ISSUE TITLE
Bundling, Tree Shake, Ahead-of-time support

### ISSUE THREAD

**Issue by igorlino** [FortAwesome/angular-fontawesome#6]
1st of all, I happy to see this official library get done. FA5 is really awesome and I know there are quite a lot of modern webprojects with Angular+Boostrap that are definitively going to upgrade to FA5 Pro if there is nice official library to support it.

Here is a very nice description of how best to provide a library
http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/

that will leverage the most  important features of angular 5, so that it can be easily used also in mobiles or similar smaller bundles.

**Comment by devoto13** [comment]
This package uses Angular Package Format v5, so bundling is done and AoT compilation is supported. Tree-shaking is working, when using deep imports for icons. There is also ongoing work to support tree shaking, when importing icons from package's main without [extra configuration](https://fontawesome.com/how-to-use/use-with-node-js#tree-shaking).

I think we can consider this issue resolved. Unless you have some more concrete comments?

**Comment by igorlino** [comment]
Hi, thanks for the fast answer,

I have seen inside your package.json, it does have what the [Angular Package Format v5](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview)
 specifies. 

I see there was a lot related work done [recently](https://github.com/FortAwesome/angular-fontawesome/pull/4).  +1

Yes I think from implementation point of view, this is what is expected. I think perhaps there could be a bit more information in the github description of this library, to highlight this nice feature.
Quite many people will be looking first at the github description, if its empty it won't give the best impression.

**Comment by devoto13** [comment]
As stated in the README it is still work in progress. More documentation is coming. Stay tuned ;)

**Comment by mlwilkerson** [comment]
I updated the README just now to provide a little more context for newcomers to our project here.

**Comment by igorlino** [comment]
The link 
https://github.com/FortAwesome/Font-Awesome-Pro/issues/978
is broken

**Comment by devoto13** [comment]
@igorlino It is not broken. It is only available to FA Pro subscribers.

**Comment by igorlino** [comment]
@devoto13  Thanks. I'm in discussing with my project, I hope to get very soon that access  ;)
