### ISSUE TITLE
Unexpected value 'undefined' imported by the module 'xxx'

### ISSUE THREAD

**Issue by xalhera** [FortAwesome/angular-fontawesome#62]
### Describe the problem

After  upgrading the NPM package "@fortawesome/angular-fontawesome" to 0.1.0, an error appears with the message :

**Unexpected value 'undefined' imported by the module 'xxx'**
(where 'xxx' is the name of the module where **FontAwesomeModule** is imported)

### What did you expect?

I expected that I could compile my project after ugrading the package "@fortawesome/angular-fontawesome" to the latest version without an error.

### Reproducible test case

You can find a [demo on stackblitz](https://stackblitz.com/edit/angular-fontawesome-0-1) which reproduces that bug.

**Comment by EvilJimJafar** [comment]
+1

**Comment by fchiumeo** [comment]
see #57

**Comment by mlwilkerson** [comment]
Yeah, I'm wrapping up the `0.1.1` release now, so I expect this to be resolved today.

**Comment by mlwilkerson** [comment]
OK, `0.1.1` is out. Update and see how that works.

**Comment by EvilJimJafar** [comment]
Works for me now, thanks.
