### ISSUE TITLE
icon not found ng-build

### ISSUE THREAD

**Issue by TheBoneJarmer** [FortAwesome/angular-fontawesome#63]
For the past hours I have been breaking my head on something pretty frustrating. Out of nowhere when I build my angular app and publish my website to azure the icons are missing! This did not happen last week for sure, I don't get it. It does work just fine when I use ng-serve and run the site locally but when I try to publish it it is as if all icons are gone... The command I use for building the app is "ng build --prod --aot" and the output is then used in the wwwroot folder of an dotnet core mvc app.

**Comment by robmadole** [comment]
What version of angular-fontawesome are you using? Can you give us the site URL?

**Comment by geo242** [comment]
I am having the same issue. [Here is a link to the deployed version](http://oybnl.staging.v2.iverticle.net/admin_angular)

You don't need to log into this site to see the console log errors.

**Comment by robmadole** [comment]
@TheBoneJarmer can you provide a reproducible example?

@geo242 I'm not seeing anything in the console. What should I be looking for?

**Comment by TheBoneJarmer** [comment]
Hi @robmadole 
I am very sorry for the late reply! My colleague managed to fix the issue because it seemed the imports were not being executed, however, I cannot provide an example at the moment unfortunately to show the difference. Sorry for that.

**Comment by robmadole** [comment]
no worries!
