### ISSUE TITLE
@fortawesome/Angular-FontAwesome doesn't work within an Angular 6 Library

### ISSUE THREAD

**Issue by RushuiGuan** [FortAwesome/angular-fontawesome#65]
I am trying to run the Explicit reference code example within an Angular 6 library.  It doesn't compile and here are the build errors. 
```
projects/test-lib/src/lib/font-test/font-test.component.ts(11,3): error TS4029: Public property 'faCoffee' of exported class has or is using name 'IconDefinition' from external module "c:/git/test-app/node_modules/@fortawesome/fontawesome-common-types/index" but cannot be named.

Error: projects/test-lib/src/lib/font-test/font-test.component.ts(11,3): error TS4029: Public property 'faCoffee' of exported class has or is using name 'IconDefinition' from external module "c:/git/test-app/node_modules/@fortawesome/fontawesome-common-types/index" but cannot be named.

    at Object.<anonymous> (c:\git\test-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at fulfilled (c:\git\test-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
    at <anonymous>
```
Please note that it works for an application but not a library.  The library is generated using the following command:
```
ng new test-app
cd test-app
ng generate library test-lib
```

Thanks

-Rushui

**Comment by kirakishin** [comment]
Hello @RushuiGuan ,

i have the same problem, but i haven't any error shown.
my console shows only and nothing append : 
`92% chunk asset optimization UglifyJSPlugin`

how do you show the error, my main tsconfig file is  : 
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "noStrictGenericChecks": false,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "strict": true,
    "paths": {
      "lib": [
        "dist/lib"
      ],
      "lib/*": [
        "dist/lib/*"
      ],
    }
  },
  "exclude": [
    "bazel-out",
    "dist/example-app",
    "dist/gallery",
    "node_modules",
    "**/*/node_modules",
    "modules/schematics/src/*/files/**/*"
  ],
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  },
  "bazelOptions": {
    "suppressTsconfigOverrideWarnings": false
  }
}

```

but after many tests, it appears that my build is extremely slow (5min) when i add icon to the library..

**Comment by mlwilkerson** [comment]
The 92% thing is almost certainly caused by this [known issue](https://github.com/fabiosantoscode/terser/issues/50) in the minifier used for production builds in Webpack 4. The root cause has been fixed, but not yet integrated and released in Webpack 4. We have [some workarounds](https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking) for you to try in the mean time.

**Comment by mlwilkerson** [comment]
@kirakishin I think my previous comment mostly addresses your scenario, based on your observation of the 92% thing.

But @RushuiGuan, your issue seems different. I don't recall whether we have any integration tests for adding this library to another Angular library. Normally our library is added to an app.

@scttcper or @devoto13: do you know what might be different or problematic in the build config with adding our Angular library to _another_ Angular _library_?

**Comment by scttcper** [comment]
Looks like its coming from `fontawesome-common-types`. would need to see the library code as well

**Comment by RushuiGuan** [comment]
The workaround is to add `import {IconDefinition } from '@fortawesome/fontawesome-common-types';` to any ts file that has icon declarations.  Not ideal, but it works.

@scttcper the code below in a library will cause the compile error when the TestComponent is declared  in a module.
```
import {faChevronRight} from '@fortawesome/free-solid-svg-icons'
import { Component } from '@angular/core';

@Component({
	selector: 'test'
 })
export class TestComponent{
	faChevronRight = faChevronRight;
}
```

**Comment by devoto13** [comment]
IIRC it is a TypeScript limitation, when emitting declaration (i.e. `declaration: true` is set in the `tsconfig.json`. https://github.com/Microsoft/TypeScript/issues/5711 is a relevant issue. I don't think anything is broken in the FA library, it's just how TypeScript works.

The workaround is to add explicit type annotation to the property (which in turn ensures that there is an import statement for the required type). E.g. `class MyComponent { faCoffee: IconDefinition = faCoffee }`. See linked issue for more reasoning on why it is needed.

**Comment by kirakishin** [comment]
@mlwilkerson thanks a lot! now it takes 35 sec :)

**Comment by RushuiGuan** [comment]
Thanks devoto.  I will mark this as resolved.

**Comment by erdalceylan** [comment]
import { faEdit} from '@fortawesome/pro-light-svg-icons/faEdit';
import { faAddressCard} from '@fortawesome/pro-light-svg-icons/faAddressCard';

library.add(faEdit, faAddressCard);

works for me thank you @mlwilkerson

**Comment by learnuser521** [comment]
Has the issue with 92% thing been fixed or do we still have to use the workaround ?

**Comment by devoto13** [comment]
@learnuser521 It is supposed to be fixed using Angular CLI 7+ and I do not experience this issue in my applications. However another user has reported that he still experiences this problem. If you can provide a reproduction for the problem using Angular CLI 7+ we can take a look, but without reproduction it is rather hard to do anything.

See https://github.com/FortAwesome/angular-fontawesome/issues/34 for more details.

**Comment by learnuser521** [comment]
@devoto13 I have not yet updated to Angular 7, will get back if there are issues after the update. Thank you
