### ISSUE TITLE
long compile time

### ISSUE THREAD

**Issue by erdalceylan** [FortAwesome/angular-fontawesome#67]
library.add(faPaperPlane, faGlobeAmericas, faSmile, faLaugh, faGrin, faGift, faTrash, faImages, faUserCircle, faEdit,faAddressCard, faGooglePlusG, faTwitter, faFacebookF, faSearch);
Time: 769431ms
12.82385 minute

**Comment by fchiumeo** [comment]
[#65](https://github.com/FortAwesome/angular-fontawesome/issues/65#issuecomment-401856551)

**Comment by mlwilkerson** [comment]
Thanks @fchiumeo. You beat me to it.

Yes, @erdalceylan. Your compile time issue is almost certainly the same problem, a performance regression in `uglify-es` / `terser`. See my comments on #65.
