### ISSUE TITLE
Not find icon fab-facebook

### ISSUE THREAD

**Issue by lapongua** [FortAwesome/angular-fontawesome#69]
Hello,

¿how to use `<i class="fab fa-facebook-f"></i>`?

thanks.

**Comment by devoto13** [comment]
@lapongua Please check [Usage section](https://github.com/FortAwesome/angular-fontawesome#usage) in the project REAME file for information on how to use this library.

Demo: https://stackblitz.com/edit/angular-z8v4ux-okzszq
