### ISSUE TITLE
modern web project generators support

### ISSUE THREAD

**Issue by igorlino** [FortAwesome/angular-fontawesome#7]
Something that will explosively increase usage of angular-fontawesome is if there is clear, easy and consistent instructions how to include/consume the angular-fontawesome in the 2 most powerful and popular angular 5 web project generators:

**angular-seed :** 
- for more enterprise/advanced projects
- project: https://mgechev.github.io/angular-seed/
- github: https://github.com/mgechev/angular-seed
- example of an intergration: https://github.com/mgechev/angular-seed/wiki/Integration-with-AngularMaterial2

**angular-cli:**  
- for fast 1-click projects
- project: https://cli.angular.io/
- github: https://github.com/angular/angular-cli
- example of an integration: https://material.angular.io/guide/getting-started

**Comment by devoto13** [comment]
This is very good idea. We should definitely do it once library is documented and has a stable release.

**Comment by kukac7** [comment]
angular-cli +1

**Comment by mlwilkerson** [comment]
+1 😉

**Comment by mlwilkerson** [comment]
@igorlino Could you have a look at our latest pre-release `0.1.0-8` and its documentation for using this component and let us know what you think, with respect to your suggestion above?

All of the installation instructions and examples in the [README](https://github.com/FortAwesome/angular-fontawesome/blob/master/README.md) are based on Angular CLI.

**Comment by ceilino** [comment]
@mlwilkerson  I have finally given a last try, not with the angular cli, but with an angular-seed project.
I have good news, migrating from FA4 to FA5 is now working quite well. My production build was reduced by ~500kb, no joke.

Thanks a lot for all the awesome work you guys have done.

If you wish to I can contribute the section for the angular-seed generator.

After reading the README, the following things came to my mind:

+ very efficient usage of fonts in the module concept. super efficient builds.
+ typescript support
+ quite many useful ng-oriented examples (I call then ng-FA examples )
+ easy to follow angular-cli instructions
+ nice support for different module formats. (i.e. UMD), which makes it possible to easy integrate the library in optimized modern web projects.
+ finally FA5 :+1: 

- table of contents is urgent, its easy to lose yourself
- markdown can be sometimes a bit plain.
- there is reference to the website for some FA features, but the plain-FA examples at the website look too awesome in comparison with the ng-FA ones of README.md
- probably too much to ask, but the presentation of an example could be a bit more structure, by using tab concept. See the documentation for [ngClick](https://docs.angularjs.org/api/ng/directive/ngClick)
Its a lot more intuitive to see which files are involved, and what content that files has

**Comment by devoto13** [comment]
https://github.com/mgechev/angular-seed is deprecated. Wiki guides in Angular CLI are also deprecated - https://github.com/angular/angular-cli/issues/13018#issuecomment-454907996.

[README](https://github.com/FortAwesome/angular-fontawesome/blob/master/README.md) has the integration steps, which are not project generator specific and should work in any sane environment.

**Comment by igorlino** [comment]
@devoto13 thanks for the tip 👍  and thanks for the rest of the documentation effort.
