### ISSUE TITLE
Problem with inline styling due to not passing the CSP

### ISSUE THREAD

**Issue by CmajSmith** [FortAwesome/angular-fontawesome#73]
Hello.
I'm using Angular 6 along with angular-fontawesome.

After general setup everything works perfect locally, but once deployed to production the icons aren't styled properly and I get the error in console:

```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-1Crl/GVwHSFINQSzfyuyHRndH1ljVgs19xrozlYQ1eU='), or a nonce ('nonce-...') is required to enable inline execution.
```

nginx configured the way it sends a header like:
```
...
add_header Content-Security-Policy "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://*.trendeo.com; object-src 'none'";
...
```

So the question is: can I avoid fontawesome inline styles to be inserted into the page and somehow include 'em into a separate file (or import into main .scss-file)?

**Comment by robmadole** [comment]
@CmajSmith you can disable inline styles using a configuration.

https://fontawesome.com/how-to-use/with-the-api/setup/configuration (check `autoAddCss`)

You can then include the CSS from `@fortawesome/fontawesome-svg-core/styles.css`. :+1:

**Comment by CmajSmith** [comment]
@robmadole absolutely spot on. Thx a lot!
