### ISSUE TITLE
Stacking icons

### ISSUE THREAD

**Issue by BigSakoLol** [FortAwesome/angular-fontawesome#74]
According to offical guide, you can stack icons like below

```html
<span class="fa-stack fa-2x">
  <i class="fas fa-square fa-stack-2x"></i>
  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
</span>
```

How can I do this with this library?

**Comment by robmadole** [comment]
Check out the "Layers" section @BigSakoLol.

https://github.com/FortAwesome/angular-fontawesome#examples

**Comment by danielflippance** [comment]
The link above is now broken. See Stacked and Layers here:
https://github.com/FortAwesome/angular-fontawesome/blob/master/docs/usage/features.md#stacked-icons
