### ISSUE TITLE
Power Transforms Have No Effect

### ISSUE THREAD

**Issue by arajay** [FortAwesome/angular-fontawesome#75]
Using power transforms (as documented [here](https://fontawesome.com/how-to-use/on-the-web/styling/power-transforms)) with Angular-Fontawesome doesn't seem to have any effect. 

Example:
`<fa-icon icon="caret-down" data-fa-transform="rotate-180">`
The caret still points down.

**Comment by robmadole** [comment]
Hey @arajay. Please check the docs again: https://github.com/FortAwesome/angular-fontawesome
