### ISSUE TITLE
Stacking position

### ISSUE THREAD

**Issue by maxisam** [FortAwesome/angular-fontawesome#76]
```
    <fa-layers class="fa-fw">
      <fa-icon [inverse]="true" [icon]="faCircle" size="4x" ></fa-icon>
      <fa-icon [icon]="faChevronLeft" transform="shrink-6" size="4x"></fa-icon>
    </fa-layers>
```

I don't understand why faChevronLeft is not in the center. Currently I use right-3 to adjust it but it is kinda weird. I check the code, it seem like the width of the faChevronLeft is only half of the width of faCircle.

Thanks!

**Comment by maxisam** [comment]
I think it is because there is no size input for fa-layers. So text:center doesn't really work when I have a 4x size on icon.

**Comment by robmadole** [comment]
@maxisam yeah you are putting these icons in a container that is just too tiny.

Try this (add `fa-4x` to the layers):

```
<span class="fa-layers fa-fw fa-4x">
  <i class="fas fa-circle fa-inverse"></i>
  <i class="fas fa-chevron-left"></i>
</span>
```

**Comment by robmadole** [comment]
Yeah that's a pretty good idea. Going to add a feature request.
