### ISSUE TITLE
layering with text

### ISSUE THREAD

**Issue by maxisam** [FortAwesome/angular-fontawesome#77]
![image](https://user-images.githubusercontent.com/456807/43782724-97661ad4-9a25-11e8-9d9f-6ee3b18810e2.png)

How to create an icon like this with layer?

I can put bars with text together but the space between bars is too wide. any suggestion ?

I wonder if I can just do something to make it scale (1 0.5) ?

My current solution is using css to control it. I wonder if there is any build-in solution

**Comment by paustint** [comment]
@maxisam - while I don't think it is perfect, I was able to get something somewhat close using OOB functionality.

![image](https://user-images.githubusercontent.com/5461649/43988789-2b359b78-9cfa-11e8-8e01-225c3a4b3439.png)


```html
<div class="fa-4x">
  <fa-layers [ngClass]="['fa-fw']">
    <fa-icon [icon]="faSquare" [styles]="{color: 'blue'}"></fa-icon>
    <fa-icon [icon]="faBars" transform="shrink-8 up-2" [styles]="{color: 'white'}"></fa-icon>
    <fa-layers-text title="Menu" [content]="'Menu'" transform="shrink-6 down-13" [styles]="{'font-size': '0.3em', color: 'white'}"></fa-layers-text>
  </fa-layers>
</div>
```

**Comment by devoto13** [comment]
Closing as question was answered.
