### ISSUE TITLE
fa-layers-counter, how do you make it bigger?

### ISSUE THREAD

**Issue by dalu** [FortAwesome/angular-fontawesome#85]
your example
```
<fa-layers class="fa-fw">
  <fa-icon [icon]="['fas', 'envelope']"></fa-icon>
  <fa-layers-counter content="99+"></fa-layers-counter>
</fa-layers>
```
the counter is red and tiny.

How can I style it and also make it bigger?
(inb4 that's what she said)

**Comment by robmadole** [comment]
@dalu throw a screenshot in here. It's probably by design but we'll double-check.

**Comment by lucboutier** [comment]
One of my colleagues had the same issue see screenshots (tiny is default, larger with workaround below)

```
<fa-layers class="fa-fw">
    <fa-icon [icon]="['far','shopping-cart']"></fa-icon>
    <fa-layers-counter [content]="46" class="fa-icon-counter"></fa-layers-counter>
</fa-layers>
```

```
.fa-icon-counter {
  zoom: 260%;
  position: relative;
  left: 2.1rem;
  bottom: 0.6rem;
}
```

HTH

<img width="30" alt="capture d ecran 2018-08-20 a 15 52 01" src="https://user-images.githubusercontent.com/1510790/44344459-0bcd0980-a491-11e8-909c-b1d4be46a4db.png">
<img width="35" alt="capture d ecran 2018-08-20 a 15 52 19" src="https://user-images.githubusercontent.com/1510790/44344460-0bcd0980-a491-11e8-8c9b-d49a12e27dd4.png">

**Comment by dalu** [comment]
Sorry for the late reply, been enjoying the last days of summer at the beach. I'll probably get around to try it this weekend. Will let you know how it worked and also provide a before/after screenshot.

**Comment by sebitsi** [comment]
@robmadole 
It would be nice if `<fa-layers-counter>` accepts` transform` attribute.

**Comment by dalu** [comment]
I completely forgot about that, is it ok to close this? I don't think I used it afterwards, because of the initial problem I dropped those and redesigned the UI

**Comment by sebitsi** [comment]
@dalu i think this issue should be open.
It would be nice if we have options on `<fa-layers-counter>` to move it or size it using `transform` attribute.

**Comment by robmadole** [comment]
@sebitsi to keep the `fa-layers-counter` simple we will not be adding `transform` to it. It's done with CSS now and `transform` requires JS to process.

**Comment by Arackow** [comment]
@robmadole can we reopen this? The workaround listed here isn't a good one since it is not standard and doesn't work on every browser. Below is what i see. the icon in question is using size="lg" so its not a huge size difference. 
![Annotation 2019-07-01 181750](https://user-images.githubusercontent.com/9533786/60470039-e40c0d80-9c2c-11e9-937c-25ec02397a63.png)

There is _something_ wrong here.

**Comment by AmbroiseVuaridel** [comment]
@robmadole Any news ?

**Comment by devoto13** [comment]
Here is a better implementation to control appearance of the counter, which works across browsers:

```
@Component({
  template: `
    <fa-layers [fixedWidth]="true">
      <fa-icon [icon]="faShoppingCart"></fa-icon>
      <fa-layers-counter [content]="42" [classes]="['fa-custom-counter']"></fa-layers-counter>
    </fa-layers>`,
  styles: `
    :host ::ng-deep .fa-custom-counter {
      transform: scale(0.5) translateX(50%) translateY(-50%);
    }`
})
export class AppComponent {}
```

1. Make sure to set `fixedWidth=true` to ensure that counter is correctly positioned.
2. Use CSS transform to adjust size/position of the counter. Try playing with the values to achieve the desired look. 

Demo: https://stackblitz.com/edit/angular-z8v4ux-gzuzmd

**Comment by AmbroiseVuaridel** [comment]
@devoto13 Awesome ! Thanks !
