### ISSUE TITLE
Svg mask on safari fails when base href is defined

### ISSUE THREAD

**Issue by lucboutier** [FortAwesome/angular-fontawesome#86]
Hi,

Mask rely on svg url based reference which seems to cause issues with the <base href="/"> tag.

I found some information that describe the problem here angular/angular.js#8934 and here airbnb/lottie-web#360

I tried to find a workaround using APP_BASE_HREF and some generation features of angular cli but didn't managed to get anything working for both my prod and dev env. I guess that the solution may lie more on the angular CLI side so I created also an issue there  angular/angular-cli#11952 on angular cli)

Have you encountered such issue ? Is there any known workaround ?

**Comment by pavax** [comment]
We faced the same problem in our project. We ended up in creating a angular directive that decorates the `<fa-icon>` component for angular-fontawesome.

The svg element are updated in the ngAfterViewInit phase and listen for router `NavigationEnd` events. In that case also dynamically added component will be decorated as well as on every route/location change

see here: https://gist.github.com/pavax/117ef58db65f8fe1a43a2c5b536abcd7

**Comment by Sandeep2408** [comment]
Hello 
You need to pass full url and append id of mask tag in the image which want to mask. It works fine with base url also. For example

<svg width="100%" height="100%" viewBox="0 0 588 681" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns">
    <defs>
        <mask id="itringlemasking">
          <polygon transform="translate(294.000000, 340.500000) scale(-1, 1) translate(-294.000000, -340.500000)" fill-rule="evenodd" clip-rule="evenodd" fill="#F5F5F5" id="Mask" points="0 681 588 340.49085 0 0"></polygon>
        </mask>
      </defs>
      <image width="100%" height="100%" preserveAspectRatio="xMidYMid slice" xlink:href="images/image-need-to-mask.png" mask="url(http://domain-name/test.html#itringlemasking)"></image>    
</svg>

**Comment by devoto13** [comment]
See https://github.com/FortAwesome/Font-Awesome-Pro/issues/1422#issuecomment-520084263. It is a Safari bug. I've asked `fontawesome-svg-core` to implement a workaround to resolve this issue.

**Comment by devoto13** [comment]
This was finally fixed in Safari 13.1.

**Comment by devoto13** [comment]
I'm going to close it as it is working correctly in both Safari 13.1 and Safari 14. And it doesn't seem to be worths the effort fixing it in the older versions.

You may consider using a workaround described in https://github.com/FortAwesome/angular-fontawesome/issues/86#issuecomment-460662573 if you need to support older versions.
