### ISSUE TITLE
Invalid transform property inside CSS3 column-count rule.

### ISSUE THREAD

**Issue by rafek1241** [FortAwesome/angular-fontawesome#93]
### Describe the problem
I use bootstrap 4 with angular. I discovered that when i want to icon with a mask & transform

`<fa-icon [icon]="['fas', 'award']" transform="shrink-10 right-3 down-4" size="6x" [fixedWidth]="false" [mask]="['fas','file']"></fa-icon>
`
Then in result i have that:
![image](https://user-images.githubusercontent.com/9272027/45266160-de072f00-b456-11e8-872b-9abd3ac0343c.png)

Now for an example we will have code like that:
```
<span *ngFor="let i of [1,2,3,4]">
  <fa-icon [icon]="['fas', 'award']" transform="shrink-10 right-3 down-4" size="6x" [fixedWidth]="false" [mask]="['fas','file']"></fa-icon>
</span>
<div class="card-columns">
</div>
```

Then we will get that:
![image](https://user-images.githubusercontent.com/9272027/45266186-49510100-b457-11e8-9395-a794c8a48083.png)

**Problem occurs when we will nest this icons inside column-count rule:**
**Code:**
```
<div class="card-columns">
  <span *ngFor="let i of [1,2,3,4]">
    <fa-icon [icon]="['fas', 'award']" transform="shrink-10 right-3 down-4" size="6x" [fixedWidth]="false" [mask]="['fas','file']"></fa-icon>
  </span>
</div>
```

**Result:**
![image](https://user-images.githubusercontent.com/9272027/45266205-86b58e80-b457-11e8-8c0b-7973c9306d15.png)

### What did you expect?

I expect that transform inside this icons shouldn't be changed by rule outside directive.

**Comment by rafek1241** [comment]
For card-columns class CSS:
`.card-columns {
    -webkit-column-count: 3;
    column-count: 3;
    -webkit-column-gap: 1.25rem;
    column-gap: 1.25rem;
    orphans: 1;
    widows: 1;
}`

**Comment by devoto13** [comment]
@rafek1241 I've added your code into https://stackblitz.com/edit/angular-z8v4ux-bambjj and can not reproduce the problem. Please update the linked application by adding minimal code to reproduce the issue. 

PS Also in the future please provide a runnable minimal reproduction of the problem, when reporting issue (on e.g. StackBlitz).

**Comment by rafek1241** [comment]
@devoto13 
![image](https://user-images.githubusercontent.com/9272027/45300635-3437a900-b50f-11e8-9d50-c1621a6cb001.png)

I have opened your simulation and for me it look like that. That is the problem. Different position of masked icon.

**Comment by devoto13** [comment]
@rafek1241 Which version of Chrome do you use? I've tried in Chrome 69, Safari 11.1 and Firefox 62 on macOS and all work correctly.

**Comment by rafek1241** [comment]
![image](https://user-images.githubusercontent.com/9272027/45301272-e6bc3b80-b510-11e8-9431-4424b5e7f7e8.png)

**Comment by rafek1241** [comment]
@devoto13 
I have updated chrome, clear app storage and open this simulation:
![image](https://user-images.githubusercontent.com/9272027/45301389-2551f600-b511-11e8-94bd-c25a33b9e8cd.png)

**Comment by devoto13** [comment]
@rafek1241 Can you try in incognito window/with all plugins disabled/different browser?

**Comment by rafek1241** [comment]
Opera:
![image](https://user-images.githubusercontent.com/9272027/45301700-c0e36680-b511-11e8-9200-ec48dbab916b.png)
Firefox:
![image](https://user-images.githubusercontent.com/9272027/45301732-d22c7300-b511-11e8-8d7e-6f58bdfa644b.png)

**Comment by devoto13** [comment]
@rafek1241 Managed to reproduce now. Had to reduce window size for it.

It works correctly in Safari and Firefox, but doesn't in Chrome and Opera. Also it reproduces only in interaction with Multiple column layout. Given these two things I would suspect that it may be a bug in a Blink engine.

Here is demo with just HTML/CSS: https://stackblitz.com/edit/angular-z8v4ux-gr2bir

Please, consider reporting this to Blink issue tracker.

**Comment by rafek1241** [comment]
@devoto13
I will do that.

**Comment by rafek1241** [comment]
Issue has been closed because it's inside the chromium engine.
