### ISSUE TITLE
Accessibility: Tabbing on IE11

### ISSUE THREAD

**Issue by kalexmills** [FortAwesome/angular-fontawesome#95]
### Describe the problem

fa-icon provides SVG images. There is a [known issue](https://stackoverflow.com/questions/29393144/how-to-prevent-svg-elements-from-gaining-focus-with-tabs-in-ie11) with IE11, svg and tab indexing.

### What did you expect?

I expected that the fa-icon component would expose some way to setting focusable=false on the internal <svg> tag.

We should be able to specify `focusable=false` on the internal svg to avoid an extra tab in accessible applications.

### Reproducible test case

https://stackblitz.com/edit/angular-z8v4ux

In the standard test case, this behavior can be seen. On IE11, it will take 2 extra tabs to tab between the URL and the link at the bottom. On Chrome, the user can tab smoothly between the URL and the link with no extra tabs.

**Comment by devoto13** [comment]
This sounds reasonable to me.

@robmadole Is it something you would consider to implement in SVG core? Maybe even by default if we can't think of any drawbacks?

**Comment by jboeijenga** [comment]
@devoto13 Thanks for your comment!
I had issues with the svg element not having the focusable attribute and IE11 as well. After updating `@fortawesome/fontawesome-svg-core` to `1.2.13` I was able verify these issues are now resolved.

**Comment by devoto13** [comment]
Closing as this issue seems to be fixed now.
