### ISSUE TITLE
Feature request: support viewEncapsulation.Native and ShadowDom

### ISSUE THREAD

**Issue by arthurRbr** [FortAwesome/angular-fontawesome#96]
When using `viewEncapsulation.Native` (shadow DOM), some styles are missing in the component because they are set globally in the `head` section. For example, you cannot set the `size`.

This would be a nice evolution to support [Angular Elements](https://angular.io/guide/elements) (web components) that can be shared across other websites without leaking on the global DOM.

**Comment by RezaRahmati** [comment]
Please support this feature, it's needed when creating web components

**Comment by bjornharvold** [comment]
Would love support for this!
