### ISSUE TITLE
How can I add a Hover text something like a title attribute to an fa-icon element?

### ISSUE THREAD

**Issue by nodeCodeNinja** [FortAwesome/angular-fontawesome#97]
### Describe the problem you'd like to see solved or task you'd like to see made easier
I would like this attribute to take a title attribute and show it on hover

### Is this in relation to an existing part of angular-fontawesome or something new?
Something New

### What is 1 thing that we can do when building this feature that will guarantee that it is awesome?
I am not sure. May be this is not a functionality of an icon library

### Why would other angular-fontawesome users care about this?
This to me looks like a general requirement

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?
7

### Feature request checklist

- [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
- [ ] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
- [x] I have [searched for existing issues](https://github.com/FortAwesome/angular-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by devoto13** [comment]
You can use `title` attribute for this, it works (hover over `fortAwesome` icon): https://stackblitz.com/edit/angular-z8v4ux-m7e3qm

If you want a custom tooltip I don't think this is something, which should be supported in `angular-fontawesome` or FontAwesome in general, but I'm pretty sure you can use one of the popover/tooltip libraries out there to show tooltip/popover bound to an icon. [ng-bootstrap](https://ng-bootstrap.github.io/#/components/tooltip/examples) for example.

**Comment by nodeCodeNinja** [comment]
Thanks for the response.

It indeed works. Thanks fr putting up the example.
